ionic-team/capacitor

ios/Capacitor/Capacitor/CAPPlugin.h
ios/Capacitor/Capacitor/CAPPlugin.m
ios/Capacitor/Capacitor/Plugins/Browser.swift

iOS 13 supports popover presentation on iPhones, so allow Browser to also use popover presentation in that case

fix(ios): allow Browser popover presentation if supported

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java

fix(android): don't remove LocalNotification from pending on dismiss

---

site/docs-md/android/troubleshooting.md

closes https://github.com/ionic-team/capacitor/issues/2822

docs(troubleshooting): Add Android X information and workaround

---

core/package.json
core/src/web-runtime.ts

Fixes https://github.com/ionic-team/capacitor/issues/456. This guards the `Proxy` usage is order to ensures that loading Capacitor does not throw a Syntax Error in IE11 and other older browser engines.

fix(web): Gracefully degrade Proxy usage to fix IE11

---

site/docs-md/guides/deep-links.md

When creating `applinks.json` (as opposed to Google's requirement to call the file `assetlinks.json`, I get the following error when clicking "Test statement" in the [Google Statement List Generator and Tester](https://developers.google.com/digital-asset-links/tools/generator):
> No app deep linking permission found for nl.APP_NAME.app at app.APP_NAME.nl.
Renaming to `assetlinks.json` (like Google also recommends) [solves this issue](https://developer.android.com/training/app-links/verify-site-associations). Updated the docs to reflect this change.

Rename applinks.json to assetlinks.json

---

site/docs-md/ios/configuration.md

There was no information on this and I had a wild goose hunt for this information all over issue & stack overflow.
I added everything I learned to the documentation here.

docs(ios/configuration): Add information on how to rename your app

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

The applicationState active check was there to try to solve a visual glitch when swiping apps if one of them was showing a keyboard, but was not solving it completely and causes other problems, so I'm removing the check. 
closes #2804

fix(ios): remove applicationState check on keyboard plugin

---

site/docs-md/android/updating.md

To me this is not so specific. I'd prefer to have a clear path, since the android project contains several gradle files in different directories.

docs(updating): Provide a full path to variables.gradle file

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Clipboard.java

I encountered app crash when reading the content of the clipboard since 2.0.0+
It only occurs on Android platform and in my case on a Samsung with Android 7.
When my clipboard is empty (like after a reboot) and I attempt to read it, the plugin crashes the app because of a `NullPointerException`.
I checked the Android documentation and found the method [hasPrimaryClip()](https://developer.android.com/reference/android/content/ClipboardManager#hasPrimaryClip()).
So I implemented it in order to check if the primary clip exists. If it's the case, normal behavior happen otherwise the clipboard content will be set to an empty string.

fix(android) : App can crash on clipboard.read if empty

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Camera.swift

Now, Prompt message in camera plugin is hard coding.
I think this be able to change users label is better.
Thanks.

feat(camera): make prompt strings localizable

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Geolocation.java

and use `PRIORITY_LOW_POWER` if not enabled, otherwise no location is returned
closes https://github.com/ionic-team/capacitor/issues/2854

fix(android): check if NETWORK_PROVIDER is enabled

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

On Android, the default action of Filesystem.readFile creates a malformed base64 string with newlines added.
This is acceptable in the browser when displaying images, for example, but not when base64 data is expected.
ref [https://developer.android.com/reference/android/util/Base64#NO_WRAP]

fix(android): make readFile don't return newlines on base64 strings

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Haptics.java
core/src/core-plugin-definitions.ts
site/src/assets/docs-content/apis/haptics/api.html

Implements selection haptic feedback for android.

feat(android): implement selection haptic feedback

---

android/capacitor/src/main/java/com/getcapacitor/Logger.java
ios/Capacitor/Capacitor/CAPLog.swift
site/docs-md/basics/configuring-your-app.md

At the moment hideLogs has to be specified by platform, this allows a common hideLogs root preference to set both platforms at once.
It still respects the platform preference if set.
Also document the preference

feat: Add common hideLogs option

---

cli/src/cordova.ts

remove the @ from the dependency only if it's not on the start of the plugin name, in that case it's a scope, not a version.

fix(cli): avoid infinite loop on scoped dependencies

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPPlugin.h

variation of #2307 
changes:
Android method renamed from `shouldOpenExternalUrl ` to `shouldOverrideLoad` (more similar to the Android WebView method, and matches the iOS name). Logic changes, false load, true abort, null default.
ios method renamed from `shouldOverrideLoadWith` to `shouldOverrideLoad`, with a single `WKNavigationAction` param instead of two (you can get both request and navigationType from it).
Method return type changed from Bool to NSNumber so it can return nil.
And as it can return nil now, change logic to work as on Android (false load, true abort, nil default)
closes #2307 
closes https://github.com/ionic-team/capacitor/issues/70

feat: Allow plugins to override navigation

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java
cli/src/common.ts
ios/Capacitor/Capacitor/Plugins/SplashScreen.swift

Instead of setting the default native value to 0 as done on https://github.com/ionic-team/capacitor/commit/b29346b2bf9d41ec3be621f80435b306c1027941
set the default values back to 3000 and make new projects have 
```
"plugins": {
"SplashScreen": {
"launchShowDuration": 0
}
}
```

fix: set launchShowDuration to 0 on new projects only

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/NotificationChannelManager.java
core/src/core-plugin-definitions.ts

Please add notification vibration option on channel manager, it's very useful

feat(android): add vibration option to notifications channel

---

cli/src/ios/update.ts

some plugins rely on this macro to not compile UIWebView code, so add it to CordovaPlugins pod so the code can be excluded

feat(cordova): Add WK_WEB_VIEW_ONLY=1 preprocessor macro

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

closes https://github.com/ionic-team/capacitor/issues/2106

fix(android): remember camera prompt selection after permission result

---

cli/src/cordova.ts

the plugin just apply plugin com.google.gms.google-services, but Capacitor already does it, so it's not needed and makes the apply of Capacitor to fail and show the `google-services.json not found, google-services plugin not applied. Push Notifications won't work` that might confuse users, so make the CLI skip it.

fix(cordova): Add cordova-support-google-services to incompatible list

---

site/docs-md/basics/workflow.md

update respects semver, so people on v1.x following this docs weren't getting v2.x.
So changed the docs to use install @latest and add a note about update

docs(workflow): change update instructions to get latest version

---

site/docs-md/apis/splash-screen/index.md

document that `splashFullScreen` and `splashImmersive` are android only
closes https://github.com/ionic-team/capacitor/issues/2934

docs(splash): Full Screen & Immersive are android only

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

when trying to read public folders (`FilesystemDirectory.Documents` or `FilesystemDirectory.ExternalStorage`) 
closes #2948

fix(android): Prevent Android 10 crash on Filesystem.readdir

---

core/src/web-runtime.ts

Fixed https://github.com/ionic-team/capacitor/issues/2850
Solves server rendering issues by checking if `window` is actually defined (which is not the case when doing server rendering).

fix(web): improve Proxy check to avoid SSR problems

---

site/docs-md/guides/deep-links.md

I was working with the `apple-app-site-association` file today, banging my head against the wall why it wasn't working.
Then I realized there was a comment at the top of the file that was causing my file to be interpreted as a file to be downloaded (not a content-type of JSON). LOL, programming...
I created this PR to hopefully help clarify the example a little bit more and prevent others from running into the same issue (although I know I am the dumb one 😀)
Thanks for your hard work 🙏
Let me know if you have any questions!

docs(deep-links): clarify apple-app-site-association file

---

cli/src/ios/update.ts

framework headers are being added as plugins source code an that is causing problems when there are mixed swift and objective-c plugins because of the generated CocoaPods umbrella.
This change prevents CocoaPods from adding the files as they are not needed because they are in the .framework already and avoids those conflicts.
Some reported issues that had this problem:
https://github.com/ionic-team/capacitor/issues/2357
https://github.com/ionic-team/capacitor/issues/2625

fix(cordova): Exclude framework headers

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/TmpViewController.swift

instead of having the tmpWindow always present, init it when it's needed and destroy it when it's not needed so it doesn't mess up with orientation plugin
closes https://github.com/ionic-team/capacitor/issues/2977
closes https://github.com/ionic-team/capacitor/issues/2892

fix(ios): Create tmpWindow when is needed and destroy it when not needed

---

site/docs-md/android/configuration.md
site/docs-md/android/index.md
site/docs-md/apis/app/index.md
site/docs-md/apis/camera/index.md
site/docs-md/apis/geolocation/index.md
site/docs-md/apis/push-notifications/index.md
site/docs-md/apis/status-bar/index.md
site/docs-md/basics/workflow.md
site/docs-md/cordova/using-cordova-plugins.md
site/docs-md/electron/index.md
site/docs-md/getting-started/index.md
site/docs-md/guides/deep-links.md
site/docs-md/guides/ionic-framework-app.md
site/docs-md/guides/push-notifications-firebase.md
site/docs-md/ios/index.md
site/docs-md/plugins/android.md
site/docs-md/plugins/index.md
site/docs-md/plugins/ios.md
site/docs-md/plugins/js.md
site/docs-md/plugins/web.md
site/docs-md/web/index.md

there is a problem in the relative links that don't work depending on if the page ends in / or not, we have received a lot of PRs changing some links back and fort, but they just break the other url.
making them absolute should avoid the problem

docs: make links to other pages absolute

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

On iOS 13 `presentationControllerDidDismiss` is called instead of `popoverPresentationControllerDidDismissPopover`
closes https://github.com/ionic-team/capacitor/issues/3008

fix: send error on photos picker dismiss on ios 13

---

android/capacitor/build.gradle
scripts/deploy.sh
scripts/deploy/android.sh

`com.novoda:bintray` is not compatible with Gradle 6+ required in Android Studio 4, and it appears we are no longer using this as originally intended. Publishing logic for capacitor-android library module is not required for Capacitor apps to function. 
Resolves #3003

fix(android): remove bintray publishing plugin to fix Gradle 6+ issues

---

cli/package.json

This should make the CLI tests run faster.

test(cli): run tests with max workers, not in band

---

site/docs-md/README.md
site/docs-md/cordova/migrating-from-cordova-to-capacitor.md
site/docs-md/guides/splash-screens-icons.md

While v1.0 milestone is ongoing for cordova-res, generating splash screens and icons comes up a lot in the community. With the recent addition of Capacitor support (native projects) in cordova-res, I'm opening this simple PR to get folks started.
It's intentionally as short as possible, since we know the package name will change, how to run it will inevitably change, etc.

[Docs] Add basic guide for generating Splash Screen/icons

---

core/src/core-plugin-definitions.ts

add basic information about the push notification methods.
closes #2998

docs(push): Add descriptions to push notification methods

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

Currently, when the keyboard hides, if the user is scrolling in the webview the `keyboardWillHide` event won't fire and the frame won't update until the scrolling stops. See this app that hides the keyboard when scrolling starts:
Current Behavior:
Fixed Behavior:

fix(ios/keyboard): update frame immediately when keyboard hides

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Permissions.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Permissions.swift
site/src/assets/docs-content/apis/permissions/api.html

Add checkMicrophone in permission plugin

feat(Permissions): allow microphone check

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

To avoid errors in logcat about null cookies

fix(android): set cookie on proxied request only if exists

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

the content type can be obtained from the request, no need for a connection

chore(android): avoid connection on proxy to check the content type

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java

I've noticed some actions are not dismissing the notification when you choose an action, all of them should, so removing the check.

fix(android): LocalNotification action not dismissing notification

---

example/ios/IonicRunner/Podfile
example/ios/IonicRunner/Podfile.lock

The iOS podfiles recently moved, this updates the IonicRunner app with the right location so the example docs remain accurate.
(Not sure if this is the right Podfile.lock update, it was automatically generated and seems to work okay).

chore: Update the location of capacitor pods for IonicRunner

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
android/capacitor/src/main/java/com/getcapacitor/CapacitorWebView.java
android/capacitor/src/main/java/com/getcapacitor/Logger.java
android/capacitor/src/main/java/com/getcapacitor/Splash.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java

When[ I made](https://github.com/ionic-team/capacitor/pull/3055) Config class non static, it broke plugins using it
This PR reverts the changes in Config class, deprecates it and introduces CapConfig class that is the current non static Config

fix: revert static Config class

---

cli/src/common.ts

Update the error message displayed when a user tries to add a native platform to their project, before having built their web code.
Changes:
- Fix the More Info link to point to the correct page (/basics/building-your-app instead of /basics/configuring-your-app).
- Help the user by telling them _which_ property to change in capacitor config (webDir).
- Added build details for both Ionic apps and non-Ionic apps.
Wasn't sure how to format correctly for newlines - this function doesn't use log("") like the others.

Clarify "missing web assets directory" error message

---

README.md
android/capacitor/src/main/java/com/getcapacitor/Splash.java
capacitor-cordova-ios-plugins/CordovaPluginsResources.podspec
cli/src/common.ts
cli/src/tasks/add.ts
cli/test/util.ts
core/README.md
example/src/pages/app/app.html
ios/Capacitor.podspec
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/Plugins/SplashScreen.swift
ios/CapacitorCordova.podspec
plugin-template/ios/Plugin/Plugin.swift

Update all the links to use the new https://capacitorjs.com website! 🎉

chore: update site links

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java
ios/Capacitor/Capacitor/Plugins/SplashScreen.swift

When using the plugin in TS, the call `Splash.show({autoHide:false})` was never resolving the returned promise because the native call to complete the call was never invoked. It was only called with autoHide = true.
fixes: #3143

fix(SplashScreen): show method not resolving if autoHide is false

---

cli/src/tasks/new-plugin.ts

When generating a new plugin, pin the core, ios and android dependencies to the cli version used to build the plugin

chore(cli): pin cli version instead of latest on plugin generation

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Share.java

Hello everyone,
This is a minor refactor that allows to share a file (a url that starts with `file:`) with text on android. I noticed that the ios version already supports this functionality.
I'm not sure if this is considered a "breaking change" but if it gets merged it **will** affect what is shared on the following scenario: 
1. android device
2. share plugin called with both `url` and `text`
Before fix: It will only share the file
After fix: it will share the file and will also have text if the receiving app supports it.
Demo:
https://drive.google.com/file/d/141Q0G3hA2tf8n5k_rNMc7WkhJClrle6i/view?usp=sharing
All feedback is welcome :)
Have fun

feat(android): share both text and url at the same time

---

android-template/variables.gradle
android/capacitor/build.gradle

add `androidxExifInterfaceVersion` variable into the `variables.gradle` file with value set to 1.2.0
use the variable in capacitor's build.gradle file but also default to 1.2.0 if not set

chore(android): Make androidx.exifinterface version configurable

---

cli/src/cordova.ts

If using `cordova-plugin-cleartext`, the `usesCleartextTraffic` gets added twice, and doesn't have a whitespace between them, so fails to build.
This PR adds the whitespace and also prevent the second usesCleartextTraffic attribute being added if some plugin already added it.

fix(cli): Avoid duplicate usesCleartextTraffic attribute

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java
core/src/core-plugin-definitions.ts
core/src/web/device.ts
electron/src/electron/device.ts
ios/Capacitor/Capacitor/Plugins/Device.swift

This PR adds `appName` (the app's display name) and `appId` (the app's bundle id) to `Device.getInfo()`.
I thought this can come in handy when gathering debug information. After moving one of my apps over from Cordova, `cordova-plugin-app-version` is the only remaining plugin I can not remove just yet as I need to display the app's name and bundle id.

Extend device plugin

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

Fixes #3261 .
The issue was a check done: if the splash is visible, it was returning without completing the call.

fix(android): Splash.show not resolving if splash is visible

---

cli/src/common.ts
cli/src/tasks/add.ts
cli/src/tasks/copy.ts
cli/src/tasks/doctor.ts
cli/src/tasks/open.ts
cli/src/tasks/update.ts

https://github.com/ionic-team/capacitor/pull/3263 is only warning in add, so will only on new projects or users adding electron for the first time, but existing electron users won't notice and they need to move too because all commands are being removed in v3.
So this PR adds the deprecation notice in all electron commands

chore(cli): add deprecation notice for all electron commands

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeDelegate.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPMessageHandlerWrapper.swift
ios/Capacitor/Capacitor/CAPPlugin.h
ios/Capacitor/Capacitor/CAPPlugin.m
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift
ios/Capacitor/Capacitor/Plugins/Browser.swift
ios/Capacitor/Capacitor/Plugins/Camera.swift
ios/Capacitor/Capacitor/Plugins/Geolocation.swift
ios/Capacitor/Capacitor/Plugins/Keyboard.m
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift
ios/Capacitor/Capacitor/Plugins/Modals.swift
ios/Capacitor/Capacitor/Plugins/Network/Network.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift
ios/Capacitor/Capacitor/Plugins/Share.swift
ios/Capacitor/Capacitor/Plugins/SplashScreen.swift
ios/Capacitor/Capacitor/Plugins/StatusBar.swift
ios/Capacitor/Capacitor/Plugins/Toast.swift
ios/Capacitor/Capacitor/Plugins/WebView.swift

Assorted collection of changes cherry-picked from exploratory work. Primary focus on breaking retain cycles, clarifying ownership, and avoiding implicit retentions.
- Relationships reworked to make parent and delegate relationships weak
- Added nullability annotations to Plugin API
- Split WKUserContentController into a separate object to fix a retain cycle (expected to be revisited in future refactoring)
- Added capture lists to avoid implicit retains of self in blocks
- Minor fixes for some warnings

iOS memory cleanup

---

cli/src/config.ts
cli/src/tasks/add.ts

When people run `npx cap add electron` in Capacitor 3, we probably want to point them in the right direction. First, they install it, then they can add it to their app.
closes https://github.com/ionic-team/capacitor/issues/3140

chore(cli): print warning when adding electron

---

android/capacitor/src/main/java/com/getcapacitor/BridgeFragment.java

The purpose of `BridgeFragment` is to integrate Capacitor into existing Android apps in cases where `BridgeActivity` would not fit into the existing native UI.
This is nice because it enables a gradual transition from a native codebase to Capacitor.
However, it is unclear how custom plugins should be passed to `BridgeFragment`.
Therefore, this PR introduces a new method to mimic the usage pattern of `BridgeActivity`.

Pass custom plugins to BridgeFragment

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

If file is empty stream.available() returns 0, so make available return -1 when the stream is null to distinguish between empty and not found
closes https://github.com/ionic-team/capacitor/issues/3312

fix(android): Don't return 404 on empty files

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/CameraSettings.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ImageUtils.java
core/src/core-plugin-definitions.ts
example/src/pages/camera/camera.html
example/src/pages/camera/camera.ts
ios/Capacitor/Capacitor/Plugins/Camera.swift

This PR is a re-opening of #3297 because of wrong base branch and a retry of #2050 and should fix ionic-team/capacitor-plugins#2 (also the discussion #1952). I've used the Android implementation of @sandstrom (shout-out) and also did an implementation for iOS.
There's now a `preserveAspectRatio` flag on CameraOptions which is set to `false` by default.
I've also fixed a bug where the app would crash while saving an image to the gallery on Android. This only happens on certain devices but I was able to reproduce it by creating 32 images until it crashed. A random UUID gets now appended to the file name to make sure no name clashes happen anymore.
@dwieeb is there anything I can do to provide some testing or how do you test this fix?

add preserveAspectRatio to CameraOptions while resizing an image

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

This branch avoids a bug discovered by an enterprise client. In the reproduction case, if a user performs a double tap on a `tel` link, the application will get stuck in the `inactive` state. When opening the URL, the system presents an action sheet so the user can confirm the dial operation. However, if a second `tel` URL is attempted to open while that system-supplied action sheet is on-screen (and the application is `inactive`), the application will not be moved to the `active` state if the user selects `cancel` and dismisses the sheet. The application needs to be deactivated some other way (app switcher, etc) for the normal application life cycle events to be restored.
Under normal operations, the application shouldn't be asking the system to open URLs if it is not active so I'm not …

fix(iOS): Only open a URL while the application is active

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/DateMatch.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/TimedNotificationPublisher.java

I've read the contributing docs and I hope I'm doing this properly, please feel free to educate me on how to best approach this.
I needed to use the cron-like `on` notifications on a project of mine to make daily notifications happen at a certain time (like every day at 8:30 am) and noticed the Android implementation didn't work properly. On iOS, it all appears to be handled by `DateComponents`, but on Android it's got a more complex custom implementation.
It's a bit hard to find documentation, but after examining the native code, it appears that the `on` style notifications are supposed to let you:
- pass a minute and have a notification repeat each hour (passing 15 would trigger every hour at :15)
- pass an hour and a minute and have a notification repeat each day (passing 14 and 30 …

fix(android): LocalNotification `on` not working properly

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

Hi guys
I ran into an app crash with my ionic app after creating 32 images and save them into the gallery (`saveToGallery: true` in `CameraOptions`) on Android 10. I could reproduce it on a Pixel 3a Emulator running Android 10 and several other physical devices running Android 10. 
This fix extracts the file name from the file path. This file name should be unique since it is generated from the timeStamp of when the picture was taken (thanks @jcesarmobile).
As you can see [here](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/provider/MediaStore.java#L1733) the name of the image is set to "Image" when no name argument was passed. I think this is where the problem starts and after that numbers get appended internally and somehow stop working after 32 …

fix(android): Provide a file name when an image is saved to the gallery to prevent app crash

---

ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin+Resources.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin+Resources.m

Some plugins use `pluginImageResource` or `pluginLocalizedString` methods and import `CDVPlugin+Resources.h` files, which were not present at the moment.
This PR add those files for better plugin support.
closes https://github.com/ionic-team/capacitor/issues/3379

fix(cordova): add CDVPlugin+Resources category for better plugin support

---

android/capacitor/src/main/java/com/getcapacitor/MessageHandler.java
android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPPluginCall.swift
ios/Capacitor/Capacitor/JS.swift

When calling `call.resolve()` it will return `undefined` instead of `{}`
`call.success()` will keep returning `{}`

chore: Make native resolve return undefined

---

core/src/plugins.ts

For the web platform, many APIs may not work, especially for IE11, for example. We need a consistent way to report that a feature is unsupported. This will be used by official plugins, but all Capacitor plugins are welcome to use it. This is just a proposal to spark discussion.
Stems from a discussion in the Haptics PR: https://github.com/ionic-team/capacitor-plugins/pull/5#issuecomment-667739490
- Usage in plugins: https://github.com/ionic-team/capacitor-plugins/blob/4862a1997c0d1e6e65f4a16a7de976083acbf4d5/screen-reader/src/web.ts#L16-L20
- Usage in apps: https://github.com/ionic-team/capacitor-testapp/blob/84aaab694f05dadebb1666ff130f33130a279ec1/src/pages/ScreenReader.tsx#L38-L49

Unsupported Browser Exception proposal

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java
android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
ios/Capacitor/Capacitor/CAPPluginCall.swift
plugin-template/android/CLASS_NAMEPlugin.java
plugin-template/ios/Plugin/CLASS_NAMEPlugin.swift

- `success()` is now deprecated (use `resolve()`)
- `error()` is now deprecated (use `reject()`)

Deprecate redundant PluginCall methods

---

cli/src/cordova.ts

The plugin is being reworked to be compatible with Capacitor and people can't test it unless we remove it from the skip list.
Related: https://github.com/ionic-team/capacitor/discussions/3431

chore(cli): remove cordova-plugin-googlemaps from skip list

---

android-template/app/build.gradle

@dwieeb to answer your question from the other PR I made..
The presence of these items in the list means they *will* be ignored. (The default string includes the `<dir>_` pattern that ignores the directories, thus we override it here to omit that and allow them). The exclamation point here means not to print a warning about it (vs. meaning negation like in other code)
Source: https://android.googlesource.com/platform/frameworks/base/+/6d2c0e5/tools/aapt2/Files.h#88

Added asset ignore string to allow dirs beginning with underscore in assets

---

cli/src/ios/update.ts

fix(cli): replace SDK variables with default values on Cordova plugins

---

cli/src/plugin.ts

While doing reviews I noticed this property that is not used, so better remove it.

chore(cli): Remove doctor entry from PluginManifest interface

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

Resolves #3601
Fix in 3.x: #3596

fix(android): move splash screen trigger before the webview render to prevent flicker (2.x)

---

cli/src/tasks/update.ts
cli/test/update.android.spec.ts
cli/test/update.ios.spec.ts

fixes https://github.com/ionic-team/capacitor/issues/3592

fix(cli): halt update upon failure

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Share.java

closes https://github.com/ionic-team/capacitor/issues/3638

fix(android): Avoid SecurityError on Android 10 file share

---

cli/src/android/open.ts
cli/src/config.ts
cli/src/definitions.ts
cli/src/web/copy.ts

This is a breaking change that removes the `windowsAndroidStudioPath` and `linuxAndroidStudioPath` configuration options, combining them into a `STUDIO_PATH` environment variable, which can be set on any OS.
The naming style of `STUDIO_PATH` comes from other Android Studio environment variables: https://developer.android.com/studio/command-line/variables
addresses https://github.com/ionic-team/capacitor/issues/230 and https://github.com/ionic-team/capacitor/issues/2493

feat(cli): STUDIO_PATH environment variable

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java

At the moment `onRequestPermissionsResult` handles the prompt/prompt-with-rationale/denied logic, but since most plugins will overwrite it, that functionality get lost and `checkPermissions` always returns prompt because of that.
By adding a new `handlePermissions` function in Plugin class that handles that logic, users can call it on their `onRequestPermissionsResult` override.

feat(android): Add handlePermissions function for plugins to call

---

android/capacitor/src/main/java/com/getcapacitor/plugin/WebView.java

Since WebView plugin will remain in here, make it use the new `CapacitorPlugin` annotation and `resolve` instead of `success`

chore(android): Make WebView plugin use CapacitorPlugin annotation

---

ios-template/App/App/AppDelegate.swift
ios/Capacitor/Capacitor/CAPApplicationDelegateProxy.swift

This branch is follow-on work to #3678 to fix a bug and remove deprecation warnings.
- Fixes a bug where the ApplicationDelegateProxy singleton was not correctly exposed as public.
- Update the iOS template to use the new methods/definitions to avoid deprecation warnings.

chore(iOS): Clean up from bridge API changes

---

cli/src/tasks/update.ts

When running `npx cap sync` and not specifying a platform, the cli will attempt to run `pod install` without verifying it exists. This results in an error saying "pod does not exist."
When running `npx cap sync ios` the problem does not exist.

fix(cli): Properly detect cocoapods on multiple platforms

---

cli/src/config.ts
cli/src/definitions.ts
cli/src/ios/common.ts
cli/src/ios/update.ts

Fixes https://github.com/ionic-team/capacitor/issues/3603
A new environment variable `CAPACITOR_COCOAPODS_PATH` can be set to specify a specific pod installation

feat(cli): Add configurable pod path

---

cli/src/index.ts
cli/src/tasks/run.ts

Even though it takes longer (especially on iOS), I think this is the safer option for `capacitor run`.

fix(cli): run sync instead of copy during run

---

cli/src/index.ts
cli/src/tasks/run.ts

depends on https://github.com/ionic-team/capacitor/pull/3816

feat(cli): add --no-sync option to run

---

cli/src/android/common.ts
cli/src/android/doctor.ts
cli/src/android/update.ts
cli/src/config.ts
cli/src/cordova.ts
cli/src/definitions.ts
cli/src/ios/common.ts
cli/src/ios/run.ts
cli/src/ios/update.ts
cli/src/tasks/copy.ts

We want to rely on the config for file paths as much as possible to reduce hard-coding and open up the CLI to opportunity for configuring these paths in the future.

refactor(cli): consolidate paths to config

---

cli/src/index.ts
cli/src/tasks/config.ts

This is a hidden command that outputs the CLI config (including the `extConfig` from reading `capacitor.config.json` or evaluating dynamic config files).
This will be used in the Ionic CLI to know where each platform's generated `capacitor.config.json` is.

feat(cli): add config command

---

.github/workflows/ci.yml

SwiftLint is now installed by default: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md

chore(ci): remove swiftlint installation

---

android/capacitor/src/main/java/com/getcapacitor/util/HostMask.java
android/capacitor/src/test/java/com/getcapacitor/util/HostMaskTest.java
ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Having 
```
"server": {
"allowNavigation": [
"*"
]
}
```
in `capacitor.config.json` should allow all internal navigation, but it doesn't at the moment.
This PR address it.

fix: wildcard in allowNavigation

---

android-template/app/src/main/AndroidManifest.xml

Only internet permission is needed in a base Capacitor app, removing everything else.

chore: Remove permissions from android template

---

android/capacitor/src/main/AndroidManifest.xml

application is empty now, so no need to keep it
camera feature is no longer used

chore: cleanup capacitor manifest

---

ios-template/App/App/Info.plist

The template should not contain any UsageDescription string, plugins should document the ones the plugins need and users should add them when necessary

chore: remove UsageDescription strings from ios template

---

ios/Capacitor/Capacitor/CAPBridgeProtocol.swift
ios/Capacitor/Capacitor/CapacitorBridge.swift

Follow-on branch to #3678, fixing some minor issues in the bridge protocol
- Added `public` access level to extension methods that mistakenly inherited `internal`
- Deprecated `modulePrint` and removed new `print` method from the bridge
- Exposed and deprecated `getLocalUrl` method which will be superseded by a config property in #3759

chore(iOS): updating bridge protocol

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

if using 
```
"server": {
"allowNavigation": [
"*"
]
}
```
The app fails to load the local content
closes https://github.com/ionic-team/capacitor/issues/3809

fix(android): load local assets when using wildcard on allowNavigation

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java

For platform consistency. Changes the result of checkPermissions and requestPermissions to resolve undefined when no permissions are defined on the plugin.

fix(android): resolve undefined for both checkPermissions and requestPermissions by default

---

android/capacitor/build.gradle

those were used by camera, geolocation and browser plugins, so not needed anymore

chore(android): cleanup gradle dependencies

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

This fixes the “App is not implemented on ios” error in main.

fix(ios): share message handler between webview and bridge

---

package.json
scripts/lib/cli.mjs
scripts/lib/fn.mjs
scripts/lib/fs.mjs
scripts/lib/lerna.mjs
scripts/lib/repo.mjs
scripts/lib/subprocess.mjs
scripts/lib/version.mjs
scripts/sync-peer-dependencies.mjs

This will automatically keep the version range of `@capacitor/core` in `peerDependencies` up to date as part of the lerna versioning process.

chore(scripts): add version hook for syncing peer deps

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java

These changes were a breaking change but this should keep existing plugins functional with deprecation instead

fix(android): fixed breaking change to `handleOnActivityResult`

---

ios/Capacitor/Capacitor/CAPApplicationDelegateProxy.swift

otherwise I get 
> is inaccessible due to 'internal' protection level

fix(ios): expose lastURL getter

---

android-template/app/src/main/java/com/getcapacitor/myapp/MainActivity.java

Since we prefer users to use the automatic plugin detection, better remove the init code from the template.

chore(android-template): Remove init code from MainActivity

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

closes https://github.com/ionic-team/capacitor/issues/3910
supposedly the `preferredInterfaceOrientationForPresentation` override is not needed, according to the docs
> If you do not implement this method, the system presents the view controller using the current orientation of the status bar.
and that's what our code does, but it crash on portrait only apps after taking a picture. Letting the view controller do its default doesn't crash.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621438-preferredinterfaceorientationfor

fix(ios): avoid crash on portrait apps after taking a photo

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java

Called whenever one of the configurations in `android:configChanges` changes.
ref: https://developer.android.com/guide/topics/resources/runtime-changes#HandlingTheChange
resolves https://github.com/ionic-team/capacitor/issues/3535

feat(android): add onConfigurationChanged() activity lifecycle hook

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java

Ensures that the `getPermissionStates` method is called against the Plugin in case a plugin author has override it to manipulate the states.
Alternative to: https://github.com/ionic-team/capacitor/pull/3911

fix(Android): Use plugin's getPermissionStates() to support overriding

---

cli/src/android/open.ts
cli/src/config.ts

To be more consistent with the other environment variable: `CAPACITOR_COCOAPODS_PATH`.

chore(cli): rename STUDIO_PATH to CAPACITOR_ANDROID_STUDIO_PATH

---

cli/src/tasks/init.ts

Max wanted launchShowDuration value to be 0, but we couldn't do it in the middle of v2 as it was a breaking change, so we added this setting for new apps.
For the new SplashScreen plugin I'm making the default value 0, so the CLI don't need to add the value anymore.

chore(cli): remove default SplashScreen launchShowDuration value

---

android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
android/capacitor/src/main/java/com/getcapacitor/FileUtils.java
android/capacitor/src/main/java/com/getcapacitor/JSExport.java

A full context is not required for this, only an AssetManager is really needed. This allows the helper to be used when a Context isn't available.

refactor(android): readFile now takes an AssetManager instead of a full Context object

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

refactor(android): reduce access of Bridge.Builder to Package Private

---

android-template/variables.gradle
android/capacitor/build.gradle
android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java
capacitor-cordova-android-plugins/build.gradle

in variables.gradle, capacitor and capacitor-cordova-android-plugins
Added QueryPermissionsNeeded lint suppress because that it used for input file and getUserMedia, but most users won't use it, so adding intent queries on Capacitor's manifest wouldn't be a good idea.
But we would need to document somewhere that for Android 11, users need to add those queries if using input file and/or getUserMedia (not sure where would be the better place for that)

chore: bump targetSdkVersion and compileSdkVersion to 30

---

cli/src/config.ts
cli/src/declarations.ts
cli/src/definitions.ts
cli/src/ios/update.ts

`cordovaSwiftVersion` was added because in the old days each Swift version was incompatible with the previous ones and a lot of plugins were not updated to latest available Swift version.
At the moment, Xcode 12 only supports Swift 4.2 and Swift 5, and Swift 4.2 code should still compile if set a Swift 5. And even if it didn't, the plugin authors will probably update the plugin at some point, if it reached 4.2 it's probably still maintained.
Old Cordova plugins that use Swift 2/3 won't work on Capacitor apps anymore, but that's not because of Capacitor, but because of Xcode not being able to use older versions (won't work on Cordova apps neither), so the `cordovaSwiftVersion` doesn't make much sense anymore.

chore: drop cordovaSwiftVersion config option

---

cli/src/ios/run.ts

The CLI had a typo on the `-configuration` parameter.

fix(cli): run an actual debug build for iOS

---

cli/src/android/doctor.ts
cli/src/android/update.ts
cli/src/common.ts
cli/src/config.ts
cli/src/cordova.ts
cli/src/errors.ts
cli/src/index.ts
cli/src/ios/doctor.ts
cli/src/ios/open.ts
cli/src/ios/update.ts
cli/src/log.ts
cli/src/plugin.ts
cli/src/tasks/add.ts
cli/src/tasks/copy.ts
cli/src/tasks/create.ts
cli/src/tasks/init.ts
cli/src/tasks/list.ts
cli/src/tasks/new-plugin.ts
cli/src/tasks/open.ts
cli/src/tasks/run.ts
cli/src/tasks/serve.ts
cli/src/tasks/sync.ts
cli/src/tasks/update.ts
cli/src/util/cli.ts
cli/src/util/native-run.ts
cli/src/web/copy.ts

Using `process.exit()` is discouraged in NodeJS because it forcibly terminates the process. To set the exit code of the process, the `process.exitCode` property should be used. 
This PR switches the usage of `logFatal()` to a new `fatal()` function, which throws a `FatalException`. Some try/catch flows needed to be adjusted. All commands are now wrapped via `wrapAction` which catches these exceptions and prints their message in the exact same way as before.
This is a precursor for some telemetry work where we want the process to proceed even if the command fails.
relates to https://github.com/ionic-team/capacitor/issues/4020

refactor(cli): use exceptions for fatal errors, not process.exit()

---

cli/src/config.ts

Allows devs to use:
```typescript
const config = { ... };
export default config;
```
ref: https://github.com/ionic-team/capacitor/pull/3999#pullrequestreview-563747655

feat(cli): allow 'export default' style TS config files

---

cli/package.json
cli/src/index.ts
cli/src/ipc.ts
cli/src/sysconfig.ts
cli/src/tasks/init.ts
cli/src/tasks/telemetry.ts
cli/src/telemetry.ts
cli/src/util/cli.ts
cli/src/util/subprocess.ts
cli/src/util/uuid.ts

This PR adds telemetry to the Capacitor CLI, which comprises several components:
1. `npx cap telemetry [on|off]` command, which is for managing telemetry on a machine
2. New "sysconfig" for managing a system-level configuration file (for storing telemetry opt-in/out status)
3. Command-level events for gathering anonymous usage data
4. IPC system for sending event data in the background (as to not affect the performance of commands)
TODO
ref: https://github.com/ionic-team/capacitor/issues/4020

feat(cli): opt-in anonymous usage data

---

cli/src/config.ts
cli/src/cordova.ts
cli/src/definitions.ts
cli/src/tasks/copy.ts
cli/test/update.ios.spec.ts
ios-template/.gitignore
ios-template/App/App.xcodeproj/project.pbxproj

The `public` directory, which contains generated web assets, should exist alongside the generated `capacitor.config.json` within the iOS target directory, not the Xcode workspace directory.
TODO:

fix: move `public` into iOS target directory

---

cli/src/log.ts
cli/src/tasks/config.ts
cli/src/tasks/run.ts

This was causing this issue from the Ionic CLI:
```
ionic:lib:integrations:capacitor Getting config with Capacitor CLI: [ 'config', '--json' ] +0ms
SyntaxError: Unexpected token n JSON at position 0
at JSON.parse (<anonymous>)
```

fix(cli): use stderr for logs when using --json option

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m

This PR corrects a small mistake where Cordova iOS plugins were initialized with a `webViewEngine` set to `nil` which causes NPE's.
See two screenshots with before and after the changes applied.

fix(ios): correctly initialize cordova plugins with webViewEngine

---

ios/Capacitor/Capacitor/CapacitorBridge.swift
ios/Capacitor/Capacitor/JS.swift

This branch moves the point at which the `JSCall` options are coerced into the preferred swift types. The coercion strips `NSNull` objects, which is an Obj-C placeholder for `nil` in collections. Removing the object(s) changes the indexes of arguments on Cordova calls and breaks existing behavior. The coercion is moved from the `JSCall` wrapper (which is used for both types of plugins) to the point where the `CAPPluginCall` is created for Capacitor plugins.

fix(iOS): skip Swift type coercion on Cordova plugin calls

---

android/capacitor/src/main/java/com/getcapacitor/FileUtils.java

As the `BufferedReader` is reading line per line, we need to append a `\n` in the `StringBuffer`, otherwise the cordova.js and cordova plugins js files get unformatted, causing syntax errors.
This was mistakenly removed in a previous refactor.

fix(android): append missing new lines on cordova injected files

---

cli/src/config.ts
cli/src/declarations.ts
cli/src/definitions.ts
cli/src/ios/run.ts

This allows custom scheme names to be used when running `npx cap run`.

feat(cli): configurable iOS build scheme

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/Array+Capacitor.swift
ios/Capacitor/Capacitor/CAPPluginCall.swift
ios/Capacitor/Capacitor/JSTypes.swift
ios/Capacitor/CapacitorTests/BridgedTypesHelper.swift
ios/Capacitor/CapacitorTests/BridgedTypesTests.m
ios/Capacitor/CapacitorTests/BridgedTypesTests.swift

This branch extends JSValue to include NSNull in order to preserve null values sent from JS. It also adds some small extensions to Array to improve the ergonomics when working in Swift, and adds unit tests to document and verify the behavior.
This branch also deprecates `hasOption` on `CAPPluginCall` as the presence of a key in the options isn't significant and we shouldn't encourage that pattern. Typing the represented value if it is not nil is more meaningful.
This addresses the underlying cause that https://github.com/ionic-team/capacitor/pull/4048 worked around.

fix(iOS): preserve null values in bridged types

---

android-template/variables.gradle
android/capacitor/build.gradle

…x.coordinatorlayout
we are including the whole android material dependency but it's not used anymore.
On the other hand, it includes a dependency to `androidx.coordinatorlayout`, which is used.
So this PR removes `com.google.android.material` dependency and adds `androidx.coordinatorlayout`

refactor: use androidx.coordinatorlayout, not all of android.material

---

core/src/runtime.ts

Follow up to https://github.com/ionic-team/capacitor/pull/4013
I found another issue related to react-refresh trying to access `$$typeof`.

fix(core): fix another $$typeof issue

---

android/capacitor/src/main/java/com/getcapacitor/JSExport.java
android/capacitor/src/main/java/com/getcapacitor/JSInjector.java
core/src/definitions-internal.ts
core/src/runtime.ts
core/src/tests/runtime.spec.ts
ios/Capacitor/Capacitor/JSExport.swift

This PR introduces the idea of "plugin headers" that are written to JS alongside the plugin skeleton implementations.
This is required because the [core refactor](https://github.com/ionic-team/capacitor/pull/3748) changed how the `Capacitor.Plugins` object is populated and broke `isPluginAvailable()`. The new headers are necessary to know if a plugin has an implementation on native. `isPluginAvailable()` has been updated to check JS and native implementations.
I want to do a refactor later to remove the plugin skeleton implementations because they're unnecessary with our proxy and with bundling the core together.

fix: fix isPluginAvailable() for web and native

---

core/src/bridge.ts
core/src/definitions.ts

Not sure if anyone is using `nativeCallback()` directly, but if they are, this particular usage should probably be deprecated.

refactor(core): deprecate options as callback for nativeCallback()

---

ios/Capacitor/CapacitorTests/BridgedTypesTests.swift
ios/Capacitor/CapacitorTests/JSONSerializationWrapper.h

Companion to https://github.com/ionic-team/capacitor/pull/4043
This branch adds tests for the Date handling in JSTypes. It also renames the ivars in BridgedTypesTests to make the usage more clear.

test(iOS): Add tests for `Date` types in JSValue collections

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

When using adb reverse live reload is not working because of the `loadingUrl.getHost().equalsIgnoreCase(bridge.getHost())` check, so add an extra check to see if live reload is enabled, and if so, use the proxy instead of loading local assets.
Also split each check in different functions to make it more readable.
closes https://github.com/ionic-team/capacitor/issues/4125

fix(android): live reload not working when using adb reverse

---

android/capacitor/src/main/java/com/getcapacitor/JSExport.java
core/src/definitions.ts
core/src/events.ts
core/src/legacy/legacy-handlers.ts
core/src/runtime.ts
core/src/tests/bridge.spec.ts
core/src/tests/legacy.spec.ts
core/src/tests/plugin.spec.ts
core/src/tests/web-plugin.spec.ts
core/src/web-plugin.ts
ios/Capacitor/Capacitor/JSExport.swift

In 3.0.0-beta.1, `Geolocation.watchPosition()` is currently broken on web. It returns a callback ID synchronously on native but asynchronously on web (due to the [core refactor](https://github.com/ionic-team/capacitor/pull/3748)). Since all plugin methods are supposed to be asynchronous now, this PR cleans up some additional things:
- The `addListener()`, `removeListener()`, and `removeAllListeners()` methods from Capacitor 2 should be asynchronous (see https://github.com/ionic-team/capacitor-plugins/pull/223).
- The auto-generated JS plugin functions for calling into native have been removed. Instead, the core now relies more on the proxy object to hijack the plugin methods. This is achieved by relying on the "plugin headers" written by native platforms (introduced in …

refactor(core): remove plugin skeleton implementations

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

If a permission prompt is present and you manage to show another one, the previous one gets canceled and crash the app.
When the prompt is canceled, the `grantResults.length` is `0`, so the PR checks the lenght and if 0, reject with `PERMISSION_DENIED_ERROR`.
Could use a new error, but that probably requires a minor release, and verified that the problem is not present on Capacitor 3 (probably because of the usage of the callback APIs), so this will be short lived.
closes https://github.com/ionic-team/capacitor/issues/4170

fix(android): Reject on permission prompt cancelation

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java
android/capacitor/src/main/java/com/getcapacitor/util/PermissionHelper.java

**Manifest Permission Declaration**
- Added `isPermissionDeclared(String alias)` allowing plugin developers to check if permissions are declared in Manifest using Aliases. (Naming "declared" matches how [Android documentation](https://developer.android.com/training/permissions/declaring) discusses adding these permission strings).
- Deprecated `hasDefinedPermissions(String[] permissions)` and moved to `PermissionHelper`. Expected use internal only but kept as a helper.
- Deprecated `hasDefinedRequiredPermissions`. Plugin authors can use `isPermissionDeclared` with aliases to check if needed.
- Removed `hasDefinedPermissions(Permission[] permissions)` method added during earlier Capacitor 3 work, was similar to `hasDefinedPermissions(String[] permissions)`.
**Checking Permissions**
- …

refactor(android): permission API cleanup

---

cli/src/android/update.ts
cli/src/common.ts
cli/src/cordova.ts
cli/src/ios/update.ts
cli/src/tasks/copy.ts

The Capacitor CLI developer experience can be improved when using livereload by not requiring the web asset directory to exist if `server.url` is being used. 
BEFORE:
AFTER:

feat(cli): do not require webDir when server.url is set

---

core/src/legacy/legacy-handlers.ts
core/src/tests/legacy.spec.ts

I wrapped the logic in the legacy handlers to only add the empty Cordova object and the native event handlers to only be executed when it is running on a device. This fixes the issue with Ionic Core wrongly identifying web apps as being identified as Cordova and hybrid apps as brought up in issue #4198.

fix(core): do not add window.cordova on web apps

---

README.md
cli/src/common.ts
cli/src/config.ts
cli/src/ios/common.ts
cli/src/ios/doctor.ts
cli/src/tasks/copy.ts
cli/src/tasks/init.ts
cli/src/tasks/list.ts
cli/src/tasks/open.ts
cli/src/tasks/run.ts
cli/src/tasks/sync.ts
cli/src/tasks/update.ts

Removed the `platforms.length === 0` checks as we always return at least web as platform, so they will never be 0.
Removed the `checkIOSProject` checks as the ios folder was already being checked by `selectPlatforms` function, so that code was not reachable.
Replaced the npx cap add instructions on `init` with a link to `https://capacitorjs.com/docs/v3/getting-started#where-to-go-next`
closes https://github.com/ionic-team/capacitor/issues/4030

chore: clean up npx cap add hints

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/Array+Capacitor.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPPlugin.h
ios/Capacitor/Capacitor/CAPPlugin.m
ios/Capacitor/Capacitor/CAPPluginCall.h
ios/Capacitor/Capacitor/CAPPluginCall.m
ios/Capacitor/Capacitor/CAPPluginCall.swift
ios/Capacitor/Capacitor/CapacitorBridge.swift
ios/Capacitor/Capacitor/JS.swift
ios/Capacitor/Capacitor/JSTypes.swift
ios/Capacitor/Capacitor/PluginCallResult.swift
ios/Capacitor/CapacitorTests/BridgedTypesTests.swift

Currently, `WKWebView` will automatically translate JavaScript `Date` objects to NSDate/Date objects when sending data over the bridge from JavaScript -> Native. While this might be helpful it is potentially unexpected, and it is inconsistent with Android where the `Dates` are turned into strings. Dates are not handled at all when sending Native -> JavaScript and including a Date in the result dictionary will cause an exception to be thrown during serialization.
So, this branch does 3 things related to Dates and returning the result of a plugin call. 
1. It serializes Dates in plugin calls during type coercion. This operation is **not** performed for Cordova plugins to preserve backwards compatibility. In addition, a plugin can opt-out of the new behavior by setting its …

feat(iOS): Add automatic Date serialization to bridge communication

---

cli/package.json

[parseStringPromise was added in xml2js 0.4.20](https://github.com/Leonidas-from-XIV/node-xml2js/commit/c7597111d758f8850fc40810a9fd4ef58d922052), so bumping the minimum version should resolve the issue for people with old cached installations.
alternative to https://github.com/ionic-team/capacitor/pull/4224
fixes https://github.com/ionic-team/capacitor/issues/4223

fix(cli): init failure if config.xml is present

---

ios/Capacitor/Capacitor/CAPBridgeProtocol.swift
ios/Capacitor/Capacitor/CapacitorBridge.swift

This branch exposes the previously internal functionality of `getPlugin` to the `public` scope by adding it to the bridge protocol. Since backwards compatibility is not a concern, it has been renamed to be more idiomatic.
Closes https://github.com/ionic-team/capacitor/issues/4174

feat(iOS): Expose plugin accessor on the bridge

---

ios/Capacitor/Capacitor/CAPBridgeProtocol.swift
ios/Capacitor/Capacitor/CAPPlugin.m
ios/Capacitor/Capacitor/CAPPluginCall.h
ios/Capacitor/Capacitor/CAPPluginCall.m
ios/Capacitor/Capacitor/CapacitorBridge.swift

This branch revisits and updates how plugin calls should be saved to clarify usage and better align the API between platforms.
- Deprecated `CAPPluginCall`'s `save` method and `isSaved` property and replaced with `keepAlive` to make the implications of the flag clearer.
- Exposed `saveCall` on the bridge and renamed related methods to be more idiomatic and consistent.
Closes https://github.com/ionic-team/capacitor/issues/4087
Companion to https://github.com/ionic-team/capacitor/pull/4254
Documented in https://github.com/ionic-team/capacitor-site/pull/238

feat(iOS): Unifying saving plugin calls

---

ios/Capacitor/Capacitor/CAPInstanceDescriptor.h

This branch adds inline documentation for the assorted`CAPInstanceDescriptor` properties.

documentation(iOS): Annotating CAPInstanceDescriptor

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java

A bug was observed (resolves #4277) where if permission was requested and the callback contained another permission/activity launch with a result, the app would crash claiming the savedCall was null.
What was happening was the call was originally saved for the first permission request, then during the callback the call would save again for the following activity result. The initial permission request would then try to cleanup after the callback was called and remove the saved call that was still being used by the waiting callback, resulting in it being null when the second callback returned. 
Fix: I moved the cleanup of the savedCall before the callback is triggered so that if the same PluginCall is saved again, it won't be accidentally removed.

fix(android): calls re-saved during permission/activity result callbacks were being released

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/CAPBridgedJSTypes.h
ios/Capacitor/Capacitor/CAPBridgedJSTypes.m
ios/Capacitor/Capacitor/CAPPlugin.h
ios/Capacitor/Capacitor/CAPPlugin.m
ios/Capacitor/CapacitorTests/PluginCallAccessorTests.m

This branch revisits the Obj-C versions of the CAPPluginCall convenience accessors, deprecates the redundant methods on CAPPlugin, adds test coverage, and fixes a bug with dates.
- Adds a `getNumber` method for NSNumber values.
- Switches the redundant `CAPPlugin` accessors to use the call's implementation.
- Marks the redundant `CAPPlugin` accessors as deprecated.
- Fixes the incorrect handling of NSDate objects in `getDate`.
- Adds unit tests to verify behavior.

feat(iOS): Obj-C convenience accessors on CAPPluginCall

---

cli/test/util.ts

The sample app has a dependency to "latest" of a plugin that doesn't exist, that wasn't a problem on npm 6 since we first install the plugin from a local folder, but on npm 7 it tries to get it from npm after installing the local version for some reason.
This PR changes "latest" with the local file path of the generated plugin.

fix(cli): Make tests work on npm 7

---

android/capacitor/src/main/java/com/getcapacitor/MessageHandler.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java

Capacitor calls are being saved when an intent is being launched and then released after the intent returns a result, but before the plugin returns the result, and in cases where there are multiple intents launched by the same plugin call it ends up creating null pointer exceptions in some cases where the call was released sooner than expected and needed later.
This PR removes the early releases of the calls and put it where the call actually rejects or resolves to the JS side.
closes https://github.com/ionic-team/capacitor/issues/4307

fix(android): Release the call after reject/resolve

---

package.json
swiftlint.config.js

`autocorrect` was renamed to `--fix`
`includes`/`excluded` require the full path, that can be accomplished by appending `${PWD}/` to the paths.

chore(ci): Update swiftlint config/commands for latest version

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

`cordova-plugin-screen-orientation` sets the screen orientation of the view controller but when `CAPBridgeViewController` was made public the `@objc` was removed.
Since `cordova-plugin-screen-orientation` is an Objective-C plugin it can't set the value anymore, so putting the `@objc` back fixes the problems.
closes https://github.com/ionic-team/capacitor/issues/4357

fix(ios): cordova-plugin-screen-orientation not working

---

ios/Capacitor/Capacitor/CAPBridgeProtocol.swift
ios/Capacitor/Capacitor/CapacitorBridge.swift

We no longer support iOS 11, so all those checks are not needed anymore

chore: Remove iOS 12 available checks

---

cli/src/common.ts

If the device doesn't have an id it fails to run, so filter out the devices without id from the run list
closes https://github.com/ionic-team/capacitor/issues/4396

fix(cli): filter targets without id from run device list

---

ios/Capacitor/Capacitor/WebViewDelegationHandler.swift

According to Apple's HIG, cancel button should always be on the left, but we put it in the right.

fix(ios): put cancel button of confirm/prompt on the left

---

cli/bin/capacitor

Our node version check doesn't allow prerelease versions, by adding `includePrerelease` option it will
closes https://github.com/ionic-team/capacitor/issues/4466

fix(cli): Allow prereleases on node version check

---

ios/Capacitor/Capacitor/CapacitorBridge.swift

Cordova fires pause and resume events, but if there are no cordova plugins installed, cordova doesn't get initialized, so the events are not fired.
This PR fires pause/resume when there are no cordova plugins installed for compatibility
closes https://github.com/ionic-team/capacitor/issues/4456

fix(ios): fire resume/pause events if no cordova plugins installed

---

core/src/runtime.ts
core/src/tests/legacy.spec.ts

Instead of always using the native listener on the native platforms, check if the native platform has a native implementation for the plugin (if pluginHeader is defined), and if not, use the web listener.
closes https://github.com/ionic-team/capacitor/issues/4331

fix(core): Use web listener if there is no native implementation

---

core/src/runtime.ts

On plugins that mix native and web implementations, current implementation causes an infinite loop because it always tries to use the web implementation before the native implementation, so when it reaches `Plugins.PluginName`, it tries to call the native code, but the proxy returns the web code, which tries to call the native code again and causes the infinite loop.
By changing the order, it will use the native code if available, and if not, use the web implementation.
closes https://github.com/ionic-team/capacitor/issues/4492

fix(core): Call native implementation before web implementation

---

android/capacitor/src/main/java/com/getcapacitor/JSExport.java
ios/Capacitor/Capacitor/JSExport.swift

revert the native code that generated the Capacitor.Plugins object that was removed on https://github.com/ionic-team/capacitor/pull/4128, but keeping the pluginHeaders generation too

fix: generate Capacitor.Plugins object

---

core/native-bridge.ts
core/src/definitions-internal.ts
core/src/platforms.ts
core/src/runtime.ts

Merging in #4255 seemed to make tests and types not work anymore even though they worked fine on their own individual branch...This PR makes some changes such as
- Making the `CapacitorPlatforms` optional like all of the other types on `WindowCapacitor`
- optional chaining to allow web platform to default correctly to the bridge functions if no platform was initialized (mostly for tests)

fix(bridge): Fix type errors with new Platforms API

---

core/native-bridge.ts

Lint fixes for #4506 (need to verify workflows)

chore(lint): fix linting issues on recent safeStringify PR

---

ios/Capacitor/Capacitor/CapacitorBridge.swift

According to the [saving calls docs](https://capacitorjs.com/docs/v3/core-apis/saving-calls) if you save a call you have to release it, but at the moment it's being released automatically, which prevents the saveCall from working. (can be reproduced on https://github.com/ionic-team/capacitor-plugins/pull/374)
closes https://github.com/ionic-team/capacitor/issues/4531

fix(ios): Don't auto release saved calls

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

ionic relies on `isPluginAvailable` being on `Capacitor` object, so adding it to the bridge
closes https://github.com/ionic-team/capacitor/issues/4588

fix: Make isPluginAvailable available on bridge

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Whenever a html file is requested (i.e, a fetch/xhr call to a .html file), the bridge is being reset, which causes problems such as the mentioned on https://github.com/ionic-team/capacitor/issues/3444, as it cleans all the saved calls, making it impossible to clean listeners and also to return values on plugins that use callbacks.
So, instead of reseting the bridge when a .html file is requested, reset it when onPageStarted is called, which is not called on xhr/fetch/iframes, etc.
closes https://github.com/ionic-team/capacitor/issues/3444

fix(android): Reset bridge on onPageStarted only

---

ios/Capacitor/Capacitor/CAPBridgeDelegate.swift

When compiling with @capacitor/ios 3.0.0-rc.3 we get the following warning. This fixes this warning.
/Users/morten/MyProject/node_modules/@capacitor/ios/Capacitor/Capacitor/CAPBridgeDelegate.swift:3:38: Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead

chore(ios): Use AnyObject instead of class for protocol inheritance

---

cli/src/util/native-run.ts

Show a better error when native-run fails

fix(cli): Better native-run error

---

cli/src/util/native-run.ts

At the moment if native-run didn't find any device or emulator, run just silently fail.
This PR changes the behavior to throw the errors (can be more than one) that native-run provided.

fix(cli): Throw error if native-run didn't find targets

---

cli/src/cordova.ts

If there is a config.xml present, capacitor CLI will prompt the user if they want to migrate preferences from config.xml to capacitor config file.
In non interactive environments (such as when run inside ionic CLI) it will hang as it can't choose an answer.
So, in cases is a non interactive environment, migrate the preferences without asking.
closes https://github.com/ionic-team/capacitor/issues/4678

fix(cli): Don't prompt cordova preferences if non interactive

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

When the events are initialized cordova is still undefined as it gets injected later, so we are setting the undefined to a const, then, when you try to fire a cordova event, the cordova const is undefined and will fail to fire.
By moving the cordova const initialization to when it's going to be used it will contain the real `window.cordova` and won't be undefined.
Also moved the window.document just in case.
closes https://github.com/ionic-team/capacitor/issues/4713

fix(core): cordova events not firing

---

ios/Capacitor/Capacitor/CapacitorBridge.swift

cordova uses `willEnterForegroundNotification` instead of `didBecomeActiveNotification` for resume event and `didEnterBackgroundNotification` instead of `willResignActiveNotification` for pause event, so this should work the same way

fix(ios): Use proper native events for cordova events

---

cli/src/ios/common.ts
cli/src/ios/update.ts
cli/src/tasks/add.ts

If sync is run on windows or linux, just skip the pod install step instead of erroring
closes https://github.com/ionic-team/capacitor/issues/4717

fix(cli): Don't error on ios sync on non macOS

---

android/capacitor/src/main/java/com/getcapacitor/JSInjector.java

According to the [docs](https://capacitorjs.com/docs/basics/utilities#convertfilesrc) `Capacitor.convertFileSrc` should return an URL starting with `http://localhost` on android, but instead this part is missing and something like `/_capacitor_file_/path/to/device/file` is returned. `convertFileSrc` gets the host part from `webviewServerUrl`, which is set when native-bridge is loaded:
https://github.com/ionic-team/capacitor/blob/ca4e3b62dba6a40e593a1404ba2fe2b416a4ac14/core/native-bridge.ts#L356-L357
Because of the injection order, `win.WEBVIEW_SERVER_URL` has not been set yet when this line is executed. This PR fixes that by injecting the part that sets `WEBVIEW_SERVER_URL` before native-bridge.

fix(android): Set WEBVIEW_SERVER_URL before injecting native-bridge

---

cli/src/util/subprocess.ts

I was looking into an issue that provided this sample app https://github.com/RaphaelWoude/ionic-capacitor-example
Running `npx cap run android` on it was showing a strange error message.
It was caused because both `e.output` and `e.code` were undefined.
It's probably a bug on `@ionic/utils-subprocess` not properly building the `SubprocessError` for the EACCES error, but since I know nothing about that package and don't want to break things, I've patched our handler to throw the error message if present or an unknown error.

fix(cli): correctly show EACCES error on run

---

cli/src/common.ts
cli/src/tasks/add.ts
cli/src/tasks/copy.ts
cli/src/tasks/open.ts
cli/src/tasks/run.ts
cli/src/tasks/sync.ts
cli/src/tasks/update.ts

As my other PR #4536 is still pending, this would be another way for me to make my android Build work in Appflow.
- The existing method `runPlatformHook` was extended with a new Environment Variable: **CAPACITOR_PLATFORM_NAME**
- The same Method is used to trigger the following hooks from `package.json:`
- `capacitor:sync:before`
- `capacitor:sync:after`
- `capacitor:copy:before`
- `capacitor:copy:after`
- `capacitor:update:before`
- `capacitor:update:after`
closes #3593

feat(cli): Add hooks to call into npm scripts when capacitor commands run

---

cli/src/common.ts

the hook check was failing if there was no scripts field in package.json

fix(cli): Don't error if there are no scripts

---

cli/test/util.ts

use the file path of the fake plugin to install so tests pass on npm 7
tests should be fixed once https://github.com/ionic-team/capacitor/pull/4774 gets merged

chore: fix tests on npm 7

---

cli/src/android/run.ts
cli/src/config.ts
cli/src/declarations.ts
cli/src/definitions.ts

closes https://github.com/ionic-team/capacitor/issues/4740

feat(cli): allow run command to use flavors

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ExifWrapper.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ImageUtils.java
ios/Capacitor/Capacitor/Plugins/Camera.swift

Backporting android camera exif fix from Capacitor 3.x
https://github.com/ionic-team/capacitor-plugins/pull/480

fix(camera): properly append exif data into the returned images

---

scripts/sync-peer-dependencies.mjs

Having ~ in the peer dependencies is making it hard to update on npm 7, make the script that set the version change to ^

chore: Make sync peer deps script use ^

---

cli/src/config.ts
cli/src/index.ts

At the moment, if the user has hideLogs configuration option, the CLI will show a warning on every command the CLI runs.
For some commands (version, config, run) it's a problem because the output is used by other tooling (like Ionic CLI) and can't be parsed correctly.
This moves the warning from all commands to just a set of them (add, update, copy, sync, doctor, list)

fix(cli): Don't warn about hideLogs on some commands

---

core/src/runtime.ts

In Capacitor 2, calling `JSON.stringify(Plugin)` would return an empty object. In Capacitor 3 it tries to call a native toJSON method, which doesn't exist, and throws an error.
This PR handles the toJSON call in core to make it return an empty object as it used to.
closes https://github.com/ionic-team/capacitor/issues/4814
closes https://github.com/ionic-team/capacitor/issues/4820

fix(core): handle toJSON() in plugin objects

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

In Capacitor 2 the theme and contentView were set in onCreate (because the init method was called on onCreate), now in Capacitor 3 are set on onStart (because init is deprecated), which seems to be too late for the themes to properly work.
closes https://github.com/ionic-team/capacitor/issues/4787

fix(android): Set theme an content view on onCreate

---

core/native-bridge.ts

fix(core): Modify safeStringify to allow multiple null values

---

android/capacitor/src/main/java/com/getcapacitor/JSExport.java

Capacitor injects cordova plugin files into a script tag in the index.html, but if the plugin provides a .map file, such as sentry plugin, the map is not proper js and breaks the injection, making Capacitor and the plugins to not work.
closes https://github.com/ionic-team/capacitor/issues/4891

fix(android): Don't inject map files into capacitor script

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/annotation/CapacitorPlugin.java
core/native-bridge.ts

These proposed changes will allow support for using request codes in the `@CapacitorPlugin` annotation while also calling the `handleOnActivityResult` method in the Plugin as in previous versions of Capacitor.

(feat) android: adds support in CapacitorPlugin for handleOnActivityResult

---

cli/src/ios/update.ts

Some Cordova plugins are using pod dependencies directly from GitHub, as they don't have a version we just add a dependency in the podspec, but if it's not published in CocoaPods repo Capacitor won't find it.
This PR will read pod entries in plugin.xml and if they are git references it will put them in the users Podfile with the other Capacitor dependencies so it can be found.
closes https://github.com/ionic-team/capacitor/issues/4867

fix(cli): Put cordova git pod dependencies in Podfile

---

cli/src/common.ts
cli/src/tasks/add.ts

Track `@ionic-enterprise` platforms in the CLI. I _think_ this is all that will be necessary in this repo to integrate with the win stuff now that it's all in a separate platform.

chore(cli): Register enterprise-specific platforms

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java

When using activity result launchers, the call is not being saved, so if the app dies, the `appRestoredResult` event won't be fired
Also `getSavedCall()` is deprecated and not returning the proper value, switched to `bridge.getSavedCall(lastPluginCallId);`
closes https://github.com/ionic-team/capacitor/issues/5003

fix(android): save activity result launcher calls

---

cli/src/cordova.ts

see https://github.com/ionic-team/capacitor/issues/4949

fix: Add SalesforceMobileSDK-CordovaPlugin to iOS incompatible list

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Instead of overwriting console object, hook to it to display the native logs

fix(ios): show correct line number on console logs

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/CAPBridgeViewController+CDVScreenOrientationDelegate.h
ios/Capacitor/Capacitor/CAPBridgeViewController+CDVScreenOrientationDelegate.m

Some Cordova plugins, such as cordova-plugin-inappbrowser rely on CDVScreenOrientationDelegate to determine its supported orientations.
CAPBridgeViewController.swift can't conform CDVScreenOrientationDelegate directly because the CDVScreenOrientationDelegate protocol Objective-C names conflict with UIViewController names in Swift.
This PR adds an Objective-C category for CAPBridgeViewController that allows to conform CDVScreenOrientationDelegate, and since it's Objective-C it doesn't conflict.

fix(ios): Add CDVScreenOrientationDelegate protocol on CAPBridgeViewController

---

cli/src/tasks/add.ts

telemetry hangs on add command because it prompts while sync is being run and the message get lost in the sync logs, await for sync so telemetry is prompt after sync finish

fix(cli): await sync on add to avoid telemetry hang

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

`safeStringify` function was added to fix https://github.com/ionic-team/capacitor/issues/4506, but didn't do it properly as there is a [follow up PR](https://github.com/ionic-team/capacitor/pull/4573) that is still unmerged. And also causes a crash on iOS apps if you try to log an object with circular references, see [this issue](https://github.com/ionic-team/capacitor/issues/5178) for more details.
Since [we changed](https://github.com/ionic-team/capacitor/pull/5073) the way the console overwrite works on iOS, looks like the `safeStringify` is not even needed, so this PR removes it. After merged, circular objects that error on `JSON.stringify()` will go back to printing `[object Object]` as they did before the `safeStringify` PR was merged instead of crashing the app.
closes …

fix(core): avoid crash on logging circular objects

---

cli/src/config.ts

If iOS platform is not added `npx cap config` throws an error, while if android platform is not added it just returns the default values as if it existed.
This PR prevents `npx cap config` from throwing an error if iOS platform is not added, will return the default values as Android does.

fix(cli): Make config don't error if iOS is missing

---

cli/src/android/add.ts
cli/src/tasks/add.ts

At the moment we are running gradle sync from the root folder, which no longer works on Gradle 7
Change the command to run from android folder
And as it needs some generated gradle files to exist, that are generated by capacitor sync, move the gradle sync after capacitor sync.
closes https://github.com/ionic-team/capacitor/issues/5229

fix(cli): sync gradle from android folder

---

cli/src/cordova.ts

Most plugins that require to be a static framework have `use-frameworks` in the pods definition, so read it and if present automatically add the plugin to the static list.
The PR removes the old known plugins that have `use-frameworks` in plugin.xml from the list and leaves the ones that don't have it but need to be static.

fix(cli): Add plugin to static list if pod has use-frameworks

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

On Android 12 accepting only ACCESS_COARSE_LOCATION permission should be considered as granted, at the moment we consider it rejected as ACCESS_FINE_LOCATION is rejected.
Sadly web geolocation still doesn't get the coordinates after this change if the user chooses the "Approximate" option, it times out instead of getting a permission error message.
I've [reported it to chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1269362).

fix(android): Allow web geolocation if only COARSE_LOCATION is granted

---

cli/src/cordova.ts

version 3 is automatically put in the static list because it uses the pods tag with `use-frameworks="true"`, but version 2 is not, so add it to the hardcoded list.

fix(cli): Add onesignal-cordova-plugin to the static list again

---

cli/src/android/run.ts
cli/src/config.ts
cli/src/definitions.ts

Solves request: https://github.com/ionic-team/capacitor/issues/5252
Live reload should now work with any `productFlavor`.

fix(android): restrict android run command to configured flavour

---

ios/Capacitor/Capacitor/WebViewDelegationHandler.swift

related to https://github.com/ionic-team/capacitor-plugins/issues/713
If a js alert is used while the capacitor view controller is presenting another view (in 713 it's a native alert), the app crash because the js alert is not being presented
This PR changes the behavior to detect if another view controller is being presented and present the js alert on top of that view controller instead of in the capacitor view controller.
Not sure if this could be considered a breaking change since at the moment the js alert is not being presented. An alternative would be to not try to present the js alert if capacitor view controller is presenting another view controller, that should also avoid the crash.

fix(ios): Present js alert on top of the presented VC

---

.github/workflows/publish-android.yml

#5266 Update the GitHub action setup-java from adopt to zulu of the OpenJDK.
The AdoptOpenJDK has been discontinued since July 2021 (https://adoptopenjdk.net). Switching the distribution to Azul Zulu. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. 
Please see more details at Foojay.io:
https://foojay.io/today/github-actions-with-java-part-2/

#5266 Using TCK Tested JDK builds of OpenJDK

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

this PR fixes this (closed) issue: https://github.com/ionic-team/capacitor-plugins/issues/658
closes: https://github.com/ionic-team/capacitor/issues/5290
Without the fix, capacitor calls the camera plugin's `restoreState()` method even though `bundleData` is `null`

fix(android): Prevent crash in restoreInstanceState if bundleData is null

---

cli/src/android/common.ts
cli/src/ios/common.ts

on iOS `&`, `<` and `>` can't be used on the app name unless escaped
on Android `&`, `<`, `'` and `"`can't be used on the app name unless escaped
we were already handling `'` on Android, but this PR handles the rest of invalid characters for both iOS and Android
closes https://github.com/ionic-team/capacitor/issues/5322

fix(cli): Escape appName from invalid characters on add

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

If the app is killed while using an input file is being used, when the user chooses a file the app crashes because the `activityListener` is null as the app was killed.
The file will be lost, but the app won't crash.
Can be tested by setting the "Don't keep activities" option in the developer menu.
closes https://github.com/ionic-team/capacitor/issues/5284

fix(android): Prevent crash if activity killed on input file

---

ios/Capacitor/Capacitor/WebViewDelegationHandler.swift

Delegates media capture permissions to the app and remembers the user's decision for iOS15.
[https://developer.apple.com/documentation/webkit/wkuidelegate/3763087-webview#discussion](https://developer.apple.com/documentation/webkit/wkuidelegate/3763087-webview#discussion)
Thanks and credits to @7freaks-otte who found the solution. :)
[https://forum.ionicframework.com/t/prevent-for-reprompting-webrtc-webview-permissions-ios15/215240/2?u=samydoesit](https://forum.ionicframework.com/t/prevent-for-reprompting-webrtc-webview-permissions-ios15/215240/2?u=samydoesit)
You can test these changes using my getusermedia demo case when build on Xcode13 -> https://github.com/samydoesit/capacitor-getusermedia-test

feat(ios): Add new iOS15 media capture permission delegate

---

ios/Capacitor/Capacitor/WebViewDelegationHandler.swift

Like https://github.com/ionic-team/capacitor/pull/5196 but for Motion permission.
Requesting motion permission have multiple issues (wrong titles, wrong origin, doesn't remember it was granted and keeps asking every time), with this delegate present and Motion usage description the WKWebView will not present the motion permission prompt, instead will just grant the permission directly.

feat(ios): Add new iOS 15 Motion permission delegate

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

we were handing it for when the accept has multiple values with . but not a single value with . 
there is a bug on the intent android creates that puts an invalid type when the accept has a . on it, it's really an android bug, but we workaround it by setting the type to one of the validated ones.
closes https://github.com/ionic-team/capacitor/issues/5358

fix(android): prevent input file crash if accept has .

---

capacitor-cordova-android-plugins/build.gradle

cordova-android 10 uses appcompat as activity, so if a Capacitor app uses cordova-android 10 and any plugin calls `cordova.getActivity()` or similar method it fails to build because it nows returns an AppCompatActivity instead of a regular Activity.
Adding the appcompat dependency to the plugins module fixes the issue.

fix(android): Add appcompat to capacitor-cordova-android-plugins module

---

ios-template/App/App.xcodeproj/project.pbxproj
ios-template/App/App/Info.plist

Add `CURRENT_PROJECT_VERSION` and `MARKETING_VERSION` variables to the ios-template project as Xcode 11+ do when you change the values from the "General" screen

fix(cli): Use CURRENT_PROJECT_VERSION variable on ios template

---

cli/src/android/update.ts

if the cordova plugin doesn't have any source files (i.e. es6-promise-plugin)

fix(cli): avoid srcFiles is not iterable on kotlinNeededCheck

---

ios/Capacitor/Capacitor/CAPWebView.swift
ios/Capacitor/Capacitor/JSTypes.swift

Using frame-based layout with `CAPWebView` and it's descendants was causing issues with Portals due to the fact it was unable to resize or adjust it's origin and size when a parent view's origin or size changed.
Added extension method `getValue(_:)` method and deprecated `getAny(_:)` to help constrain the possible values able to be represented by `JSValueContainer` by consumers of Portals.

fix(ios): Use autolayout for CAPWebView and JSValueContainer Update

---

.github/workflows/ci.yml
.github/workflows/lint-podspec.yml
.github/workflows/publish-ios.yml
ios/Capacitor.podspec

As it stands today, any change made to the `portals-dev` branch will be pulled by anyone who does a fresh `pod install`. This change will make each version a bit more deterministic with each version being tied to a specific commit hash instead of always referring to the tip of the `portals-dev` branch.

fix(ios): Specify specific portals-dev commit for Capacitor.podspec

---

android-template/variables.gradle
android/capacitor/build.gradle
capacitor-cordova-android-plugins/build.gradle
cli/src/config.ts

chore(android): bump core min sdk

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/java/com/getcapacitor/RouteProcessor.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Adds the ability to pass a route processing interface to the Bridge that intercepts routes and can change them.

feat(android): Add overridable routing for WebViewLocalServer

---

ios/Capacitor/Capacitor/Router.swift
ios/Capacitor/CapacitorTests/RouterTests.swift

fix(ios): Use `URL(fileURLWithPath:)` instead of `URL(string:)`

---

ios-template/App/App/AppDelegate.swift

touchesBegan was there for iOS <= 12, removing since we no longer support those versions
closes https://github.com/ionic-team/capacitor/issues/5650

chore(ios-template): Remove unused touchesBegan method

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

Remove the init and other related deprecated methods from BridgeActivity and move the bridge initialization code to onCreate instead of onStart

chore(android): Remove deprecated init method

---

android/capacitor/src/main/java/com/getcapacitor/ProcessedRoute.java
android/capacitor/src/main/java/com/getcapacitor/RouteProcessor.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
cli/src/declarations.ts

This update to the recently introduced Route Processor feature allows the interface to also specify whether the returned file is file or an asset. This is helpful when discerning whether a bundled asset in the apk or web assets on disk should be used, for example in Live Updates in the Portals for Capacitor use case. This is a breaking change with little-to-no impact currently due to the development state of Portals for Capacitor.
Example use:
```java
private RouteProcessor implementRouteProcessor() {
return (basePath, path) -> {
ProcessedRoute processedRoute = new ProcessedRoute();
String shellAppName = portalsConfig.getShellApp().getName();
LiveUpdateConfig shellLiveUpdateConfig = portalsConfig.getShellApp().getLiveUpdateConfig();
File shellLiveUpdatePath = null;
if …
```

feat(android): update support for Portals for Capacitor to include Live Updates

---

android/capacitor/src/main/java/com/getcapacitor/AppUUID.java
ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/AppUUID.swift

Adds support for generating and accessing a UUID for a specific installation of an app from the core library. 
> Note: This UUID does not persist across app installations, so if the app is uninstalled the UUID is lost.
Plugins can leverage this by using the AppUUID class in both iOS and Android:
Android Plugin:
```java
// Get or Create And Get, the UUID
String uuid = AppUUID.getAppUUID(this.getActivity());
//Regenerate the UUID
AppUUID.regenerateAppUUID(this.getActivity());
```
iOS Plugin:
```swift
// Get or Create And Get, the UUID
let uuid = AppUUID.getAppUUID()
//Regenerate the UUID
AppUUID.regenerateAppUUID();
```

feat(iOS, Android): add AppUUID Lib for plugins

---

android-template/app/build.gradle

We have the dependency inside capacitor/android, but for some users it's not picking it correctly.
Since we use CoordinatorLayout in the default template we should include the dependency instead of relying on it being declared in capacitor/android
closes https://github.com/ionic-team/capacitor/issues/5437

chore(android-template): Add coordinatorlayout dependency

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj

Frameworks should only be embedded in application targets. Embedding a framework in a framework will result in an iOS application upload to be rejected by Apple.

fix(ios): Remove Cordova as an embedded framework

---

android-template/.gitignore
ios-template/.gitignore

I've also added the config.xml and for android the capacitor.plugins.json file since those are also auto generated by copy/sync commands.
closes https://github.com/ionic-team/capacitor/issues/4626

chore(cli): Add config files to native templates gitignore

---

cli/src/android/update.ts

updates default kotlin version to 1.7.0 and core-ktx to 1.8.0
also update the kotlin_version variable setting logic to be done in the buildscript so we can always use the `$kotlin_version` variable in the dependency by declaring a new `ext.kotlin_version` if it doesn't exist

chore(cli): Update cordova plugins default kotlin versions

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/CAPWebView.swift
ios/Capacitor/Capacitor/JSTypes.swift

cherry pick CapWebView into 3.x branch

feat: Add CapWebView  (#5715)

---

.github/workflows/publish-ios.yml
ios/Capacitor.podspec

After [CapWebView is added to 3.x branch](https://github.com/ionic-team/capacitor/pull/5730), native-publish will need to pick the code from there instead of from portals-dev

chore(ci): Change script to publish from 3.x branch

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
cli/src/declarations.ts

Adds a `android.minWebviewVersion` config option for allowing developers to set the minimum web view version for their app.

feat(android): Add android.minWebviewVersion configuration option

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
core/src/util.ts
ios/Capacitor/Capacitor/PluginCallResult.swift

This PR adds an optional data object to be passed to `call.reject()` in order to be consistent with the method signatures on iOS.
closes https://github.com/ionic-team/capacitor/issues/5336

feat(android): Add Optional Data Param for Error Object

---

ios/Capacitor/Capacitor/CAPWebView.swift

Since CAPWebView was in portals-dev brach, we didn't remove the available check with the others

chore(ios): Remove unused available check

---

ios/Capacitor/Capacitor/CAPPluginCall.swift

If no data is passed, error is always returning an empty object, while in Android it doesn't return data.
This set the data to nil as default and makes data optional.

fix(ios): error data is optional

---

android-template/app/build.gradle
android-template/app/src/main/res/values/styles.xml
android-template/variables.gradle

We are making Android 12 splash API the default, so the template needs to be updated to use it out of the box
splash API PR https://github.com/ionic-team/capacitor-plugins/pull/1011

feat(android-template): Use Android 12 splash API

---

android-template/variables.gradle

In https://github.com/ionic-team/capacitor/pull/5427 a new androidxWebkitVersion variable was used, so should be included in the variables.gradle with the default value.

chore(android-template): Add androidxWebkitVersion variable

---

ios-template/App/Podfile
ios/scripts/pods_helpers.rb

feat(iOS): post install script for deployment target

---

cli/src/tasks/migrate.ts

New variables should be put at the end of the file instead of at the beginning, the beginning should be "reserved" for SDK related variables as those are more important.

chore(cli): Put new variables at the end

---

cli/src/tasks/migrate.ts

docs are now published, so use the official url instead of "next" one

chore(cli): Update plugins breaking changes link

---

cli/src/tasks/migrate.ts

for users that already ran the migrator with a bug on the splash theme changes, this revert those wrong changes.

fix(cli): Revert some splash migration errors

---

cli/src/tasks/migrate.ts

The migrator is missing[ the change ](https://capacitorjs.com/docs/updating/4-0#optional-use-a-daynight-theme)of the app theme to DayNight 
I've put the code in the same place the splash theme is changed to avoid reading the file again

chore(cli): Replace Dark theme with DayNight theme

---

cli/src/tasks/migrate.ts

In android-template we use gradle 7.4.2-all, while the migrator uses 7.4.2-bin.
Also `https\://services.gradle.org/distributions/gradle-7.4.2-all.zip` is being written as `https://services.gradle.org/distributions/gradle-7.4.2-all.zip`, so add an extra \ so it gets written as `https\://services.gradle.org/distributions/gradle-7.4.2-all.zip` to match the template (the url still works, so not a big issue, but for consistency.

chore(cli): make migrator use gradle 7.4.2-all

---

package.json

core tests are failing because of a minipass problem on the root @types/tar package.
Update it to latest to prevent the error.

fix: update @types/tar to prevent core build failure

---

ios/Capacitor/Capacitor/CAPWebView.swift

Xcode 14 shows this warning:
> Non-'@objc' instance method in extensions cannot be overridden; use 'public' instead
And proposes to change to public, so I've done that
Closes https://github.com/ionic-team/capacitor/issues/5819

fix(ios): Prevent Xcode 14 warning on CAPWebView

---

cli/src/tasks/migrate.ts

In Capacitor 2, some variables had a double space between `=` and `'`, which is making the migrator to put the variables as numbers instead of as strings.
This PR removes those double spaces before doing the replacement.

fix(cli): remove double space in cap 2 variables file

---

cli/src/tasks/migrate.ts

If the app was already using capacitor 4 beta and already migrated to using preferences plugin instead of storage plugin, the migrator won't update the preferences dependency to ^4.0.0, add it to the list so it gets updated.

fix(cli): Also update preferences plugin if present

---

cli/src/index.ts
cli/src/tasks/add.ts
cli/src/tasks/run.ts
cli/src/tasks/sourcemaps.ts
cli/src/tasks/sync.ts

Adds an option to the `sync` command , `--inline`, which will, after syncing, inline all JS source maps for easier debugging on mobile devices.

feat(cli): Option to inline JS source maps during sync

---

cli/src/tasks/migrate.ts

I've seen several users that were using custom plugins that no longer work because registerPlugin has to be called before super.onCreate on Capacitor 4.
So this PR makes the migrator move the registerPlugin calls before super.onCreate.

fix(cli): Migrator put registerPlugin before super.onCreate

---

cli/src/tasks/migrate.ts

Currently the "cap migrate" command will crash with the error "Failed to migrate: TypeError: Cannot convert undefined or null to object" if you run it in project that has a package.json file without a devDependencies property. This PR fixes this issue.

fix(cli): prevent error on migrate when devDependencies is missing

---

cli/src/tasks/migrate.ts

Capacitor 2 apps had all those plugin variables defined and it's causing issues for users that update the plugins but have the old variable version defined (specially playServicesLocationVersion variable since we use constants that weren't available before that version).

fix(cli): make migrator also update plugin variables

---

cli/src/ios/common.ts

If CocoaPods is not installed we link the official CocoaPods install guide that uses gem install, but gem install has some problems on M1 macs, so better use a link to our own page that explains how to install with Homebrew (and also without it)

chore(cli): Change CocoaPods install link

---

LICENSE
android/LICENSE
cli/LICENSE
core/LICENSE
ios/LICENSE

Github doesn't automatically detects the MIT license because of formatting.
closes https://github.com/ionic-team/capacitor/issues/5884

chore: format license files properly

---

ios/Capacitor/Capacitor/CAPBridgeProtocol.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CapacitorBridge.swift

Backports `setServerBasePath(_:)` to 3.x

feat(ios): Add `setServerBasePath(_:)` to CAPBridgeProtocol (#5860)

---

cli/src/declarations.ts
cli/src/tasks/copy.ts

Copies the secure live updates key file specified in the config when using Secure Live Updates in the Capacitor Live Updates plugin.

feat(cli): copy signature when using secure live updates

---

cli/src/tasks/migrate.ts

closes https://github.com/ionic-team/capacitor/issues/5897

fix(cli): show error if npm install on migration failed

---

cli/src/tasks/migrate.ts

run gradlew wrapper command to update gradle wrapper files
created a new constant to use the same gradle version in different places so it's easier to update in the future.

fix(cli): Make migrator update gradle wrapper files

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

fix(core): Exception object was not set on Cap

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

This sets the WebViewClient on the WebView too as if setWebViewClient is being called after the app initialization it had no effect setting it only on the bridge.
closes https://github.com/ionic-team/capacitor/issues/5419

fix(android): set WebViewClient on the WebView

---

cli/src/declarations.ts
cli/src/tasks/copy.ts

Updates the CLI to add the ability to add a liveUpdatesKey to the Portals for Capacitor config which enables support for Secure Live Updates in the Portals for Capacitor plugin.

feat(cli): supports secure live updates in Portals for Capacitor config

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/ServerPath.java

Adds a ServerPath object and mechanics for Portals and live updates to load directly instead of after the webview has already loaded. Fixes issue with observable flash or Page Not Found error before content loading.
Will port this to 4.x when upgrading Portals for Cap 4 support.
Example use
```kotlin
var bridgeBuilder = Bridge.Builder(this)
.setInstanceState(savedInstanceState)
.setPlugins(initialPlugins)
.setConfig(config)
.addWebViewListeners(webViewListeners);
if (portal?.liveUpdateConfig != null) {
liveUpdateFiles = LiveUpdateManager.getLatestAppDirectory(requireContext(), portal?.liveUpdateConfig?.appId!!)
bridgeBuilder = if (liveUpdateFiles != null) {
bridgeBuilder.setServerPath(ServerPath(ServerPath.PathType.BASE_PATH, liveUpdateFiles!!.path))
} else { …
```

fix(android): added ServerPath object and building options for setting initial load from portals

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/ServerPath.java

4.x port of merged 3.x code https://github.com/ionic-team/capacitor/pull/6005
Adds a ServerPath object and mechanics for Portals and live updates to load directly instead of after the webview has already loaded. Fixes issue with observable flash or Page Not Found error before content loading.

fix(android): added ServerPath object and building options for load from portals (#6005)

---

cli/src/tasks/migrate.ts

If `super.onCreate(savedInstanceState);` line has a different padding than the hardcoded one, the migrate command will fail to remove the line and will end up with it duplicated (see https://github.com/jcesarmobile/capacitor-migration-issue/pull/2/files)
This PR calculates the padding of the `super.onCreate(savedInstanceState);` line to use it on the string replacement so it works with any padding.

fix(cli): calculate padding of super.onCreate(savedInstanceState); line

---

cli/src/tasks/migrate.ts

get the current gradle version and check if it's older than the version on the template to not downgrade user projects in case they had already upgraded gradle to 7.3.0 or newer.

fix(cli): Update gradle versions only if they are older

---

cli/src/declarations.ts
ios/Capacitor/Capacitor/CAPInstanceDescriptor.swift

`ios.handleApplicationNotifications` is not being read at the moment nor exposed on the types.
Expose it and read the value to allow to use a custom `UNUserNotificationCenter`

fix(cli/ios): Read handleApplicationNotifications configuration option

---

.github/workflows/publish-android.yml
android/capacitor/build.gradle
android/scripts/publish-module.gradle
android/scripts/publish-root.gradle
scripts/publish-android.sh

Adds native publication step for android into Capacitor v4. No separate publication branch required like in v3.
Triggering a build requires ENV variable set for `CAP_PUBLISH=true` when running the build and publish Gradle commands so that the appropriate plugins are imported with Gradle. The CI publish script will include this.
ENV variable requirement fixes a previous error in traditional Capacitor apps where the parent App project threw a Gradle sync error due to the presence of the publishing plugin in the entire project.
```A problem occurred evaluating project ':capacitor-android'.
> Failed to apply plugin 'io.github.gradle-nexus.publish-plugin'.
> Plugin must be applied to the root project but was applied to :capacitor-android
```
Removed the manual review step from Sonatype. …

chore(android): native artifact publish logic

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java

As behavior will change in Capacitor 5 to match iOS behavior

chore(android): Warn when using getArray/getObject without a default value

---

.github/workflows/ci.yml
.github/workflows/publish-ios.yml
ios/Capacitor.podspec
ios/Capacitor.podspec.patch
ios/CapacitorCordova.podspec
ios/CapacitorCordova.podspec.patch
ios/package-lock.json
scripts/native-podspec.sh

This removes the need to maintain two separate branches. Having a Capacitor.podspec and CapacitorCordova.podspec in the root of the repo would also solve this problem. I went this patchfile route to avoid any potential drift that having two separate sources of truth would eventually cause.

chore(ios): iOS pub v4

---

cli/src/framework-configs.ts

Adds vite framework detection to hopefully help with some detection issues around svelte. Older svelte projects used the public directory, but newer ones use vite as the primary bundler which has `dist` as the output directory. This should also add support for other vite-based frameworks such as solidjs.

fix(cli): add vite config to framework detection

---

android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaInterfaceImpl.java

We have the same code cordova-android has in here https://github.com/apache/cordova-android/blob/2a84d7c44ddf5eb169f34a2448915a53d0a30fcd/framework/src/org/apache/cordova/CordovaInterfaceImpl.java#L220-L223
So silence the warning for now until it gets replaced there

fix(android): Silence deprecation warning on handlePermissionResult

---

cli/src/declarations.ts

4.4.1 was never released, so the change was made in 4.5.0

docs(cli): correct since version of handleApplicationNotifications

---

cli/package.json
cli/src/cordova.ts
cli/src/util/xml.ts

This PR fixes a behaviour where the CLI will warn about missing configuration in the Plist and AndroidManifest files even when the required config of the plugins is already present.

fix(cli): warns about config that is present

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/CAPBridgeProtocol.swift
ios/Capacitor/Capacitor/CAPInstancePlugin.swift
ios/Capacitor/Capacitor/CAPPlugin+LoadInstance.swift
ios/Capacitor/Capacitor/CAPWebView.swift
ios/Capacitor/Capacitor/CapacitorBridge.swift

feat(ios): Adds support for manual registration for plugins and the ability to register instances of plugins so that plugins can be instantiated by the user instead of relying on the bridge.

feat(ios): Plugin Registration and Plugin Instance Support

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Logger.java

When a memory dump is done in a Capacitor app any Logger.verbose etc calls will appear with their payload even if the loglevel is set to None, this is because all method call parameter objects are placed on the stack and require a GC to empty. 
This particular Logger.verbose statement passes the data of the call which is likely to contain sensitive data if making say a login API request so by checking if we should log before calling the statement it ensure that call.getData() is not called and the verbose method is not called.
Note: other plugins are likely to still insert sensitive data into memory but these would be treated separately. This PR is just for Capacitor.

fix(core): Ensures PII data is not placed in memory if LogBehavior is set to none

---

.github/workflows/publish-npm-dev.yml
cli/src/cordova.ts

Dev releases to test with:
- @capacitor/android@4.6.1-dev-20221202T163618.0
- @capacitor/cli@4.6.1-dev-20221202T163618.0
- @capacitor/core@4.6.1-dev-20221202T163618.0
- @capacitor/ios@4.6.1-dev-20221202T163618.0

fix(cli): support variables in config warn checks

---

ios/Capacitor/Capacitor/Plugins/CapacitorHttp.swift
ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift

I've removed the url validation checks on `CapacitorHttp.swift` because they are also done on `HttpRequestHandler.swift`.
The fix encodes the provided url so whitespaces can be used
closes https://github.com/ionic-team/capacitor/issues/6122

fix(ios): encode whitespace in http plugin urls

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java

As far as I understand, when using `application/x-www-form-urlencoded` you send a string, so that's why the `body.toJSObject()` is crashing, because it's a string, not a JSObject.
The PR removes the whole `application/x-www-form-urlencoded` else and goes directly to the final else where it read the body as string.
If you think there might be bases where the `application/x-www-form-urlencoded` could be getting a `JSObject`, let me know and I'll change the code to catch the JSON exception and fallback to string in that case.
closes https://github.com/ionic-team/capacitor/issues/5996

fix(android): get application/x-www-form-urlencoded as string

---

ios/Capacitor/Capacitor/Plugins/CapacitorHttp.swift

fix(ios): CapacitorHttp cannot use delete method

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorHttp.java
ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift

On Android:
remove the System.out line
Return the error localized message first and then the exception name as rejection code
On iOS:
Add missing rejection on data task error
return the localized message instead of "Error" and the error domain as rejection code instead of "REQUEST" on the existing and new rejection
closes https://github.com/ionic-team/capacitor/issues/6024
closes https://github.com/ionic-team/capacitor/pull/6033

fix(ios/android): better http error handling

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Stringify the headers so the native side only gets strings as native headers can only be strings.
closes https://github.com/ionic-team/capacitor/issues/6202

fix(ios): crash when http headers contain numbers

---

android/capacitor/src/main/assets/native-bridge.js
cli/src/ios/update.ts
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

This allows for _some_ visibility into the native network requests being made. In the Chrome performance tools, this shows up in the timeline like this:
It also will log to the console with the tag provided and the total time:
```
CapacitorHttp XMLHttpRequest {timestamp at start} http://localhost:8080/delay/3: 3219.450ms
```
In Safari Dev tools, the only thing that shows up is the timestamp in the console.

chore(core): Add `console.time` and `console.timeEnd` calls to patched network requests

---

cli/src/cordova.ts

when the element to search in the AndroidManifest.xml doesn't have children it causes several problems
this PR solves them
check if the element has children and if not, add itself to the elements to search
compare not only if the children are undefined, but also if they are defined but empty as sometimes the required element is defined but empty

fix(cli): prevent error on manifest element without children

---

ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift

compare the received url with the unencoded url and only encode the url if they are the same (if they are not encoded already)
closes https://github.com/ionic-team/capacitor/issues/6230

fix(ios): Avoid double encoding on http urls

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
android/capacitor/src/main/java/com/getcapacitor/CapacitorWebView.java
android/capacitor/src/main/java/com/getcapacitor/FileUtils.java
android/capacitor/src/main/java/com/getcapacitor/JSExport.java

This PR adds the ability to create configs from a provided file path. It will be used by Portals to allow config files to be contained within specific Portal subdirs in assets and also to allow them to be contained within live update files on disk. 
This PR also fixes a bug that was found where CapacitorWebView may not read the correct config that was provided to Capacitor when used with Portals.

feat(android): add ability to create config from a custom file path

---

cli/src/tasks/copy.ts

all `extConfig` properties are read only, so typescript doesn't allow to delete `buildOptions` directly
by casting to any, we can easily remove `buildOptions` from `extConfig.android` before writing the platforms `capacitor.config.json` file
close https://github.com/ionic-team/capacitor/issues/6246

fix(cli): Remove buildOptions from platform capacitor.config.json

---

android/capacitor/src/main/java/com/getcapacitor/ProcessedRoute.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Adds an override option for the RouteProcessor to allow Portals to request a route outside of the `assetPath` location. EG: a Portal at `/assets/mywebapp/index.html` wants to load an image at `/assets/sharedimages/fish.jpg`
Example usage in Portals:
```kotlin
// If AssetMap contains this virtual route, reroute to shared assets location
assetLoop@ for ((mapName, assetMap) in assetMaps) {
if (path != null) {
if(path.startsWith(assetMap.virtualPath)) {
val assetMapObj = assetMaps[mapName]
if (assetMapObj != null) {
var trimmedPath = path.replace(assetMap.virtualPath,assetMapObj.getAssetPath())
if (trimmedPath.startsWith("/")) {
trimmedPath = trimmedPath.drop(1)
}
processedRoute.path = trimmedPath
processedRoute.isAsset = true
processedRoute.isIgnoreAssetPath = true
break@assetLoop
}
}
}
} …
```

feat(android): enable loading of assets outside of the content web asset directory

---

cli/src/tasks/copy.ts

This allows for Certs. to be copied into the necessary places to be used with the Enterprise SSL Pinning Plugin

feat(cli): add ssl pinning copy logic

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/ICapacitorHttpUrlConnection.java
ios/Capacitor/Capacitor/Plugins/CapacitorHttp.swift
ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift
ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift

This PR changes the interfaces in the HTTP plugin to be public so they can be extended by other plugins.

chore(http): make interfaces public

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift
ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

This PR fixes an issue with the fetch/XHR override where http headers were not being set on the request
Resolves: #6297, #6274

fix(ios): Correctly Attach Headers to Request

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

If the fetch call uses headers created with the Headers interface, they can't be handled by http plugin since they are not serializable on iOS and are serializable on Android but are not proper headers.
This PR checks if the headers are a instance of `Headers` and use its entries to get the headers javascript object.

fix: handle fetch headers that are Headers objects

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorHttp.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java
cli/src/tasks/copy.ts

SSL CLI commands: #6312 
This PR adds necessary support on android for attaching SSL certificates to a HTTP request via our `enterprise-ssl-pinning` plugin.

feat(android): Add SSL Pinning logic

---

ios-template/.gitignore

The cap build ios command will produce an ipa file in the folder App/output. This change ensures that the folder is ignored by source control

chore(ios-template): git ignore App/output folder produced by cap build ios

---

android-template/gradle.properties

Removes `android.enableJetifier` in from the android template as its no longer needed for modern libraries.

feat(android-template): Removing enableJetifier

---

android-template/gradle.properties
android/capacitor/gradle.properties
android/gradle.properties
scripts/publish-android.sh

Removes `android.enableJetifier` in core and in the publish script as its no longer needed for modern libraries.

feat(android): Removing enableJetifier

---

android/capacitor/lint.xml
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

When targeting SDK 33, multiple `DiscouragedApi` errors appear in `BridgeActivity.java` and `AssetUtil.java` classes because of the usage of reflection for getting resources from the name.
`BridgeActivity.java` I've used `R.style.AppTheme_NoActionBar` instead of the name, there was already a line like that for the activity theme, so removed the string one and replace the string with the `R.style.AppTheme_NoActionBar` on the app theme line. Not sure if it was a mistake to have them duplicated, but doesn't seem to break anything with the change.
For `AssetUtil.java` it can't be fixed because we allow plugins to get resources dynamically from the javascript name the users provide, so I've just silenced the warnings. 
We could probably remove some of the methods that generate the warnings …

fix(android): solve and/or silence lint errors

---

cli/package.json

Bump minimum version to native run 1.7.2 so `npx cap run ios --target [UUID]` now works and does not fail silently. Should show errors on locked device, etc.

chore(cli): Upgrade minimum native-run to fix bug

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java

breaking change, we have been warning about it.
To match iOS behavior, make getArray and getObject return null
We are doing null checks in most plugins and they are not working because of this returning empty objects/arrays, so should fix several problems.
But also will break camera requestPermissions as it's not doing null check, and probably several user plugins.

refactor(android)!: make call getArray and getObject return null

---

ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift

Fixes https://github.com/ionic-team/capacitor/issues/6308 for Capacitor 4.x
[Relevant comment](https://github.com/ionic-team/capacitor/pull/6313#issuecomment-1462355249)

fix(iOS): Separate cookies by ; rather than ; when accessing through document.cookie (Cap 4.x)

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPWebView.swift

allowFileAccessFromFileURLs is a non documented preference that can cause security warnings
it allows to load file:// urls in the WKWebView, but Capacitor uses custom schemes for serving the local files and provides a helper to convert any file:// url to a capacitor://localhost url, so the preference shouldn't be needed anymore, and if anybody is using it, should move to the capacitor://localhost urls
closes https://github.com/ionic-team/capacitor/issues/6131

refactor(ios): remove allowFileAccessFromFileURLs preference call

---

cli/src/tasks/init.ts

I just noticed I had this unsaved change from https://github.com/ionic-team/capacitor/pull/6420

chore(cli): missing bundledWebRuntime removal

---

cli/src/android/build.ts
cli/src/index.ts
cli/src/tasks/build.ts

Adds support for Android build flavors via `cap build android --flavor <flavor>`.
closes: https://github.com/ionic-team/capacitor/issues/6269

feat(cli): Add support for Android build `--flavor`

---

android/capacitor/build.gradle
android/capacitor/lint.xml

made it `informational` instead of `ignore` so it still gets shown in the lint analysis results, so we have the `Build.VERSION.SDK_INT` checks present for future Capacitor updates where we drop support of older Android versions and the code is no longer needed.
closes https://github.com/ionic-team/capacitor/issues/6260

chore(android): hide ObsoleteSdkInt errors

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java
android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorHttp.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java

Storing references to the Bridge in static classes will hold views in memory outside of their lifecycle, because the Bridge has an activity/fragment variable to keep a reference to its view. This is more obvious in Portals apps where memory leaks were found:
```
┬───
│ GC Root: System class
│
├─ java.net.CookieHandler class
│    Leaking: NO (a class is never leaking)
│    ↓ static CookieHandler.cookieHandler
│                           ~~~~~~~~~~~~~
├─ com.getcapacitor.plugin.CapacitorCookieManager instance
│    Leaking: UNKNOWN
│    Retaining 266.6 kB in 3585 objects
│    ↓ CapacitorCookieManager.bridge
│                             ~~~~~~
├─ com.getcapacitor.Bridge instance
│    Leaking: UNKNOWN
│    Retaining 266.5 kB in 3580 objects
│    context instance of …
```

fix(android): remove stored references to bridge that holds it in memory

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

compare the scheme and hostname instead of if the url starts the same way

fix(android): proper app url check for launching intents

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java
ios/Capacitor/Capacitor/CAPPlugin.h
ios/Capacitor/Capacitor/CAPPlugin.m

Adds support for retaining multiple calls per event on iOS and Android.
closes: https://github.com/ionic-team/capacitor/issues/5967

feat: retain multiple calls per event until consumed

---

core/native-bridge.ts

This url is used in `cordova-plugin-ionic` to do live updates. Without this fix the `response.url` would be an empty string here:
https://github.com/ionic-team/cordova-plugin-ionic/blob/5b190675525806ea15e56d4e59eb67b74cc58c55/www/common.ts#L288
and live updates do not work.

fix: copy url from nativeResponse to response in native-bridge.ts

---

cli/src/index.ts
cli/src/tasks/migrate.ts

This adds a non-interactive option for cap migrate so:
npx cap migrate --noprompt --packagemanger pnpm
will migrate to cap 5 without requiring user interaction and use pnpm as the package manager. Package manager can be npm, yarn, pnpm

feat(cli): non interactive migrate

---

cli/src/tasks/migrate.ts

Requested by @dtarnawsky as part of #6461 - we now run `npm update` or the equivalent when we migrate.

feat(cli): add npm update step to migrate

---

cli/src/config.ts
cli/src/definitions.ts
cli/src/ios/common.ts
cli/src/ios/doctor.ts
cli/src/ios/update.ts
cli/src/tasks/add.ts
cli/src/tasks/update.ts

Bundler isolates RubGems dependencies from the host operating system and creates a consistent environment. Gem dependencies can be pinned to exact versions by using a `Gemfile`. CocoaPods is modeled after Bundler.
This ensures all developers and CI machines use the same CocoaPods version. It's also conveniently used to install CocoaPods plugins, e.g. `cocoapods-art`, or additional iOS development tools, such as `xcpretty`.
Multiple cases are now handled correctly. If a `Gemfile` is found:
- At the Git repository root, in case of a multi-app project
- At or below the app directory, in case of a single-app project
Then:
1. Use Bundler to install RubyGems, including CocoaPods:
1. If Bundler is outdated, update first by executing
`gem install bundler`
2. If RubyGems bundle is outdated, update …

feat(ios): Add Bundler support

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java

> Today, `Accept-Charset` is most notable for being one of several forbidden header names.
more info at
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset
https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
this header is part of one of our OWASP rulesets and is causing many issues.

fix: remove accept-charset

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java

This PR fixes a bug on Android where the cookie handler is overwritten even when the plugin is disabled.

fix(cookies): check isEnabled before setting cookieHandler

---

android/capacitor/src/main/assets/native-bridge.js
ios/Capacitor/Capacitor/assets/native-bridge.js

https://github.com/ionic-team/capacitor/pull/6397 was merged, but it only included the changes in the .ts file, not in the generated .js files
the [4.x cherry-pick](https://github.com/ionic-team/capacitor/pull/6470) is correct, so it's only needed in main branch

fix(ios/android): copy url from nativeResponse to response

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

`url` can be a `tel:` or `mailto:` or other app urls that will not include a host, which will make the app to crash because of using `equals` on a null object.
Reversing the check order, since `appUri` will always have a host, it will not crash.
closes https://github.com/ionic-team/capacitor/issues/6483

fix(android): launching intents without host

---

android/capacitor/build.gradle

Add a dependency to kotlin-bom to prevent kotlin version mismatch between the androidx dependencies or other gradle dependencies that use kotlin

fix(android): unify kotlin dependency version

---

cli/src/declarations.ts
ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/CAPInstanceConfiguration.h
ios/Capacitor/Capacitor/CAPInstanceConfiguration.m
ios/Capacitor/Capacitor/CAPInstanceDescriptor.h
ios/Capacitor/Capacitor/CAPInstanceDescriptor.m
ios/Capacitor/Capacitor/CAPInstanceDescriptor.swift
ios/Capacitor/Capacitor/Capacitor.h
ios/Capacitor/Capacitor/CapacitorBridge.swift
ios/Capacitor/Capacitor/WKWebView+Capacitor.h
ios/Capacitor/Capacitor/WKWebView+Capacitor.m
ios/Capacitor/Capacitor/WKWebView+Capacitor.swift

allow WKWebViews to be inspectable in 16.4 without using the 16.4 SDK with Xcode 14.3
Backported to 4.x in https://github.com/ionic-team/capacitor/pull/6500

feat(ios): add webContentsDebuggingEnabled configuration

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java

This PR fixes an issue with `CapacitorCookies` where `localUrl` and `serverUrl` were initialized to null due to the plugin loading before the WebView. Instead we move the initialization of the `cookieManager` to after the patching of `document.cookie`
Addresses: #6467 and #6479 in `4.x`

fix(cookies): init cookie manager after server url is set

---

cli/package.json

Latest release of @ionic/utils-subprocess doesn't work on node 12.
While docs say that Capacitor 4 supports node 14 and newer, on code it requires node 12.4 or newer, so I think it should still work there.
Or if not, we should change the node check to require node 14 so the users see an error about the node version being unsupported rather than a weird message

fix(cli): Pin @ionic/utils-subprocess version for node 12 support

---

.github/workflows/ci.yml
cli/package.json

3.x branch doesn't build on the ci because of macos-latest not having xcode 12.4 and a problem on latest @types/node
use macos-11 and pin @types/node version so it builds

fix(ci): use macos-11 to run and pin @types/node

---

.github/workflows/publish-latest.yml
.github/workflows/publish-npm-alpha.yml
.github/workflows/publish-npm-beta.yml
.github/workflows/publish-npm-dev.yml
.github/workflows/publish-npm-latest.yml
.github/workflows/publish-npm-nightly.yml
.github/workflows/publish-npm-rc.yml
package.json

See https://github.blog/2023-04-19-introducing-npm-package-provenance/
This also cleans up the following in the GitHub Actions workflows:
* npm 9.5 is now included with node 18
* use setup-node to [cache package data](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data)
* use setup-node to configure npm token via [NODE_AUTH_TOKEN](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm)

chore(ci): enable npm package provenance

---

cli/src/tasks/migrate.ts

Add missing google-maps plugin variables so the migrator update them if present.
Also add camera and notifications plugins to the breaking list as them have permission related changes that require user attention.
Update the breaking changes url as capacitor 5 docs have "next" on the url

fix(cli): Migrate more plugin variables

---

cli/src/tasks/migrate.ts

We should install `^5.0.0` version instead of `5.0.0` version so users get new versions

fix(cli): install minor Capacitor 5 version

---

cli/src/tasks/migrate.ts

use `resolveNode` to get the proper node_modules path instead of hardcoding to `node_modules` so it works in monorepo setups
closes https://github.com/ionic-team/capacitor/issues/6588

fix(cli): proper plugin module patch in monorepos

---

cli/src/tasks/migrate.ts

If npm install failed because of peer dependency problems, don't end the migration with a "success" message, warn instead.
Also skip some steps if npm install failed because the will cause issues and confusion. 
Also change the messaging if the plugin that is not updated is a core plugin to tell users to update the plugin instead of saying it doesn't support Capacitor 5.

fix(cli): Don't succeed migration if npm install failed

---

cli/src/tasks/migrate.ts

When AndroidManifest.xml contains other attributes after the package, the regex matches all attributes and writes all of them into build.gradle.
If AndroidManifest.xml contains:
<manifest package="com.example.app" xmlns:android="http://schemas.android.com/apk/res/android">
app/build.gradle will contains xmlns:android property and 'Upgrading gradle wrapper files' fails
android {
namespace "com.example.app" xmlns:android="http://schemas.android.com/apk/res/android"

fix(cli): correct migration of package from AndroidManifest.xml to build.gradle

---

core/src/index.ts

This PR exports the `buildRequestInit` function from the core `CapacitorHttp` plugin so that `downloadFile` (and other libraries) can use the utility function.

feat: export buildRequestInit function so we can use for downloadFile

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPWebView.swift
ios/Capacitor/Capacitor/WebViewAssetHandler.swift

Addresses: #4089
This PR sets CORS headers so local files can be fetched on iOS while using live reload.

fix(ios): set cors headers in asset handler for live reload

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

In plugin's `load()` method, `getLocalUrl()` is null because it's being set after the plugin initialization.
I've moved the code related to the localUrl creation to the `initWebView()` so it's available in `load()` method.
Once it's merged we can revert the changes made in Cookies plugin to init the plugin after the local url is set.

fix(android): Move bridge localUrl initialization to initWebView

---

cli/package.json

babel types are making cli to throw some errors on cli build on 4.x branch
https://github.com/ionic-team/capacitor/pull/6686

chore(cli): Pin @types/babel__traverse version to fix build

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java

This PR adds a check for `excludedDomains` in before proceeding with an SSL Pinning request

feat(android): add check for excluded domains before ssl request

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java

This PR reverts the `CapacitorCookieManager` initialization  to the plugin's `load()` method and fixes the issue where CapacitorCookies plugin methods are throwing NullPointerException when patching document.cookie is disabled.
Addresses: https://github.com/ionic-team/capacitor/issues/6640

fix(android): revert cookie manager initialization to plugin load for 4.x

---

.github/ionic-issue-bot.yml

Whenever we add the "type: bug" label, the bot will add a comment so users know the issue is real and it's being tracked.

chore: Add bot comment on triaged issues

---

ios/Capacitor/Capacitor/CAPWebView.swift

Cyclic reference between lazy `assetHandler` and lazy `bridge` variables causes a crash

fix(ios): Revert server url addition for CAPWebView.

---

android/capacitor/src/main/assets/native-bridge.js
android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java
core/native-bridge.ts
core/src/core-plugins.ts
core/src/definitions-internal.ts
core/tsconfig.json
ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift
ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

This is https://github.com/ionic-team/capacitor/pull/6206 for capacitor 5 (tested against 5.0.5)
Also includes a fix for the `content-type` bug mentioned [here](https://github.com/ionic-team/capacitor/issues/6604)

feat(http): support for FormData requests

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java
android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java
ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift

This PR adds error handling to the `Cookies` plugin and prevents unnecessary crashes by attempting to sanitize the URL before proceeding to access or store a cookie.

fix(cookies): sanitize url before retrieving/setting cookies

---

ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift

This is related on feat(http): support for FormData requests #6708
When comparing FormData with the type string and base64File we see that in the case string a second \r\n is missing after content disposition in iOS. This leads to the fact that we receive a 400 Bad Request from the server with a request from iOS.
> In HTTP version 1.x, header fields are transmitted after the request line (in case of a request HTTP message) or the response line (in case of a response HTTP message), which is the first line of a message. Header fields are colon-separated key-value pairs in clear-text string format, terminated by a carriage return (CR) and line feed (LF) character sequence. **The end of the header section is indicated by an empty field line, resulting in the transmission of two consecutive …

fix missing \r\n after Content-Disposition in iOS

---

cli/src/tasks/migrate.ts

Migration was throwing an error because I only had dev dependencies.
```
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at installLatestLibs (/Users/pete/Development/GitHub/acimce-kit/node_modules/@capacitor/cli/dist/tasks/migrate.js:257:33)
```

fix(cli): Empty fallback if no non-dev dependencies

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

This PR fixes issues with `XMLHttpRequest` event dispatching:
1. Some events such as `onload` were previously firing twice due to manually attempting to override the prototype event listeners. Now we allow the original XHR to handle setting the event listeners, but we still manually dispatch each event.
2. Some events were not being emitted in the proper order (`loadstart` for example)
3. `onreadystatechange` was previously not firing when the XHR object was being constructed due to a race condition.
Test app (test parity with web):
https://github.com/ItsChaceD/capacitor-http-xhr-events

fix(http): fire events in correct order when using xhr

---

cli/src/android/doctor.ts

Removed the package id checks since they no longer make sense, apps no longer have the package in the AndroidManifest.xml, the package doesn't have to match the applicationId and the MainActivity.java doesn't need to be on the same folder structure that matches the package.
Also since I refactored the MainActivity existence check, I added a .kt check too so doctor doesn't fail if users are using kotlin instead of java.
closes https://github.com/ionic-team/capacitor/issues/6713
closes https://github.com/ionic-team/capacitor/issues/3749

fix(cli): remove package related checks on doctor command

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

`WebChromeClient.FileChooserParams.parseResult` doesn't work fine when other gallery apps are used for the input file with multiple attribute if the user only picks a single image, so always handle the file picking ourselves if `resultIntent.getClipData() != null`, no matter how many elements it contains.
closes https://github.com/ionic-team/capacitor/issues/6758

fix(android): allow single input file selection from samsumg gallery

---

android/capacitor/proguard-rules.pro

With the update to gradle 8, now R8 is being used for code shrinking/obfuscating and current proguard rules don't seem to be enough and it's removing all plugin classes.
I've added a new rule that avoids R8 removing classes that extend `com.getcapacitor.Plugin` class (all Capacitor plugins).

fix(android): avoid R8 optimizations remove plugin classes

---

android/capacitor/src/main/assets/native-bridge.js
android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java
core/native-bridge.ts
ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

This PR prevents cookies with the `httpOnly` attribute from being accessed by the client to align with web restrictions (https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies).

fix(cookies): hide httpOnly cookies from client

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Closes #6739, #6751, #6798
This PR moves the overriding of critical XHR property descriptors to after we know the request is not for a relative URL. It also adds compatibility for if `ProgressEvent` is overridden by a polyfill.

fix(http): return valid response for relative url xhr requests

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorHttp.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java

Closes #6795
This PR handles cleanup of Http connections when the bridge is destroyed. The issue referenced contains a test app.

fix(http): disconnect active connections if call or bridge is destroyed

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java
android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java

Closes #6809
This PR adjusts the behavior of Android WebView "session" cookies to be cleared when the Cookie Manager is initialized.
See https://github.com/ionic-team/capacitor/issues/6809#issuecomment-1679733197 for more information.

fix(cookies): remove session cookies when initializing the cookie manager

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java

Closes #6819
This PR fixes an issue on Android where `parseJSON` would try to force convert booleans and numbers to JSON objects instead of returning them as-is.

fix(http): return numbers and booleans as-is when application/json is the content type

---

ios-template/App/Podfile
ios/scripts/pods_helpers.rb

`assertDeploymentTarget` was moved back to the `pods_helpers.rb` file, but the Xcode 15 patch is still in the users `Podfile`. So better move the code to `@capacitor/ios` so we can remove or edit it if needed without requiring users to edit their code or without the need of making migrate command to write that block of code for the Capacitor 6 migration.

refactor: move the Xcode 15 patch from the template to @capacitor/ios

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

This PR fixes an issue where only a constructed XHR object inherited native properties such as DONE, and not the window.XMLHttpRequest object itself.
For example:
```
xhr.onreadystatechange = () => {
if (xhr.readyState === 4) {
alert(`xhr.DONE is ${xhr.DONE}`); // This was defined
alert(`XMLHttpRequest.DONE is ${XMLHttpRequest.DONE}`); // This was undefined
}
};
```

fix(http): inherit object properties on window.XMLHttpRequest

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Closes https://github.com/ionic-team/capacitor/issues/6174
This PR fixes fetch requests failing when using a Request object as the resource

fix(http): add support for Request objects in fetch

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

This PR fixes an issue where `responseType` is ignored on `XMLHttpRequest` / Angular HTTP when it is set to `blob` or `arraybuffer`

fix(http): add support for defining xhr and angular http response types

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java

In CapacitorCookieManager we are using Android's `Log` class instead of our custom `Logger` class which allows to easily disable logging.
Replaced the `Log` calls with their `Logger` equivalents.
closes https://github.com/ionic-team/capacitor/issues/6922

fix(android): Use Logger class instead of Log in CapacitorCookieManager

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java
cli/src/declarations.ts

This PR fixes a bug introduced after #6787  where cookies are unable to be retrieved at all if using a custom scheme on Android. This is due to WebViews inherently not considering custom schemes as eligible for cookie storage. Therefore, calling `document.cookie` on the WebView was a no-op. However, since the Android cookie store provides no way to access stored cookie properties, there is no way to filter out insecure `httpOnly` cookies when returning them to the WebView. This will add `androidCustomSchemeAllowInsecureAccess` as a config option, which will return ALL cookies from the cookie store at the given url, if set to true.

fix(cookies): retrieve cookies when using a custom android scheme

---

cli/package.json

in case the users have 1.7.2 already installed, force 1.7.3 or newer

fix(cli): force latest native-run version for iOS 17 support

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

closes #6855 
This PR fixes XHR `getAllResponseHeaders()` and `getResponseHeader()` to be case-insensitive to match the spec.

fix(http): return xhr response headers case insensitive

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Closes #6916 
This PR fixes an issue after #6868  where `POST` requests are failing on native.

fix(http): parse readablestream data on fetch request objects

---

android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
cli/src/declarations.ts

We documented that Capacitor 6 would use https as default scheme, so changing it.

feat(android)!: Use https as default scheme

---

cli/src/tasks/init.ts

Since capacitor android uses https by default now, init doesn't need to add the androidScheme configuration anymore on init command

chore(cli): remove androidScheme initialization

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Converting the resource object to a Request object makes the url absolute, so all the resources are going through the patched fetch even if resource was a relative url before the conversion to Request.
Instead of checking if the url starts with http/https, as all are now, check if the url starts with the server url value, as if it starts with the server url value it should be a local request. 
I'm adding a `/` at the end of the server url so request to the same url but with a different port don't get intercepted.
closes https://github.com/ionic-team/capacitor/issues/6944

fix(android): make local urls use unpatched fetch

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java
android/capacitor/src/main/java/com/getcapacitor/WebViewListener.java

Portals developer app was crashing because they don't have a way to override this method in the WebViewClient in Capacitor. This adds the method to the interface so that it can be overridden via Portals. Not a breaking change.

feat(android): allow developers to provide logic for onRenderProcessGone in WebViewListener

---

android/capacitor/src/test/java/android/util/Log.java

If tests call code that has Logger calls (like https://github.com/ionic-team/capacitor/pull/6983) they fail because Logger calls Log internally and it's not available on tests.
This mocks Log class so tests don't break.

chore(android): Mock Log class for tests

---

core/src/web-plugin.ts

It's been deprecated and warning for a few versions, removing it now.

feat!: remove sync remove method for addListener

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
android/capacitor/src/test/java/com/getcapacitor/ConfigBuildingTest.java
cli/src/declarations.ts
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPInstanceConfiguration.h
ios/Capacitor/Capacitor/CAPInstanceConfiguration.m
ios/Capacitor/Capacitor/CAPInstanceDescriptor.h
ios/Capacitor/Capacitor/CAPInstanceDescriptor.m
ios/Capacitor/Capacitor/CAPInstanceDescriptor.swift
ios/Capacitor/Capacitor/WebViewDelegationHandler.swift

This PR creates a new `zoomEnabled` setting to control the zoomability of the Capacitor WebView, and sets the default `zoomEnabled` setting on iOS and Android to `false`.
fixes: https://github.com/ionic-team/capacitor/issues/4620

feat!: Configurable WebView Zoom Setting

---

package.json

18.18.7 was released yesterday and it breaks core tests

chore: Pin @types/node version to fix core tests

---

.github/workflows/ci.yml

I saw the ci action was showing a warning because this action was for node 12 so I was going to update it, but in the repository the author said that we "probably don't need this action" and that we should use `concurrency` instead, so I was going to replace it with a `concurrency` entry, but [Mike already added it a few months ago,](https://github.com/ionic-team/capacitor/blob/787244dc9a6fe9c6c86092e8cfcecc9ffaf0c488/.github/workflows/ci.yml#L14) so the action shouldn't be needed anymore.

chore(ci): Remove unneeded action

---

cli/package.json

I've released native-run 2.0.0, so make the CLI use that version since it fixes the SDK 34 problem.

fix(cli): Use latest native-run

---

cli/package.json
package.json

While the build works because the missing dependencies are dependencies of other dependencies, it could break in the future of those dependencies stop adding our missing dependencies as dependencies, so better add them now to prevent possible future issues.
Closes https://github.com/ionic-team/capacitor/issues/7035

chore: Add missing dependencies

---

ios/scripts/pods_helpers.rb

Note: We have to document that Capacitor 6 requires CocoaPods 1.13.0 or greater
closes https://github.com/ionic-team/capacitor/issues/6939

fix(ios): Remove CocoaPods Xcode 15 workaround that causes issues

---

ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/CapacitorCordova.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVWebViewProcessPoolFactory.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVWebViewProcessPoolFactory.m

cherry-pick https://github.com/ionic-team/capacitor/pull/7096

fix(ios): add some new cordova-ios classes used by Cordova plugins 

---

core/src/core-plugins.ts

cherry-pick https://github.com/ionic-team/capacitor/pull/7002

docs(http): FormData and other complex types do not work on CapacitorHttp plugin methods on native platforms

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java

cherry-pick https://github.com/ionic-team/capacitor/pull/7001

fix(http): properly write form-urlencoded data on android request body

---

ios/Capacitor/Capacitor/Codable/JSValueDecoder.swift
ios/Capacitor/Capacitor/Codable/JSValueEncoder.swift
ios/Capacitor/CodableTests/CodableTests.swift
ios/Capacitor/CodableTests/NestedCodableTests.swift
ios/Capacitor/CodableTests/SuperCodableTests.swift

running `npm run fmt` with swiftlint 0.53.0 does this changes, not sure if it was missed or was using a different version

chore(ios): format the new codable classes

---

ios/Capacitor.podspec

This will allow for more sub-folders to be added without having to explicitly declare them in the podspec.

chore(ios): Clean up podspec for source files

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/res/layout/no_webview.xml
android/capacitor/src/main/res/values/strings.xml

Add a basic layout with a text error message for when there is no WebView installed on the device or is disabled.
Users can use their own text by adding a `<string name="no_webview_text">custom text</string>` entry in their `strings.xml`, or create their own `no_webview.xml` layout that would replace Capacitor's default one.
Added some `bridge != null` checks as if the app fails to create the WebView, the `bridge` will be null and crash.
closes https://github.com/ionic-team/capacitor/issues/5257

feat(android): Load alternative layout when no WebView

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/AppUUID.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/KeyValueStore.swift
ios/Capacitor/Capacitor/Plugins/WebView.swift

This will prevent every single Capacitor user from having to declare use of a required reason API when it becomes required by Apple. This is also made available for plugin authors or others who utilize Capacitor as a dependency.

feat(ios): Replace usage of UserDefaults with KeyValueStore.

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java

Deprecate hasOptions since it's deprecated on iOS
closes https://github.com/ionic-team/capacitor/issues/6696

chore(android): Deprecate PluginCall hasOption

---

cli/src/tasks/copy.ts

At the moment the SSL pinning plugin only supports DER formatted certificates (binary) on iOS, which should have `.der` extension, not `.cer`, and other formats are not supported at the moment, so the error message is confusing for users.
And on Android it supports multiple formats and extensions.
I'm working on adding support for base64 formatted certificates to the SSL pinning plugin and also make the plugin log if there was a problem with any of the certificates, because at the moment it fails silently, so I think the `.cer` extension check can be removed.
An alternative if we don't want to remove the check would be to expand the file extension list.

fix(cli): remove certificate file extension check on copy

---

core/cookies.md
core/http.md
core/package.json

As far as I know the http and cookies docs on https://github.com/ionic-team/capacitor-docs were once manually generated and are not up to date because of that.
This PR adds a dev dependency to `@capacitor/docgen` in core and adds a `docgen` script to fill the API data in the new `cookies.md` and `http.md` files.

chore(core): Generate docs for http and cookies plugins

---

ios-spm-template/App/App.xcodeproj/project.pbxproj

the SMP template still has some CocoaPods folders that won't be used in the SPM template

chore: Remove CocoaPods leftovers from SPM template

---

android/capacitor/src/main/assets/native-bridge.js
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
core/native-bridge.ts
ios/Capacitor/Capacitor/WebViewAssetHandler.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

I've encoded the host because if if has a port, the `:` will be in the url path and it's not a valid character for the path, despite it works without encoding in the devices I've tested, so it might break in the future. Then I had to decode the url in native side.

fix(http): handle proxy urls with port

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

On Android, if there is a http error instead of returning it on the regular `getInputStream()`, it's returned on the `getErrorStream()`, so check it and if it's `null` then get the regular `InputStream`.

fix(android): handle http errors on the proxy

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

If there was a network error like unknown host or any other error that would cause the request to throw, return `null` so the WebView handles the request itself instead of being intercepted.

fix(android): let WebView handle errors

---

android/capacitor/src/main/java/com/getcapacitor/JSInjector.java

closes https://github.com/ionic-team/capacitor/issues/7309

fix(android): prevent crash on script injection if the script is too long

---

ios/Capacitor.podspec
ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/PrivacyInfo.xcprivacy
ios/CapacitorCordova.podspec
ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/PrivacyInfo.xcprivacy

supersedes #7315 with new branch naming rules

chore(ios): Add xcprivacy for Capacitor and Cordova

---

scripts/native-podspec.sh

run `pod lib lint` instead of `pod spec lint` for local podspec verification

chore(ci): run lib lint for podspec verification

---

ios/package.json
scripts/native-podspec.sh

We are doing pod spec lint on pull requests, but the errors got disabled at some point, probably because we were doing `pod spec lint` (published changes) while we should be doing `pod lib lint` (local changes) and that made some change fail.
And since we disabled the errors I added the `pod lib lint` in the verify script as some errors went through.
This PR reenables the errors and uses `pod lib lint` instead of `pod spec lint` and removes the `pod lib lint` from the verify script since we already run it in the `native-podspec.sh` script.

chore(ci): Re enable pod validation failures

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Instead of creating the proxy url from the bridge url, keep the original url and replace the protocol and host, so other params from the original url such as search or hash don't go missing
closes https://github.com/ionic-team/capacitor/issues/7319

fix(http): keep original URL properties on proxy

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

`addDocumentStartJavaScript`'s `allowedOriginRules` expect urls without paths, if the `server.url` contain paths, remove it from the url passed as  `allowedOriginRules`
closes https://github.com/ionic-team/capacitor/issues/7289

fix(android): Remove path from allowedOriginRules

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Despite `host` includes both `hostname` and `port`, setting the `host` to an url without `port` doesn't remove the existing `port` if there is one, turning the proxy url into an invalid one.
So set the `hostname` and `port` separately to match the capacitor bridge url `hostname`/`port`

fix(http): set port for proxy url

---

cli/src/android/run.ts
cli/src/common.ts
cli/src/config.ts

adding https://github.com/ionic-team/capacitor/pull/6704 to 5.x

fix(cli): apkName for multi-dimensional flavors

---

ios/Capacitor/Capacitor/WebViewAssetHandler.swift

If the proxied request already had CORS headers, we are using the original headers when using live reload, which doesn't work since the request goes from the live reload server to the `capacitor://` scheme.
So this PR forces the CORS headers we add for live reload instead of the original ones.
closes https://github.com/ionic-team/capacitor/issues/7334

fix(ios): overwrite CORS headers on livereload

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

At the moment trying to create a proxy url from a Request object ends up with a `[object Object]` as path.
This PR detects if the first param is a Request object and creates a new Request with the proxied url

fix(http): Make proxy work with Request objects

---

cli/src/ios/update.ts
cli/src/tasks/copy.ts
cli/src/util/iosplugin.ts

`npx cap update` generates the `packageClassList`, but `npx cap copy` does not, which cause the plugins to not work after running `npx cap copy` since they don't get registered.
This PR also runs the `generateIOSPackageJSON` function on copy so the `packageClassList` is always present.

fix(cli): also generate packageClassList on copy

---

core/cookies.md
core/http.md
core/src/core-plugins.ts

https://github.com/ionic-team/capacitor-docs/blob/main/docs/apis/cookies.md and https://github.com/ionic-team/capacitor-docs/blob/main/docs/apis/http.md files have more information than the ones generated in core.
Add the missing information to core-plugins.ts and generate the files again

docs(core): Add missing information to http/cookies files

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

On iOS >= 17.2, the `proxyUrl.protocol = bridgeUrl.protocol;` is not changing the protocol of the proxy url.
Change the `proxyUrl` generation to return the `bridgeUrl`, which already has the `capacitor` protocol and add the other relevant `proxyUrl` parameters and modified `pathname`.
closes https://github.com/ionic-team/capacitor/issues/7352

fix(http): change proxy url generation

---

cli/src/util/iosplugin.ts
ios/Capacitor/Capacitor/CapacitorBridge.swift

The Cordova plugins javascript injection is not working because the plugins are now being read from the list that the CLI generates, and the CLI doesn't generate Cordova plugin classes.
Since trying to figure out all the Cordova plugin classes is very complex and the classes are not really needed for injecting the javascript code, I've just edited the CLI to add a generic `CDVPlugin` class to the plugin list if there are cordova plugins installed, and instead of checking the superClass I just check if there is a `CDVPlugin` class in the list, and if there is one, inject the cordova files.

fix: inject cordova files if a cordova plugin is present

---

cli/src/android/build.ts

Passwords for apksigner require `pass:` signature before the actual password.
The initial commit on https://github.com/ionic-team/capacitor/pull/7073 had it like that, but when changes were requested the `pass:` part got deleted inadvertently.
closes https://github.com/ionic-team/capacitor/issues/7299

fix(cli): use correct pass signature for apksigner signing

---

cli/src/util/iosplugin.ts

The check for detecting Capacitor plugins is incorrect, should not check for undefined name but for `Core` type.

fix(cli): Change Capacitor plugin files check

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookieManager.java

secure cookies often are not set by the cookie plugin. This code correctly sets them.
This code fixes Android. There seems to be problems in iOS as well.

fix: secure cookies often are not set by the cookie plugin

---

cli/src/tasks/migrate.ts

Since latest Android Studio prompts to update Gradle to 8.4 some users might have updated their apps already.
Capacitor 6 will use 8.2.1 by default, the migrate command is downgrading the Gradle version if the user already updated.
This PR checks the Gradle wrapper version and avoids the update if the existing version is newer than 8.2.1.
Removed the `updateGradleWrapper` function because it's not needed, `updateGradleWrapperFiles` already updates it, but moved it to be run first as updating the Gradle plugin before the Gradle wrapper it can cause update failures if the plugin version is incompatible with the wrapper version.

fix(cli): Don't downgrade gradle version on migrate

---

cli/src/tasks/migrate.ts

Adds support for bun when running:
`cap migrate --noprompt --packagemanager=bun`
Resolves #7326

feat(cli): Support bun when running cap migrate

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

If the server url ends in `/` the app crash because the path replacement messes with the other `/` in the url.
Instead replace the last character from the url.
Closes https://github.com/ionic-team/capacitor/issues/7423

fix(android): avoid crash if server url ends in /

---

ios/Capacitor/Capacitor/WebViewAssetHandler.swift

add an extension to see if the urlSchemeTask was stopped and check it before calling its methods as they crash if the urlSchemeTask is stopped
closes https://github.com/ionic-team/capacitor/pull/7478
closes https://github.com/ionic-team/capacitor/issues/7404
closes https://github.com/ionic-team/capacitor/pull/7453
closes https://github.com/ionic-team/capacitor/pull/7460

fix(ios): check if urlSchemeTask is stopped before calling its methods

---

cli/src/tasks/migrate.ts

If the Android project is in not buildable state, gradle will fail to update the files because the project needs to build to update gradle.
Running npx cap sync before updating the gradle files will generate other non committed gradle files that are needed to build the project and that are not there in case the project was just checked out from github and never ran npx cap sync before on the project.
Also error the migration if npx cap sync failed to run, getCommandOutput doesn't error and reports the command as a success despite it failed, by using runCommand instead, it will fail the migration if npx cap sync fails.
closes https://github.com/ionic-team/capacitor/issues/7489

fix(cli): Run sync before updating gradle

---

cli/src/tasks/migrate.ts

Checking the new barcode plugin[ I noticed](https://github.com/ionic-team/capacitor-barcode-scanner/pull/9) that in the example app the `minSdkVersion` was downgraded from the required 26 to 22, so I checked if this was caused by migrate command, and it was, it changes any version in the `variables.gradle` to match the default Capacitor ones, even if that means downgrading it.
This PR checks the version and only update them if the value in `variables.gradle` is smaller.

 fix(cli): Don't downgrade variables on migrate

---

cli/src/common.ts
cli/src/tasks/copy.ts
cli/src/tasks/sync.ts
cli/src/tasks/update.ts

Also run `capacitor:copy:before`, `capacitor:copy:after`, `capacitor:update:before`, `capacitor:update:after`, `capacitor:sync:before` and `capacitor:sync:after` hooks in Capacitor and Cordova plugins if present in their `package.json` file.
This way Cordova plugins can have separate hooks from the Cordova ones to be run in Capacitor apps as their logic will most likely need to be different in Capacitor projects.

feat(cli): run plugin hooks

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Move readyState override to open method and do it only for POST requests as the others don't use the overridden XHR object and the override messes with the original object. 
closes RDMR-132
closes https://github.com/ionic-team/capacitor/issues/7417

fix(http): don't override readyState for non POST requests

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/CAPPluginMethod.h
ios/Capacitor/Capacitor/CAPPluginMethod.m
ios/Capacitor/Capacitor/CAPPluginMethod.swift

Add secondary initializer for CAPPluginMethod that takes a selector. Creates a convenience initializer as well with a Swift enum to avoid having to rely on global string values in the style of CAPPluginReturnPromise. For a pure Swift plugin implementation, it makes the definition potentially go from:
```swift
class MyPlugin: CAPPlugin, CAPBridgedPlugin {
let pluginMethods: [CAPPluginMethod] = [
.init(name: "promiseMethod", returnType: CAPPluginReturnPromise),
.init(name: "callbackMethod", returnType: CAPPluginReturnCallback)
]
@objc func promiseMethod(_ call: CAPPluginCall) {}
@objc func callbackMethod(_ call: CAPPluginCall) {}
}
```
to this:
```swift
class MyPlugin: CAPPlugin, CAPBridgedPlugin {
let pluginMethods: [CAPPluginMethod] = [
.init(#selector(promiseMethod)), …
```

feat(ios): CAPPluginMethod selector-based initializer

---

ios/Capacitor/Capacitor/CapacitorBridge.swift
ios/Capacitor/Capacitor/KeyValueStore.swift

Accessing `storedCalls` from two different threads causes crash since `Dictionary` is not thread safe that introduces data-race. The serial queue prevents the access to the shared resource by two different threads by queuing the operation and invoking the functions one-by-one.
There is other option to avoid data-race using locks, and top of that, there are two types of locks that can be used here: `NSLock` and the other one is `OSAllocatedUnfairLock`, which is faster than the first one.

[Bug]: add serial dispatch queue for `storedCalls` to avoid data-race

---

.github/workflows/publish-android.yml
.github/workflows/publish-ios.yml

actions were updated to v4, but the ones used in publish-ios and publish-android weren't updated

chore(ci): Use v4 actions on publish ios and android

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java

When using multipart/form-data in a POST request on Android, the values are not encoded, which is problematic when the values contain accents or emojis for example
This merge request proposes to encode values in UTF-8, similar to what is done when encoding other POST requests body
Fixes #7526 
closes https://github.com/ionic-team/capacitor/pull/7219
closes https://github.com/ionic-team/capacitor/pull/6730

fix(android): UTF-8 encode form data value

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java

formData is only being decoded and sent for Android O and newer, but we support 5.1+, add an else to handle the data on older versions

fix(android): send FormData on older devices

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

closes https://github.com/ionic-team/capacitor/issues/7473

fix(http): handle UInt8Array on body

---

cli/src/util/spm.ts

Make the CapApp-SPM project use the configured iOS version (`IPHONEOS_DEPLOYMENT_TARGET`) on the App project instead of the hardcoded version 13.
closes https://github.com/ionic-team/capacitor/issues/7544

fix(ios): Match CapApp-SPM iOS version with project version

---

cli/src/cordova.ts
cli/src/declarations.ts

`cordova.staticPlugins` is used to put some plugins into a separate CocoaPods project that has `static_framework = true`.
This is used in some plugins that use `framework` tag for CocoaPods, which didn't allow to specify if they need to be static.
But using `framework` tag for CocoaPods dependencies is not supported on latest cordova-ios (version 7.x that was released a year ago).
So if Cordova doesn't support that, we shouldn't have this special case for plugins that are out of date. 
If they are up to date, using `podspec` tag instead of `framework` tag, then they can specify if the plugin needs to be static or not and Capacitor already handles that.
Also note that we have a list of plugins that we knew that needed to be static so users didn't have to add them with this configuration …

chore(cli): Deprecate cordova.staticPlugins

---

cli/src/cordova.ts
cli/src/tasks/run.ts
cli/src/util/livereload.ts

This PR enables cleartext when using live reload by directly writing into the `capacitor-cordova-android-plugins`'s `AndroidManifest.xml`, and removes it once the command is stopped.
It no longer overrides the original `extConfig` object but instead modifies the  platform's `capacitor.config.json` after sync.
Added a TODO to remove `editExtConfigForLiveReload` since it's no longer being used.
Added a TODO to remove the last param of `editCapConfigForLiveReload` as it's not being used.
Didn't remove any of them at the moment as people could be using the `CapLiveReloadHelper` directly, so removing them is breaking.
I've put the `process.on('SIGINT'` inside a promise to prevent multiple calls, it was being called three times.
There is an [alternate …

fix(cli): enable cleartext for live reload

---

cli/src/util/iosplugin.ts

support dependencies with ".swift" at the end of name
closes #7582

fix: support dependencies with ".swift" at the end of name

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

clean the path and fragment before passing the `allowedOrigin` to `addDocumentStartJavaScript`
Also catch `IllegalArgumentException` in case the url is still not allowed by `addDocumentStartJavaScript` so it uses the old injector instead of crashing the app.
closes https://github.com/ionic-team/capacitor/pull/7597
closes https://github.com/ionic-team/capacitor/issues/7596
closes https://github.com/ionic-team/capacitor/issues/7327

fix(android): better cleaning of allowedOrigin url

---

cli/src/ios/build.ts

`app-store` is deprecated and was replaced with `app-store-connect` in Xcode 14.3.
It doesn't cause build failures yet, but better replace it now before it causes issues or breaks builds in the future.
It won't be cherry picked into 5.x branch since Capacitor 5 supports Xcode 14 and would require additional logic to use one value or the other based on the Xcode version.
closes https://github.com/ionic-team/capacitor/issues/7632

fix(cli): replace app-store deprecated method on build

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/Codable/JSValueDecoder.swift
ios/Capacitor/Capacitor/Codable/JSValueEncoder.swift
ios/Capacitor/CodableTests/DataCodableTests.swift
ios/Capacitor/CodableTests/DateCodableTests.swift
ios/Capacitor/CodableTests/NonconformingFloatCodableTests.swift
ios/Capacitor/CodableTests/URLCodableTests.swift

The default implementation of URL encodes to/decodes from a dictionary, while Date by default encodes to/decodes from seconds since January 1, 2001.
This implementation is similar to the method for handling dates and urls in [Foundation](https://github.com/apple/swift-foundation/blob/da80d51fa3e77f3e7ed57c4300a870689e755713/Sources/FoundationEssentials/JSON/JSONEncoder.swift#L1140).

feat(ios): JSValueEncoder/Decoder feature parity with JSONEncoder/Decoder

---

android-template/variables.gradle

Bump the `minSdkVersion` of Capacitor-generated Android projects to API level 23.

chore(android-template): update minSdkVersion to 23

---

ios/Capacitor/Capacitor/Codable/JSValueDecoder.swift
ios/Capacitor/Capacitor/Codable/JSValueEncoder.swift
ios/Capacitor/CodableTests/DateCodableTests.swift

chore(ios): address linter errors for Codable implementation
chore(ios): address failing Codable tests when run in a locale other then en_US

chore(ios): fix linter errors and locale sensitive tests for Codable implementation

---

ios/Capacitor/Capacitor/CapacitorBridge.swift
ios/Capacitor/Capacitor/Codable/JSValueDecoder.swift
ios/Capacitor/Capacitor/Codable/JSValueEncoder.swift
ios/Capacitor/Capacitor/WebViewAssetHandler.swift
ios/Capacitor/CodableTests/DataCodableTests.swift
ios/Capacitor/CodableTests/DateCodableTests.swift
ios/Capacitor/CodableTests/NonconformingFloatCodableTests.swift
swiftlint.config.js

The ios template was renamed last year but the path in `swiftlint.config.js` was not adjusted and also the SPM template was not added, so corrected the path and added the SPM path too.
Then ran `npm run fmt` with swiftlint 0.57.0 and it made those changes.
We have some tests folders in the excluded lists, not sure why, but not the `CodableTests` folders, not sure if we want to exclude that too, or remove the exclusion of the other tests folders.

chore: include proper template folders for swiftlint

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
ios/Capacitor/Capacitor/CAPPluginCall.swift

The plugin call methods `success()` and `error()` have been marked deprecated in favor of `resolve()` and `reject()` since August 2020. This pull request removes these methods entirely from the code base.

refactor!: Remove redundant PluginCall methods success() and error()

---

cli/src/tasks/telemetry.ts
cli/src/telemetry.ts

Modify telemetry such that is it opt-out instead of the current opt-in behavior:
- Telemetry checks only occur on specified commands (`init`, `sync`, `copy`, `update`, etc.) per the existing source.
- If the user has not yet opted in-or-out: 
- The user will be automatically opted-in.
- The user will be printed out a thank you message with instructions on how to opt-out (if they wish).
- Once the user has made a preference one way or the other, they will not see any telemetry messaging.
- Users with existing telemetry preferences will have them preserved.

feat(cli)!: change telemetry from opt-in to opt-out

---

cli/src/android/update.ts

We updated the default Capacitor kotlin version to 1.9.10 but Cordova plugins will still use 1.8.20 as default.
Sync the versions.

fix(cli): make Cordova plugins use same default kotlin version as Capacitor

---

.github/workflows/ci.yml
.github/workflows/publish-ios.yml
.github/workflows/publish-npm-alpha.yml
.github/workflows/publish-npm-beta.yml
.github/workflows/publish-npm-dev.yml
.github/workflows/publish-npm-latest-from-pre.yml
.github/workflows/publish-npm-latest.yml
.github/workflows/publish-npm-nightly.yml
.github/workflows/publish-npm-rc.yml

macos-15 is now available and macos-14 has removed Xcode 16, so we can't use it anymore.

chore(ci): use macos-15

---

cli/src/util/spm.ts
ios-spm-template/App/CapApp-SPM/Package.swift

closes https://github.com/ionic-team/capacitor/issues/7735

fix: use Capacitor 6 for SPM dependency

---

cli/src/ios/build.ts
cli/src/tasks/migrate.ts

I updated rimraf to version 6 and the import needs to be updated, otherwise it fails to delete on migrate and build commands.

fix(cli): correct rimraf import

---

cli/src/util/spm.ts
ios-spm-template/App/CapApp-SPM/Package.swift

We did this for Capacitor 6 when we started publishing Capacitor 7 into SPM to make Capacitor 6 use only the 6 version and make it match with the npm installed one
But we also need this for Capacitor 7 in case we publish a Capacitor 6 version to main branch (that will happen when a 6.x release is made after a Capacitor 7 release)

fix: use Capacitor 7 for SPM dependency

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

If status bar plugin is installed, its `CAPBridgeViewController` extension prevents Capacitor's `viewDidAppear` method from being called.
Listen for the notification the extension emits to call the same code in `viewDidAppear`.

fix(ios): listen for CapacitorViewDidAppear

---

ios/Capacitor/Capacitor/WebViewAssetHandler.swift

There are multiple file extensions that support range requests, not only media extensions, we shouldn't be checking `isMediaExtension` for the requested resource if the request has `Range` header, if the header has `Range`, then it should return `206` and the appropriate range headers.
closes https://github.com/ionic-team/capacitor/issues/7789

fix(ios): don't check isMediaExtension on range requests

---

android/capacitor/src/main/java/com/getcapacitor/FileUtils.java

Fix linting error for Android. When building a plugin I get the following error:
```
Execution failed for task ':capacitor-android:lintDebug'.
/node_modules/@capacitor/android/capacitor/src/main/java/com/getcapacitor/FileUtils.java:222: Error: Using name is unsafe as it is a filename obtained directly from a ContentProvider. You should sanitize it before using it for creating a File. [UnsanitizedFilenameFromContentProvider]
File file = new File(context.getFilesDir(), name);
```
I've applied the fix recommended here https://developer.android.com/privacy-and-security/risks/untrustworthy-contentprovider-provided-filename.
closes https://github.com/ionic-team/capacitor/issues/7880
closes https://outsystemsrd.atlassian.net/browse/RDMR-556

fix(android): sanitize portable file name

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

If the user provides the `multipart/form-data` content-type without boundary, the call to `const request = new Request(resource, options);` is not able to generate a browser boundary. 
So remove the content-type from the headers when they are set to `multipart/form-data` and if they don't have a boundary.
Also do it only for `FormData` bodies as other types or bodies are handled differently and I'm not sure if the issue is also present there.
closes https://github.com/ionic-team/capacitor/issues/7589

fix(http): boundary not added for Request objects

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/res/layout/capacitor_bridge_layout_main.xml

kept the old one in case somebody was using it somewhere else, should be removed in Capacitor 8.

fix(android): rename bridge layout to avoid collision

---

capacitor-cordova-ios-plugins/CordovaPluginsResources.podspec
ios/Capacitor.podspec

This was used by CocoaPods to post updates on `CocoaPodsFeed` on twitter, but last post is from 2019 and the sites are down too, so doesn't seem like it's used anymore and also causes a warning on publish about the url not being reachable, so removed it.

chore: Remove social_media_url from podspecs

---

ios/Capacitor/Capacitor/Plugins/HttpRequestHandler.swift

iOS is always encoding url params, this PR reads the `shouldEncodeUrlParams` and not encode them if false.
closes https://github.com/ionic-team/capacitor/issues/7911

fix(ios): respect shouldEncodeUrlParams value

---

cli/src/common.ts

This PR fixes the execution order of CLI Hooks.
The `forEach()` method of Array instances expects synchronous functions and it does not wait for promises.

fix(cli): ensures the execution order of CLI hooks

---

cli/tsconfig.json
core/tsconfig.json

To prevent build failures when there are type problems on `node_modules`.

chore: set skipLibCheck to true in tsconfig.json

---

android/capacitor/src/main/java/com/getcapacitor/CapConfig.java
cli/src/declarations.ts
ios/Capacitor/Capacitor/CAPInstanceDescriptor.swift

Fixes [7972](https://github.com/ionic-team/capacitor/issues/7972).
closes [3912](https://github.com/ionic-team/capacitor/issues/3912)
These changes introduce a new `capacitor.config` flag, `appStartPath`.
On iOS and Android, the logic already existed, but there was no way to configure this value.  This PR simply exposes that configuration.

feat: expose `appStartPath` on cap config server configuration

---

core/cordova.js

Since the addition of the ability to inject misc JS modules into the WebView on https://github.com/ionic-team/capacitor/pull/7864 there's a possibility that some user provided JS module defines a "top-level" `const Capacitor` variable which ends up conflicting with the variable being referenced by cordova.js.
This change makes it so that cordova.js usage of global Capacitor object follows the other usages found throughout the framework where `window.` is prefixed.

refactor(core): reference window.Capacitor

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/CapacitorHttpUrlConnection.java
ios/Capacitor/Capacitor/Plugins/CapacitorUrlRequest.swift

This PR fixes keys and values that were not url-encoded in CapacitorHttp on iOS during `application/x-www-form-urlencoded` HTTP POST requests.
closes: https://github.com/ionic-team/capacitor/issues/7840

fix(http): Properly URL-encode key and values during `x-www-form-urlencoded` POSTs

---

android-template/app/src/main/AndroidManifest.xml
cli/src/tasks/migrate.ts

Adding density to the default `android:configChanges` values prevents the webView from being reloaded on resize. Currently, there is a known issue with android that causes the repainting of the webView to fail on occasion. A bug has been created and can be tracked [here](https://issuetracker.google.com/issues/433671013). 
Alternative solutions:
- Disable hardware acceleration and resizing will work, but app functionality will be degraded.
- Tweak `android:configChanges` if you are okay with losing the state of your webView during resize events.
Example of behavior with the changes in this PR: 
https://github.com/user-attachments/assets/6cafbb1b-9ae9-4082-98ce-0bff36fd327b

feat(android-template)!: added density to configChanges to prevent reloading of the WebView

---

.github/workflows/ci.yml
.github/workflows/publish-ios.yml
ios/package.json

While it's still on beta, it has a symlink to `Xcode_26` so we don't need to update it once it gets updated to the final version

chore(ci): Use Xcode 26

---

ios/Capacitor/Capacitor/WebViewAssetHandler.swift

Since I was looking into replacing the `UTType` related deprecations, I've been testing in different iOS versions and Apple fixed this issue on iOS 17, so updated the TODO to note when we can remove the code since it's fixed now, but only for iOS 17+.
Couldn't run on iOS 15 simulators on Xcode 16, but the problem was still reproducible on iOS 16 rosetta simulator.

chore(ios): Update TODO note in WebViewAssetHandler.swift

---

.github/ISSUE_TEMPLATE/config.yml
.github/ionic-issue-bot.yml

We have different discord invite links, use the official `https://ionic.link/discord` in both places instead

chore: unify discord links
