core/cordova.js
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/JSExport.swift
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVCommandDelegateImpl.m

Added the cordova.js file based on the cordova original one. (has only iOS bridge for now)
Inject cordova_plugins.js. This plugin will be generated on plugin installs, it's needed for plugin clobbers and some other cordova things.
Update CDVCommandDelegateImpl to make it work with the new cordova.js
Store cordova plugins in an array to avoid releases when the plugins use weak selfs.

More cordova

---

README.md

fix minor grammar and spelling mistakes in README.md

[docs] fix minor grammar and spelling mistakes

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/JSExport.java
android/capacitor/src/main/java/com/getcapacitor/JSInjector.java

For now the PR code will always inject the js, I have to find a way of detecting if there are Cordova plugins in the app and avoid injecting this files if there are no plugins

Inject cordova.js and plugins js contents

---

cli/src/ios/update.ts

Improve the processing of Cordova js-modules and generation of cordova_plugins.js
Fixes #93

Improve Cordova plugins handling

---

android/capacitor/build.gradle
android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/java/com/getcapacitor/MessageHandler.java
android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

It uses cordova-android 7 and implements a MockCordovaWebViewImpl to do the Capacitor-Cordova magic

Added Cordova-Android implementation

---

core/cordova.js

Forgot to commit the cordova.js changes for Android compatibility.

Change cordova.js to also work on Android

---

cli/src/android/common.ts
cli/src/android/update.ts
cli/src/config.ts
cli/src/ios/update.ts
cli/src/plugin.ts
cli/src/tasks/update.ts

Create cordova_plugins.js and copy Cordova plugin files to Android public folder
Write config.xml with the needed plugin entries.

Cordova android tooling

---

example/src/app/app.component.ts
example/src/app/app.module.ts

HomePage no longer exists and example fails to build.

Fix example build

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/JSExport.java

And don't crash if they are not present

Only export Cordova files if they are available

---

android/capacitor/src/main/java/com/getcapacitor/JSExport.java

The plugins files code was being duplicated when empty folders were found.

Fix duplicated plugin code

---

cli/src/android/update.ts

Read plugin.xml source-file tags for Android platform and copy files to capacitor-cli assets folder

Copy Android native files to capacitor-cli assets folder

---

cli/src/tasks/update.ts

Fix multiple clobbers formatting

---

android-template/app/build.gradle
android-template/settings.gradle
capacitor-android-plugins/build.gradle
cli/src/android/update.ts

Added to the template the gradle settings to see the capacitor-android-plugins module
Modified the module to include cordova-android so it compiles
Make the update command also copy plugin resources from resource-file tags

Some gradle settings to make the template see the plugin files

---

cli/src/android/update.ts
cli/src/tasks/update.ts

Handle case where plugins don't have platform tags

---

cli/src/tasks/update.ts

Some plugins like dialogs use merges instead of clobbers, this PR handle them too.

Also handle plugin merges

---

cli/src/ios/update.ts

Add just CapacitorCordova instead

Don't add Capacitor dependency for Cordova plugins

---

capacitor-android-plugins/build.gradle
cli/src/android/update.ts
cli/src/ios/update.ts
cli/src/tasks/update.ts

not custom frameworks or gradle references yet, just framework tags referencing gradle libraries.

Handle framework tags from Android plugins

---

cli/src/android/update.ts
cli/src/common.ts
cli/src/ios/update.ts
cli/src/tasks/update.ts
ios-template/App/App.xcodeproj/project.pbxproj
ios-template/App/App/config.xml
ios/Capacitor/Capacitor/CAPBridge.swift
ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/CapacitorCordova.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVConfigParser.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVConfigParser.m

This adds an empty config.xml to the app template
Writes on it based on the Cordova plugins installed
Uses the information on it when loading plugins to have a proper JS name --> native class name mapping instead of trying to guess it.

Cordova config file

---

cli/src/android/update.ts

Replace the preference variables with the default values for the gradle dependencies

Replace preference variable with default value

---

cli/src/ios/update.ts

Custom frameworks are not system frameworks that plugins ship with a .framework file.
This PR copy the .framework to CordovaPlugins CocoaPods repo and add them as vendored_frameworks in the .podspec

Add support for custom frameworks in Cordova plugins

---

site/docs-md/index.md

link the "competing" product mentioned
(also some line breaks removed to make style consistent)

link "success-ees"

---

site/docs-md/getting-started/dependencies.md

highlights the software that has to be installed by making it bold

bold-ify requirements

---

site/docs-md/basics/workflow.md

- Add "Development" to step 1
- Add example build commands to step 1
- Fix typo and add transition before command

improve workflow docs

---

site/docs-md/basics/building-your-app.md

- fix package.json snippet
- fix PWA link
- fix XCode => Xcode
- fix capitalization Android CLI

polish "building your app"

---

site/docs-md/basics/running-your-app.md

Running polish

---

site/docs-md/ios/updating.md

Docs: polish "ios updating"

---

android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

getContext should return the webview context

---

site/docs-md/getting-started/with-ionic.md

- Fix splashscreen package name
- move confusing command to description
- add another headline level so all the "install" steps are grouped together

Docs: Polish with-ionic.md

---

site/docs-md/apis/index.md
site/src/components/site-menu/site-menu.tsx

New "Introduction" site for the "APIs" menu headline that explains a bit what APIs are (and also lists them again).

Docs: API -> Introduction

---

cli/src/ios/update.ts
cli/test/util.ts

Some plugins might include c files (.c), c++ files (.cc) or Objective-C++ (.mm), add those to the podspecs.

Add more extensions to plugin files

---

capacitor-android-plugins/build.gradle
cli/src/android/update.ts

Copy lib files to src/main/libs in capacitor-android-plugins folder

Handle lib-file tag

---

app-template/.gitignore

Basic stuff for @capacitor/cli create.
Addresses: #256

Added generic .gitignore to fresh project template.

---

cli/src/common.ts

[Original Issue](https://github.com/ionic-team/capacitor/issues/268)

Making app name and app id error messages more similar

---

cli/src/ios/update.ts

When a plugin has a framework with podspec we were adding it to the main Podfile, that was causing some files not seeing the framework (see https://github.com/ionic-team/capacitor/issues/281).
So I'm changing it to be a dependency on the plugins .podfile.
I already tried this and didn't work for some Pods that use static libraries, because that was incompatible with us using use_frameworks! on the main Podfile.
But on CocoaPods 1.4 they have added a new feature, we can now specify that our podspec is a static framework by using `s.static_framework = true` and that will get rid of the linking pods with static libraries problem, so I added it to the plugins podspec.
But we have now to require CocoaPods 1.4, we should add that to the docs, right now we don't specify a required version.

Move plugin dependences from Podfile to .podspec

---

.github/CONTRIBUTING.md
cli/src/common.ts
core/package-lock.json
example/README.md
example/ios/IonicRunner/Podfile.lock
example/package-lock.json
example/package.json

- update` example/README` and `.github/CONTRIBUTING.md`
- copy over `native-bridge.js` from `/core` to `/www` in `copy` script
also:
- rename example project from `avocado` to `capacitor-example`
- update package-lock.json files
- remove `@ionic/cli-plugin-cordova`
- update `@ionic/app-scripts` to a version that likes recent NPM on Windows

Improve example project and its documentation

---

ios/Capacitor/Podfile
ios/Capacitor/Podfile.lock

Keeping Capacitor's Podfile up to date in case somebody tries to build the project.

Update Capacitor's Podfile

---

cli/src/android/update.ts
cli/src/cordova.ts
cli/src/ios/update.ts

If the plugin has edit-config or config-file tags, check if the Info.plist or AndroidManifest.xml have the required entries already, and if they don't have them, log a relevant message.

Search for edit-config and config-file tags and show relevant information

---

cli/src/android/update.ts
cli/src/cordova.ts
cli/src/ios/update.ts

Check if the plugin.xml has dependency entries and if the plugin is not present, install it
Closes https://github.com/ionic-team/capacitor/issues/315

Check and install missing plugin dependencies

---

cli/src/electron/copy.ts
cli/src/tasks/init.ts
electron-template/index.js
electron/.gitignore
electron/index.js
electron/package-lock.json
electron/package.json
electron/rollup.config.js
electron/src/electron/filesystem.ts
electron/src/global.ts
electron/src/index.ts
electron/src/plugins.ts
electron/src/runtime.ts
electron/tsconfig.json
electron/tslint.json

Got core working, need to test user custom built plugins now.
Before Merge: 
- Test custom user plugins (should work the same as PWA) **[UPDATE: added a simple custom plugin to the test app and it just works by importing it after installing from npm. see: https://github.com/IT-MikeS/Capacitor_Test ]**
- Add `@capacitor/electron` as dependency to `package.json` of `electron-template`
- Publish `@capacitor/electron`

[WIP] Electron plugin support!

---

cli/src/config.ts
cli/src/ios/update.ts

Use local @capacitor/ios pod

---

site/docs-md/apis/camera/index.md

Update the camera documentation:
- Fix doc 'base64' 
- Modify angular example to display an example where the camera is specified as source

Update camera site doc

---

cli/src/plugin.ts

Remove the meta.cordova check and only read the plugin.xml to detect Cordova plugins
Closes #338

Don't search by cordova key but for plugin.xml file

---

android-template/app/build.gradle
android-template/settings.gradle
cli/src/android/add.ts

Use NPM for Android dependency

---

cli/src/android/update.ts

Use relative paths to gradle-files folder to avoid problems on windows
Closes #356

Use relative path for gradle files

---

core/native-bridge.js
example/src/pages/accessibility/accessibility.ts
example/src/pages/clipboard/clipboard.ts
site/docs-md/apis/accessibility/index.md
site/docs-md/apis/clipboard/index.md
site/src/assets/docs-content/apis/accessibility/index.html
site/src/assets/docs-content/apis/clipboard/index.html

Voice Over returns an object, fix example and docs to use vo.value to actually get the value

Fix some docs and example errors

---

site/docs-md/apis/geolocation/index.md

Did not match actual code: https://github.com/ionic-team/capacitor/blob/19ed80532d68856c89101c8e08bd4a6c421ec1c6/core/src/web/geolocation.ts#L39

Fixed order of watchPosition parameters

---

android/capacitor/src/main/java/com/getcapacitor/CapacitorWebview.java
android/capacitor/src/main/res/layout/bridge_layout_main.xml

Closes https://github.com/ionic-team/capacitor/issues/371

Capturing keypresses in Android

---

cli/src/cordova.ts

Install dependencies if it has an url
Also check for dependencies inside platform tags
And also compare the plugin id with the plugin.xml id, in case it's different from the npm one to make sure it's installed and not enter in an infinite loop because of the different ids
Closes #381

Handle Cordova plugin dependencies with url

---

.github/CONTRIBUTING.md
cli/README.md
example/README.md

multiple typo fixes in documentations

Documentation improvements

---

electron/index.js

this option was not pushed before the merge, my bad

Fix autoHideLaunchSplash option in Electron SplashScreen

---

android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/CameraSettings.java

Handle allowEditing for Android

---

electron/src/electron/toast.ts
electron/src/plugins.ts

Electron toast plugin

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Network.java

Network plugin needs ACCESS_NETWORK_STATE permission, if not present in AndroidManifest.xml the app crash at startup when the NETWORK_CHANGE_EVENT is configured.
Make it log an error message and also make getStatus return an error when the permission is not configured.

Handle no network permissions

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java

Make handleRequestPermissionsResult return an error when some of the requested permission is not present in the AndroidManifest.xml
Added some functions that can be useful for plugins when checking permissions

Handle no permissions set when requested

---

cli/src/android/update.ts
cli/src/common.ts
cli/src/cordova.ts

Write edit-config and config-file tag content into the capacitor-andorid-plugins module's AndroidManifest.xml so manifest merger does the job for us

Write edit-config and config-file tag content into AndroidManifest.xml

---

example/android/app/src/main/AndroidManifest.xml

Add vibration permission to sample app so vibration button works

Add vibration permission

---

ios-template/App/Podfile

Related to Josh issue, update the paths in the template

Update Capacitor path in template

---

android-template/gradle/wrapper/gradle-wrapper.properties

When I updated the gradle plugin and SDK I missed to update the gradle distribution url

Update gradle version on template

---

capacitor-android-plugins/build.gradle

Update gradle plugin and target SDK for capacitor-android-plugins

---

cli/src/android/update.ts
cli/src/plugin.ts

Josh commented on slack that facebook plugin was using $ANDROID_SDK_VERSION instead of a value and the problem was they moved the preferences to the root of plugin.xml and I was only checking them inside the platform element.
This change checks both

Also check preferences in the root of plugin.xml

---

ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/CapacitorCordova.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/NSDictionary+CordovaPreferences.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/NSDictionary+CordovaPreferences.m

This allows the app to build when using ionic keyboard plugin or any other plugin importing NSDictionary+CordovaPreferences.h class

Add NSDictionary+CordovaPreferences.h class

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Podfile.lock
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m

Set plugin VC before calling pluginInitialize so in case the plugin needs to access it, it's available.

Set plugin VC before calling pluginInitialize

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
site/docs-md/basics/configuring-your-app.md
site/src/assets/docs-content/basics/configuring-your-app.html

Adds `allowMixedContent` configuration to allow loading mixed content
Closes #477

Allow mixed content

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m

Closes #510
Also initializes the plugin webView and commandDelegate before calling pluginInitialize so they can be used from the beginning

Initialize startup plugins when the app initializes

---

.gitignore
electron/package-lock.json
electron/src/electron/clipboard.ts
electron/src/plugins.ts
example/README.md
example/package.json

Fixed some TS errors when building the @capacitor/electron package and solved getting an undefined value when pasting from the clipboard in the example.

Electron Clipboard Improvements  

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/Plugins/Keyboard.m

Added keyboardWillHide, keyboardDidHide, keyboardWillShow and keyboardDidShow event firing on the iOS keyboard plugin
Also added a few functions to the bridge to help firing events.

Added iOS keyboard events

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Keyboard.java

Added keyboardWillHide, keyboardDidHide, keyboardWillShow and keyboardDidShow event firing on the iOS keyboard plugin
Also added a few functions to the bridge to help firing events.

Added Android keyboard events

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Fix focus on 11.3 and the crash on previous versions

---

core/package-lock.json
core/package.json
core/src/web-plugins.ts
core/src/web/toast.ts

Add web toast

---

site/docs-md/apis/geolocation/index.md

Added a missing semicolon in the docs.

Added missing semicolon

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Make CAPBridgeViewController public

---

core/src/definitions.ts

Add isPluginAvailable to Capacitor definitions

---

core/src/web/device.ts

Closes #601
Also improve other results as osVersion on iOS 10 and Mac OS, and Firefox and Windows results

Improve user agent parsing

---

site/docs-md/plugins/android.md
site/docs-md/plugins/ios.md

Advanced plugins docs

---

cli/src/android/add.ts
cli/src/android/common.ts
cli/src/android/update.ts
cli/src/config.ts
cli/src/cordova.ts
cli/src/electron/add.ts
cli/src/electron/copy.ts
cli/src/index.ts
cli/src/ios/update.ts
cli/src/plugin.ts
cli/src/tasks/add.ts
cli/src/tasks/copy.ts
cli/src/tasks/create.ts
cli/src/tasks/init.ts
cli/src/tasks/new-plugin.ts
cli/src/tasks/open.ts
cli/src/tasks/serve.ts
cli/src/tasks/update.ts
cli/src/util/http.ts
cli/src/web/copy.ts
cli/src/web/serve.ts

Now that code removes the color from unused imports, I spotted all those and removed them

remove unused imports

---

cli/package-lock.json
cli/package.json
cli/src/cordova.ts

Improve the logs when the plugin needs to add strings to existing arrays

Improve the logs for missing string in plist arrays

---

cli/test/add.android.spec.ts
cli/test/add.ios.spec.ts
cli/test/create.spec.ts
cli/test/init.spec.ts
cli/test/update.android.spec.ts
cli/test/update.ios.spec.ts
cli/test/util.ts

We had most of the CLI tests broken, fixed them and improved a little.

Fix CLI tests

---

example/src/pages/local-notifications/local-notifications.ts

face.jpg file doesn't exist, so the notification fails to create, changed it with ionitron image.

Update example icon

---

core/src/core-plugin-definitions.ts
ios-template/App/App/AppDelegate.swift
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPNotifications.swift
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift

Moved part of the LocalNotifications code to a common class as both Push and Local are handled by UNUserNotificationCenter

Push notifications ios

---

ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

Remove duplicated day entry

---

android/capacitor/build.gradle
android/capacitor/src/main/AndroidManifest.xml
android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/CapacitorFirebaseMessagingService.java
android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts

Those are the core and capacitor android required changes for push.
Still missing some required template changes, will do them in a separate PR.
Only send to JS the Data portion from the push notification payload

Android push notifications

---

cli/src/cordova.ts

When the plugin.xml and the package.json plugin id are different, the plugin.xml id is used

Use plugin.xml plugin id instead of package.json one

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Allow iframe navigation inside the app instead of opening outside

Allow iframe navigation

---

site/docs-md/apis/background-task/index.md

Docs are wrong, the plugins use `addListener ` and not `addEventListener`

App uses addListener, not addEventListener

---

cli/src/cordova.ts

Handle when a plugin `<js-module>` tag has a `<runs/>` tag.

Add runs module to cordova_plugins.js

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java
android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java

This code is needed to show a file chooser when an input with type file is clicked.
Used a fake CordovaPlugin and `cordovaInterface.startActivityForResult` to do the job because Capacitor's startActivityForResult will require a PluginCall and a Plugin to properly work and that's harder to fake.
Closes #631

Add input file functionality to Android webview

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
site/docs-md/basics/configuring-your-app.md

Document new Android preference `captureInput`
Move `allowMixedContent` preference inside Android as it's android specific.

Document android configs

---

android-template/gitignore

These are the added files when the public folder is ignored:
```
new file:   android/.gitignore
new file:   android/app/.npmignore
new file:   android/app/build.gradle
new file:   android/app/capacitor.build.gradle
new file:   android/app/proguard-rules.pro
new file:   android/app/src/androidTest/java/com/getcapacitor/myapp/ExampleInstrumentedTest.java
new file:   android/app/src/main/AndroidManifest.xml
new file:   android/app/src/main/assets/capacitor.config.json
new file:   android/app/src/main/java/com/example/app/MainActivity.java
new file:   android/app/src/main/res/drawable-land-hdpi/splash.png
new file:   android/app/src/main/res/drawable-land-ldpi/splash.png
new file:   android/app/src/main/res/drawable-land-mdpi/splash.png
new file: …
```

Ignore Android public web asset folder

---

core/native-bridge.js
core/src/core-plugin-definitions.ts

Add typescript definitions for WebView plugin and a window.Ionic.WebView wrapper for Capacitor.Plugins.WebView

Webview definitions

---

android/capacitor/src/main/java/com/getcapacitor/AndroidProtocolHandler.java
android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
android/capacitor/src/main/java/com/getcapacitor/plugin/WebView.java

Android implementation of WebView plugin with getServerBasePath and setServerBasePath methods.
Couldn't properly test as we don't have an easy way of having a different folder where to point it, but the code is almost the same as for the cordova-plugin-ionic-webview

WebView plugin implementation for Android

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/JSInjector.java
core/native-bridge.js
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/JSExport.swift

Implement convertFileSrc function for iOS and Android.
Closes #467 
Also closes #448 as it finish with the work started on https://github.com/ionic-team/capacitor/pull/731, https://github.com/ionic-team/capacitor/pull/727 and https://github.com/ionic-team/capacitor/pull/721

Implement convertFileSrc

---

site/docs-md/basics/configuring-your-app.md

We never documented this two preferences
Closes #734

Document cordovaSwiftVersion and minVersion for iOS

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

Fix input file cancel crash

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/plugin/WebView.java
core/native-bridge.js
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/WebView.swift

It's the equivalent of https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/147 for Capacitor

Add persistServerBasePath function to WebView plugin

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift

So we are reading the server port and url config values before they are available, so port configuration and live reload won't work.

Read server url and port when config is available

---

site/docs-md/android/updating.md

Since we update with npm now, the updating docs are out of date.

Update updating instructions for Android

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Haptics.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Keyboard.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Photos.java
android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java

Added unavailable and unimplemented methods to PluginCall. It will reject with "not available" or "not implemented" error message
Changed all plugins to call unimplemented on unimplemented methods or unavailable when the method is implemented but not available for a certain Android version.

Add unavailable and unimplemented methods to PluginCall

---

ios/Capacitor/Capacitor/CAPPluginCall.swift
ios/Capacitor/Capacitor/Plugins/App.swift
ios/Capacitor/Capacitor/Plugins/Browser.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift
ios/Capacitor/Capacitor/Plugins/StatusBar.swift

Added unimplemented method to CAPPluginCall and made unimplemented methods call it instead of success

Add unimplemented method to CAPPluginCall

---

core/src/core-plugin-definitions.ts

fix(): filesystem utf16 encoding typo

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Needed for video files to properly work on video tags
Equivalent of https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/154 for Capacitor

Allow range requests for local files

---

core/src/definitions.ts

To make them compile on strict mode.
Closes #781

Make addLister and removeListener use method signature

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java
android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java

On Android 6+ you have to manually ask for the permissions, so this will ask for them when using getUserMedia
Closes #802

Request native permissions needed for getUserMedia

---

site/docs-md/apis/local-notifications/index.md
site/docs-md/apis/push-notifications/index.md
site/src/components/site-menu/site-menu.tsx

For now just list the Push Notifications plugin and shows the API, will add examples and possible instructions in the future.

List Push Notification docs

---

cli/src/android/update.ts
cli/src/common.ts
cli/src/ios/update.ts

Just in case the user updates the CLI and forgets to update the platform.

Show info message if platform version is smaller than CLI version

---

cli/src/tasks/add.ts

Don't add the project if the web dir doesn't exist.

Check for web dir before adding project

---

cli/src/common.ts

The link changed and it's not updated on the error message

Fix link to configuration section

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Please see #826 for details.
BR, Michael
If there is any reason why the favicon.ico should be loaded please let me know.

Android: Handle WebView '/favicon.ico' requests

---

core/src/web-plugins.ts

Export Motion plugin

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

Fixes a build error introduced in my previous PR (#876)

fix build error caused by #876

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Geolocation.java

Return error message instead of empty location

---

ios/Capacitor/Capacitor/Plugins/Clipboard.swift

Fix iOS clipboard

---

ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
ios/CapacitorCordova/CapacitorCordova/CapacitorCordova.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVURLProtocol.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVURLProtocol.m

Add CDVURLProtocol classes for better plugin compat

---

site/docs-md/apis/local-notifications/index.md

Add example for LocalNotifications

---

cli/package-lock.json
cli/package.json

Update inquirer as seems to have problems when prompting multiple questions on windows & node 10+
Closes #893

Fix node 10 prompt problems

---

electron/index.js

Added customHtml splash option to get a string with the html content to let users full customization.

Custom html support electron splash screen

---

site/docs-md/apis/push-notifications/index.md

Documenting Push Notifications icon on Android.

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Android: Fix request headers when proxying

---

cli/src/cordova.ts

Avoid update failure if config-file entry doesn't have target

---

cli/src/android/update.ts

fix(cli): rewrite Gradle path separators on Windows (#992)

---

cli/src/cordova.ts

Related to https://github.com/ionic-team/capacitor/pull/986
There is another place where the target is checked and I missed it

Check for empty target

---

cli/test/add.ios.spec.ts

On my machine they are still failing, increasing the timeout fixes the problem.

Increase iOS tests timeout

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

Add style to Keyboard plugin as configuration option

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

Prompt for Camera permission before using it

---

android/capacitor/src/main/java/com/getcapacitor/AndroidProtocolHandler.java
android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/FileUtils.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
core/native-bridge.js

Changed the local server to load from `capacitor://` scheme instead of https
Also added `capacitor-asset` for handling `file://` urls and `capacitor-content` to handle `content://` urls

Use capacitor:// scheme for Android

---

ios/Capacitor/Capacitor/Plugins/Filesystem.swift

Before writing, check that data is not empty
Closes #1042

Check that data is not empty

---

ios/Capacitor/Capacitor/CAPAssetHandler.swift
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPFile.swift

Also changed `capacitor-asset` to `capacitor-file` and made both schemes constants for easier changes.

Make hostName configurable on iOS

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Based on https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/217
Return 404 instead of 200 when file is not found.

Return 404 error when file is not found

---

cli/src/android/common.ts

Escape apostrophe char for strings.xml

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

I've put inside ios configurations
```
"ios": {
"scrollEnabled": false
}
```
Closes #1055

Add scrollEnabled configuration option

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
ios/Capacitor/Capacitor/CAPBridge.swift
site/docs-md/basics/configuring-your-app.md

renamed `hostName` preference to `hostname`
made `localhost` as default hostname value
made `allowMixedContent` false as default as it's not needed when using http

Use localhost as default hostname

---

android/capacitor/src/main/java/com/getcapacitor/plugin/StatusBar.java

Fixes https://github.com/ionic-team/capacitor/issues/1086

Android: make StatusBar.show compatible with StatusBar.setStyle

---

cli/src/ios/update.ts

Also check for existing dependencies to not duplicate them.
Closes #1072

Don't add dependency spec if empty

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Fix capacitor scheme files not loading on live reload

---

android/capacitor/src/main/java/com/getcapacitor/JSInjector.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

The fix for injecting the Capacitor js code inside head tag was only implemented for one case, this injects it for all the cases.
Closes #1103

Properly inject Capacitor js code inside head

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Allows media with autoplay property to autoplay
Also allows media without autoplay to be played from javascript without requiring user interaction
Closes #1081

Allow media autoplay

---

core/native-bridge.js

Fix useless logging to native (leading to performance issue in some apps) https://github.com/ionic-team/capacitor/issues/1107

Fix issue 1107

---

core/native-bridge.js
site/docs-md/apis/console/index.md

Also add console.trace to the allowed.

Document which console functions are supported

---

site/docs-md/apis/keyboard/index.md

Documenting the new "resize" configuration option, and also the "style" one as it wasn't documented when included.

Add docs for Keyboard configurations

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

Fix android filesystem getUri

---

android/capacitor/src/main/java/com/getcapacitor/plugin/StatusBar.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/StatusBar.swift

Gets the current state of the Status Bar including style, visibility, and color (Android only).

Add getInfo method to Status Bar plugin

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java

Fix LocalNotification areEnabled return value

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Properly handle requests with Range header and return appropriate headers so audio and video tags
work correctly and you can go forward or backward on them

Handle Range request header for better multimedia file handling

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/custom.md

Update issue templates

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

Potential fix for https://github.com/ionic-team/capacitor/issues/632

Update Keyboard.m fixing hide() issue

---

cli/src/cordova.ts

If public folder doesn't exists in update command, copy it. 
Closes #1197

Copy public folder in update command if doesn't exist

---

README.md

Add 2019 section in Roadmap linking Ionic blog entry about it

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift

This standardizes the data passed with the pushNotificationReceived and pushNotificationActionPerformed events to be title, body, and data. It also adds platform specific data that may be useful for some applications.

Standardize data passed to pushNotificationReceived and pushNotificationActionPerformed events

---

ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift

only show alert for LocalNotifications

---

ios/Capacitor/Capacitor/CAPPluginCall.swift

Remove warnings about public being redundant and a build error with the static var.

Fix warnings and errors on Xcode 10.2

---

site/package-lock.json
site/package.json
site/src/assets/docs-content/apis/background-task/index.html
site/src/assets/docs-content/basics/configuring-your-app.html

Update stencil router and build latest docs

---

cli/src/cordova.ts

Wait for file writing to avoid messing up files on sync and add commands 
Closes #1247

await for all js file writing

---

core/scripts/docs.js
core/src/core-plugin-definitions.ts
site/src/assets/docs-content/apis/accessibility/api.html
site/src/assets/docs-content/apis/background-task/api.html
site/src/assets/docs-content/apis/camera/api.html
site/src/assets/docs-content/apis/filesystem/api.html
site/src/assets/docs-content/apis/geolocation/api.html
site/src/assets/docs-content/apis/haptics/api.html
site/src/assets/docs-content/apis/local-notifications/api.html
site/src/assets/docs-content/apis/modals/api.html
site/src/assets/docs-content/apis/motion/api.html
site/src/assets/docs-content/apis/network/api.html
site/src/assets/docs-content/apis/photos/api.html
site/src/assets/docs-content/apis/push-notifications/api.html
site/src/assets/docs-content/apis/share/api.html
site/src/assets/docs-content/apis/splash-screen/api.html
site/src/assets/docs-content/apis/splash-screen/index.html
site/src/assets/docs-content/apis/status-bar/api-index.html
site/src/assets/docs-content/apis/status-bar/api.html
site/src/assets/docs-content/apis/toast/api.html
site/src/assets/docs-content/apis/web-view/api.html

Make Plugin enums appear on docs

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

Also improved the permission behaviour when using prompt option as now it ask based on the option you choose (meaning, won't ask for camera and external permissions if you choose photos instead of camera)
Closes #1254

Add external storage permission to make exif work

---

core/package-lock.json
core/package.json

Remove lodash as is not used

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java

Adds browserPageLoaded implementation for Android.
Also returns a promise on open function that was missing.

Implement browserPageLoaded for Android

---

cli/src/index.ts

Closes #1287 
Shows up help and a suitable message if the user provides an unknown command.

Warns the user for providing unknown commands

---

site/docs-md/basics/opening-native-projects.md
site/docs-md/getting-started/dependencies.md
site/docs-md/ios/index.md

After the Swift 4.2 update, it's required to use Xcode 10

Update Xcode version required in docs

---

site/docs-md/apis/push-notifications/index.md

Document google-services.json file

---

cli/package-lock.json
cli/package.json
cli/src/web/serve.ts

Remove stencil-dev-server and use @stencil/core instead

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

Enable window.open for Android

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

[Android] Only show app url toasts on debug builds

---

ios/Capacitor/Capacitor/Plugins/Browser.swift

Set SafariVC to nil on finish event to release it

---

site/docs-md/community/plugins.md

Added the Firebase Authentication Plugin working in Android and iOS with Google, Facebook and Twitter providers.

A new plugin under authentication section (Update plugins.md)

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java

Closes: https://github.com/ionic-team/capacitor/issues/1308

[Android] Set lockscreen visibility on notification channel

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java

Solves this: https://github.com/ionic-team/capacitor/issues/1217

[Android] implement removeAllDeliveredNotifications

---

android-template/app/build.gradle
android/capacitor/build.gradle

On both template and capacitor

Update firebase-messaging to latest

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/java/com/getcapacitor/plugin/App.java

Fix app open url

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java

And only notify listeners if the local notification was not null

Only handle local notifications if the action is Main

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

The method signature changed again

Fix autofocus for iOS 12.2

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

It was being handled only for assets, but not for local files
Closes #1343

Handle range requests also for local files

---

android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

Implement loadUrl for cordova plugins compat

---

ios/Capacitor/Capacitor/Plugins/PushNotifications.swift

Make removeAllDeliveredNotifications remove the badge number

---

ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift
site/docs-md/apis/push-notifications/index.md

Make foreground push notification appearance configurable

---

cli/package-lock.json
cli/package.json

move @types/tar to devDependencies

---

android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

Send cordova pause and resume events for better compat

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Haptics.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/Haptics.swift

According to the iOS Feedback's specification (https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/feedback/), I've added a notification type feedback that has not been implemented yet.
@jcesarmobile

Added notification haptics (iOS)

---

android/capacitor/src/main/java/com/getcapacitor/FileUtils.java

Fix IllegalArgumentException on Camera Plugin when using `allowEditing: true` and using some app like QuickPic instead of default Photos app for doing the editing.
Closes #937

Fix IllegalArgumentException on Camera photo edition

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Network.java

fixed small typo on JavaDoc header of getNormalizedTypeName

Network.java typo

---

core/src/web/camera.ts

Only return the type specified in CameraOptions
Add support for dataUrl
Fix base64String to just return the base64 string instead of the data url
Make webPath return a blob url instead of data url
Return format based on the blob type instead of being hardcoded to jpeg

Proper returns for web Camera plugin

---

android/capacitor/src/main/java/com/getcapacitor/FileUtils.java

Create image copy from InputStream if path is null

---

ios/Capacitor/Capacitor/Plugins/Filesystem.swift

Append wasn't handling the write without encoding, it was only writing as regular file instead of as base64 data. 
Closes #1051

Fix append without encoding for iOS

---

electron/package-lock.json
electron/src/electron/device.ts
electron/src/plugins.ts

Get info from Device web plugin, but change platform to electron

Implementation of Device plugin for Electron

---

site/docs-md/apis/camera/index.md
site/src/assets/docs-content/apis/camera/index.html

- Update Angular code example - remove unnecessary code
- Add link to Ionic Angular camera guide
- Mention that for Android, CAMERA permission is actually not required (via Julio), so as to avoid confusion.
- Small formatting changes

[Docs] Camera API docs refresh

---

core/src/core-plugin-definitions.ts
core/src/definitions.ts
example/package-lock.json
plugin-template/package-lock.json
plugin-template/src/definitions.ts
site/docs-md/plugins/index.md

fix(types): avoid global types

---

package.json
scripts/deploy/package.json.template
scripts/generate.sh
scripts/setversion.sh

Set the version of the .podspec files after lerna has changed the version and not before
Closes #1218

Fix the release script setting a previous version for iOS

---

example/package-lock.json
example/package.json
example/src/pages/clipboard/clipboard.ts
example/www/index.html

Fix build with latest @capacitor/core by updating typescript and @ionic/app-scripts

Update typescript in example app

---

site/src/assets/docs-content/plugins/index.html

* Removed and replaced iOS screenshot at the end of the Firebase Push guide; also checked case (`PNG` to `png`)
* Re-ran `npm i` and `npm run dev` (PR includes minor changes to `index.html`)

(fix)guide: Fixing iOS screenshot on Firebase guide

---

android-template/app/app.iml
android-template/app/build.gradle
android/capacitor/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
capacitor-cordova-android-plugins/build.gradle
example/android/app/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
plugin-template/android/gradle/wrapper/gradle-wrapper.properties
plugin-template/android/plugin/build.gradle
site/docs-md/guides/push-notifications-firebase.md
site/src/assets/docs-content/guides/push-notifications-firebase.html

Update support libraries to 28.0.0 and fcm messaging to 18 and a few others to latest

Update Android dependencies to latest

---

plugin-template/src/definitions.ts
site/src/assets/docs-content/plugins/index.html

Also update the plugin template to not be undefined

---

site/docs-md/android/updating.md
site/docs-md/apis/push-notifications/index.md
site/docs-md/apis/splash-screen/index.md
site/docs-md/basics/using-plugins.md
site/docs-md/electron/index.md
site/docs-md/getting-started/index.md
site/docs-md/getting-started/pwa-elements.md
site/docs-md/getting-started/with-ionic.md
site/docs-md/plugins/index.md
site/src/assets/docs-content/android/updating.html
site/src/assets/docs-content/apis/push-notifications/index.html
site/src/assets/docs-content/apis/splash-screen/index.html
site/src/assets/docs-content/basics/using-plugins.html
site/src/assets/docs-content/electron/index.html
site/src/assets/docs-content/getting-started/index.html
site/src/assets/docs-content/getting-started/pwa-elements.html
site/src/assets/docs-content/getting-started/with-ionic.html
site/src/assets/docs-content/plugins/index.html

- Adding language to any code blocks that were missing an alias

(fix) Adding missing language to code blocks

---

site/docs-md/plugins/index.md
site/src/assets/docs-content/plugins/index.html

- Cleaning up the Plugin Introduction section
- Removing the reference to Max's machine :D

(docs)update: Minor formatting update to Plugin Introduction page

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Keyboard.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Keyboard.m

Add listeners on Keyboard plugins for it's events
Closes #1466

Add keyboard events

---

cli/src/cordova.ts

To avoid clobbers overwriting existing ones that contain them.
Closes #1523

Order cordova plugins by clobber name

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDV.h

So plugins using it don't fail to build
Closes #1531

expose CDVScreenOrientationDelegate

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

Free saved call after File plugin permission result

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Storage.java

fix(android): Make Storage.clear() return promise

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

fix(android): Make proxy only inject Capacitor to html mime type files

---

cli/src/android/update.ts

fix(cli): consider empty target/file in config-file/edit-config tags

---

core/package.json

As it causes problems with webpack.

fix(core): Remove browser from package.json

---

electron/src/electron/filesystem.ts
site/docs-md/community/plugins.md

Update to make rmdir work like mkdir

fix(electron): Filesystem.rmdir not using directory

---

core/native-bridge.js

Fix(core): Avoid prompting empty error if null

---

android-template/gitignore

Update the file according to latest https://github.com/github/gitignore/blob/master/Android.gitignore

Update gitignore file in android-template

---

site/docs-md/plugins/android.md

Docs: Remove iOS info from Android Plugin docs

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.m

fix(cordova): Add CDVHandleOpenURLWithAppSourceAndAnnotationNotification

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVViewController.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVViewController.m

Just define it to make projects build, but won't work
Closes #961

fix(cordova): Define pluginObjects in CDVViewController

---

cli/src/electron/open.ts
cli/src/tasks/open.ts
site/docs-md/electron/index.md

Instead of [error] Platform electron is not valid.

Fix(electron): make npx cap open electron run electron app

---

electron-template/index.js

edit electron template to not use the injectCapacitor method, but use preload option instead.

chore(electron): update electron template to not use injectCapacitor

---

android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

fix(cordova): implement getUrl method

---

cli/package-lock.json
cli/package.json

fix(cli): prevent npx cap init from blocking

---

site/docs-md/guides/community.md

Add new tutorials from my blog "akhromieiev.com"

docs: Add new community tutorials

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Share.java

fix(android): resolve share call

---

core/native-bridge.js
core/src/definitions.ts

And also in the types
Closes #1759

fix(android/ios): expose getPlatform method in Capacitor object

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

I had to rearrange the code to accommodate the issue with removing the spinner bar from the view. Instead I am setting the visibility now and only remove it when the app is paused/destroyed.

fix(android): splash spinner bar not properly handled in view

---

site/docs-md/community/plugins.md

Add entry for cap-bluetooth-low-energy-client

docs: add cap-bluetooth-low-energy-client

---

cli/src/android/update.ts

fix(cli): properly handle edit-config tag target

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

fix(android): remove new line characters from camera base64 results

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

fix(ios): only listen for keyboard events when the app is active

---

android/capacitor/src/main/java/com/getcapacitor/plugin/App.java

Also return the result.
Closes #1902

fix(android): make openUrl open apps that don't handle VIEW intents

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVUserAgentUtil.m

fix(ios/cordova): Replace UIWebView with WKWebView in CDVUserAgentUtil

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/Plugins/StatusBar.swift

fix(ios): make StatusBar Light style work on Dark mode

---

site/docs-md/cordova/known-incompatible-plugins.md

docs: add reasoning for cordova plugin incompatibility

---

site/docs-md/guides/community.md

Added resource for capacitor music playback

docs(ce-guides): Add tutorial for capacitor music playback

---

site/docs-md/community/plugins.md

Hi guys I just added capacitor camera preview plugin to community plugin list.

docs(ce-plugins): add capacitor-camera-preview

---

cli/src/cordova.ts

Add some more plugins that cause conflicts with the capacitor equivalents

fix(cli): skip incompatible enterprise plugins

---

site/docs-md/community/plugins.md

Added capacitor-biometric-auth to community plugins documentation

docs(ce-plugins): add capacitor-biometric-auth

---

site/docs-md/android/custom-code.md
site/docs-md/guides/community.md

- Android custom code guide modified. 
> I was stuck on that the other day and I've solved it. And today I saw this article again and decide to modify it.
I think it's now better for common users to comprehend.
- Some style changes.

docs: improve Android custom code section

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java
ios/Capacitor/Capacitor/Plugins/Browser.swift

fix(Browser): avoid crash when using invalid urls

---

site/docs-md/guides/community.md

Add tutorial for Google and Twitter Login

docs(ce-guides): add tutorials for Google and Twitter Login

---

ios/Capacitor/Capacitor/Plugins/Modals.swift

fix(ios/Modals): Don't success until dismissed 

---

ios/Capacitor/Capacitor/CAPPlugin.m

fix(ios): event listener is not retained if was removed and added again

---

site/docs-md/basics/workflow.md

The Periodic Maintenance section looks confusing to me, it sounds like the project gets borked or something, and also says update command updates dependencies, which it doesn't. 
So renaming the section and rewording a little to not mislead.

docs: reword the Periodic Maintenance section

---

package-lock.json
package.json

it's not being used, so removing the dependency and changelog entry from root package.json

chore(deps): remove unused lerna-changelog

---

core/package-lock.json
core/package.json
core/src/core-plugin-definitions.ts
core/src/definitions.ts
core/src/util.ts
core/src/web-runtime.ts
core/src/web/app.ts
core/src/web/browser.ts
core/src/web/camera.ts
core/src/web/clipboard.ts
core/src/web/device.ts
core/src/web/local-notifications.ts
core/src/web/motion.ts
core/src/web/network.ts
core/src/web/share.ts
core/src/web/storage.ts

core had tslint installed and configured but was missing a script to use it.
Added the script and fixed the reported issues.

chore(core): Add lint script and fix lint issues

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.m

Post `CDVPluginHandleOpenURLNotification` with the url that triggered it so cordova plugins depending on it can listen and to their things

fix(cordova/ios): post CDVPluginHandleOpenURLNotification

---

site/docs-md/community/plugins.md

Added capacitor-stripe-terminal! 🎉🎉🎉
P.S. 
I also created a nice Capacitor plugin search page! Although, it needs a little more work (e.g. official plugins and sorting). 
https://capacitor-search.eventone.page

docs(ce-plugins): Add capacitor-stripe-terminal

---

site/docs-md/community/plugins.md

Added capacitor-keep-screen-on to community plugin list.

docs(ce-plugins): add capacitor-keep-screen-on

---

android/capacitor/src/main/java/com/getcapacitor/plugin/App.java

fix(android): Ensure appStateChange doesn't fire on startup

---

site/docs-md/community/plugins.md

Plugin for accessing device internal sensors

docs(ce-plugins): add cap-sensing-kit

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java
core/src/core-plugin-definitions.ts
core/src/web/device.ts
electron/src/electron/device.ts
ios/Capacitor/Capacitor/Plugins/Device.swift
site/docs-md/apis/device/index.md
site/src/assets/docs-content/apis/device/api.html

- Updateed the Documnetation to show possible return values.
- When calling device.getInfo(), platform returns 'web' when using the mobile browser on iOS or Android. However, I expect to get the actual platform.

feat(device): Add operatingSystem field

---

cli/src/ios/update.ts

It adds all compiler flags to all plugin files
Closes #1498

feat(cli/cordova): add support for source-file compiler-flags attribute

---

site/docs-md/android/updating.md
site/docs-md/electron/updating.md
site/docs-md/ios/updating.md

Add some recommended changes in users project for 1.4.0 release

docs(updating): add 1.4.0 recommended changes

---

site/docs-md/apis/keyboard/index.md

docs(keyboard): Add Keyboard config info

---

cli/package-lock.json
cli/package.json
cli/src/tasks/new-plugin.ts

Fixes https://github.com/ionic-team/capacitor/issues/2258

fix(cli): use rimraf instead of rm -rf

---

core/package-lock.json
core/scripts/docs.js

docs(core): show array type instead of any

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginResult.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginResult.m

fix(cordova): add new iOS Swift CDVCommandStatus enums

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVViewController.h

fix(cordova): avoid build failure if plugin uses viewController.webView

---

site/docs-md/community/plugins.md

Now **capacitor-admob** support iOS and Android Platform.

docs(ce-plugins): Update capacitor-admob plugin note

---

cli/src/android/open.ts

fix(cli): linux not showing error message on open

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Share.java

fix(android): make Share properly share file urls

---

site/docs-md/community/plugins.md

I created plugin code-scanner. Thanks.

docs(ce-plugins): add @rdlabo/capacitor-codescanner

---

site/docs-md/android/index.md

docs(android-guide): fix typo 

---

site/docs-md/community/plugins.md

Added voice recording plugin for ios and android

docs(ce-plugins): add capacitor-voice-recorder

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Toast.java
core/src/core-plugin-definitions.ts
core/src/web/toast.ts
example/src/pages/toast/toast.html
example/src/pages/toast/toast.ts
ios/Capacitor/Capacitor/Plugins/Toast.swift

Implements feature request #1621 
It can be one of 3 positions: 'top', 'center' or 'bottom' (the default).
closes #1621

feat(ios/android): allow to position Toast

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts

Hi,
i simply add the support of custom sound on notifications channels.

feat(android): add support to custom sound on Push Notifications

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

for notification grouping
closes https://github.com/ionic-team/capacitor/pull/2389

feat(ios): add threadIdentifier and summaryArgument to LocalNotification

---

cli/src/android/update.ts
cli/src/config.ts
cli/src/cordova.ts
cli/src/definitions.ts
cli/src/tasks/copy.ts

closes https://github.com/ionic-team/capacitor/pull/2395
closes https://github.com/ionic-team/capacitor/pull/2224

feat(cli): allow to modify cleartext setting from capacitor.config.json

---

android/capacitor/build.gradle
android/capacitor/src/main/java/com/getcapacitor/plugin/Geolocation.java
core/src/core-plugin-definitions.ts

Change Geolocation plugin to use Fused Location Provider
closes #379
closes #2186

feat(android): use Fused Location Provider on Geolocation plugin

---

android-template/build.gradle
android-template/gradle/wrapper/gradle-wrapper.properties
android/capacitor/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
capacitor-cordova-android-plugins/build.gradle
example/android/build.gradle
example/android/gradle/wrapper/gradle-wrapper.properties
plugin-template/android/build.gradle
plugin-template/android/gradle/wrapper/gradle-wrapper.properties

Since I didn't have permissions to push to #2156, I've sent a separate PR keeping the original commit but updating to newer versions
Closes #2156 
Closes #2148

feat(android): update gradle and dependencies

---

.circleci/config.yml
android-template/app/build.gradle
android/capacitor/build.gradle
capacitor-cordova-android-plugins/build.gradle
example/android/app/build.gradle
plugin-template/android/build.gradle

Set compileSdkVersion and targetSdkVersion to 29
Closes #2006

chore(android): target SDK version 29

---

cli/src/android/doctor.ts
cli/src/common.ts
cli/src/electron/doctor.ts
cli/src/ios/doctor.ts
cli/src/tasks/doctor.ts

Doctor was throwing an error if electron was present instead of checking if everything was ok.
This PR adds some logic in doctor for electron, like checking app folder, installed @capacitor/electron version or check if electron is installed
closes #2429

fix(doctor): add electron checks

---

android/capacitor/build.gradle
capacitor-cordova-android-plugins/build.gradle
plugin-template/android/build.gradle

fix(android): put google() on top of jcenter() in gradle files

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Podfile
ios/Capacitor/Podfile.lock

CocoaPods was complaining because of no having a platform present on the Podfile.
it also updates some project files

chore(ios): add platform to Podfile

---

Capacitor.podspec
cli/src/config.ts
ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
scripts/deploy/Capacitor.podspec.template

This updates the Capacitor project and the Swift version in the .podspec files

feat(ios): Update Capacitor project to Swift 5.0

---

site/docs-md/basics/configuring-your-app.md

Bumping the default cordovaSwiftVersion to 5.0

docs: update default cordovaSwiftVersion

---

android/capacitor/src/main/java/com/getcapacitor/Dialogs.java
ios/Capacitor/Capacitor/Plugins/Modals.swift

closes https://github.com/ionic-team/capacitor/issues/2339

fix(modals): make inputPlaceholder set a placeholder and not text

---

cli/src/cordova.ts

closes https://github.com/ionic-team/capacitor/issues/2440

fix(cli): properly merge non application config-file

---

.circleci/config.yml

run lint command as part of circleci tasks

chore(tests): run lint on circleci

---

example/electron/main.js
example/electron/package-lock.json
example/electron/package.json

remove deprecated injectCapacitor and make required changes so Capacitor continues working
update electron version

chore(example): update electron project to work with latest capacitor

---

electron-template/package.json

closes https://github.com/ionic-team/capacitor/issues/2488

chore(electron): update template to use latest electron

---

ios/Capacitor/Capacitor/Plugins/Modals.swift

ActionSheetOptionStyle.Cancel was not being used

fix(ios): make ActionSheetOptionStyle.Cancel show cancel button

---

site/docs-md/apis/local-notifications/index.md

should be local-notifications, not local-Notifications
closes https://github.com/ionic-team/capacitor/issues/2535

docs: fix Local Notifications url

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Device.swift

closes https://github.com/ionic-team/capacitor/issues/2130

feat(ios): add device name to Device.getInfo()

---

site/docs-md/apis/clipboard/index.md

Read option were removed, updating the sample to not use it

docs(clipboard): update read example removing options

---

electron/src/electron/device.ts

Added the missing app version in electron

fix(electron): Provide app version in Device.getInfo()

---

electron/src/electron/clipboard.ts

Remove ClipboardRead as was removed from core
Allow to copy/paste empty string
Fix image pasting

fix(electron): various clipboard fixes

---

site/docs-md/apis/filesystem/index.md

it now returns the file path, so log it in the example.

docs: update Filesystem.writeFile sample

---

site/docs-md/community/plugins.md

Following your advise i step back

docs(ce-plugins): Add SQLite, SQLite Storage and Video Player plugins

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java
core/src/core-plugin-definitions.ts
core/src/web/app.ts
core/src/web/index.ts
ios/Capacitor/Capacitor/CAPPlugin.h
ios/Capacitor/Capacitor/CAPPlugin.m
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m

implemented a removeAllListeners function for plugins so all listeners of that plugin can be removed at once (in case you lost the reference to them)
closes #2531

feat: implement removeAllListeners

---

site/docs-md/basics/configuring-your-app.md

docs(ios): Document hideLogs config option

---

cli/src/cordova.ts

fix(cli): prevent cordova dependency loop if plugin contains @

---

site/docs-md/apis/status-bar/index.md

Change `Statusbar` for `StatusBar`.

docs(StatusBar): Fix typo in setOverlaysWebView usage

---

plugin-template/android/build.gradle

not use '=' at targetSDK version.

fix(plugin-template): remove incorrect = from android gradle file

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java

fix(android): Avoid crash on schedule if LocalNotifications are disabled

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

closes https://github.com/ionic-team/capacitor/issues/2694

fix(android): input autofocus and javascript focus not working

---

cli/src/cordova.ts
cli/src/plugin.ts

asset tag was not being handled

fix(cordova): handle plugin.xml asset tag

---

ios/Capacitor/Capacitor/CAPAssetHandler.swift

fix(ios): allow access to extension-less files

---

site/docs-md/community/plugins.md

Edited community plugin page to show new plugin https://github.com/DTX-Elliot/capacitor-admob-advanced

docs(ce-plugins): Add capacitor-admob-advanced

---

site/docs-md/android/updating.md

The proper explanation is on the next line

docs(updating): Remove duplicate gradle sentence

---

core/src/core-plugin-definitions.ts

docs(browser): Updated information for close method

---

android/capacitor/src/main/java/com/getcapacitor/Dialogs.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/ui/ModalsBottomSheetDialogFragment.java

fix(android): call error on prompt cancel

---

android/capacitor/src/main/java/com/getcapacitor/JSArray.java

cherry picked from https://github.com/ionic-team/capacitor/pull/2869

feat(android): expose JSON string constructor for JSArray

---

site/docs-md/community/plugins.md

Add new community plugin. Thanks.

docs(ce-plugins): add capacitor-firebase-crashlytics

---

site/docs-md/community/plugins.md

Hi,
finally had the time to add Android Support to my Capacitor-Contacts Plugin.
Updated the docs as well. You can find a link to a working demo as well. 
As Contacts fetching is a commonly used native function (and i guess there will be more people creating Contact Plugins) I allowed myself to create a section.

docs(ce-plugins) add @byrds/capacitor-contacts plugin

---

site/docs-md/getting-started/dependencies.md

the comment says "Soon", but it's been available for a while

docs: Appflow is now available

---

core/src/web/filesystem.ts

closes https://github.com/ionic-team/capacitor/issues/2984

fix(web): #2984 Filesystem.appendFile

---

site/docs-md/apis/console/index.md

console docs mention that it's not possible, but it is now

docs: add information about disabling logs

---

ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift
ios/Capacitor/Capacitor/Plugins/Share.swift

chore(ios): correct plugin descriptions

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md

chore(github): important emoji fix

---

cli/src/tasks/doctor.ts

chore(cli): cleanup doctor output

---

README.md

It looks like there are new contributors in the `master` branch!
I've added the following wonderful people to `README.md`:
* imjacobclark
Have a great day!
Ionitron 💙

New contributors! 💖

---

cli/src/ios/update.ts

chore(cli): use real path to Capacitor iOS Pods

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeFragment.java

This ensures cleanup occurs on the BridgeFragment and attempts cleanup in the Bridge for the handler thread on destroy.

Memory cleanup improvements for the Bridge and BridgeFragment

---

cli/src/common.ts
cli/src/tasks/new-plugin.ts
plugin-template/gitignore

2.x version of https://github.com/ionic-team/capacitor/pull/3285

fix(cli): avoid npm gitignore rename on new plugins

---

.gitignore
ios/Capacitor/Podfile
ios/Capacitor/Podfile.lock
ios/package.json

chore(ci): run xcodebuild for Capacitor and CapacitorCordova

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

https://github.com/ionic-team/capacitor/pull/3328 for 1.x

fix(ios): only open a URL when the application is active

---

core/src/web/geolocation.ts
core/src/web/local-notifications.ts
core/src/web/splash-screen.ts

there is a new prettier version that wants the files like this

chore: new prettier format

---

cli/src/common.ts
cli/src/cordova.ts
cli/src/index.ts
cli/src/tasks/add.ts
cli/src/tasks/init.ts
cli/test/init.spec.ts

new `init` looks like this:
resolves https://github.com/ionic-team/capacitor/issues/3465

chore(cli): make `init` more informative

---

ios/Capacitor/Capacitor/JS.swift

chore(ios): Make JSObject and JSArray public

---

ios/Capacitor/Capacitor/CAPPlugin.m

fix(ios): iterate listeners to avoid "mutated while being enumerated"

---

core/src/core-plugin-definitions.ts

Fixing simple typo in documentation

Fix typo in pushNotificationActionPerformed documentation

---

core/src/index.ts

We need to export this so plugins can use it.

fix(core): export PermissionState

---

ios/Capacitor/Capacitor/Plugins/Geolocation.swift

Don't try to get the location when the permission status is `.notDetermined`, otherwise the failure delegate gets called before the user reacts to the permissions prompt.
closes https://github.com/ionic-team/capacitor/issues/3789

fix(ios): Don't get location if permission is not determined

---

cli/src/index.ts
cli/src/tasks/run.ts

chore(cli): add hidden --json option for run command

---

cli/src/cordova.ts

cordova-plugin-gelocation added a install variable on latest release that adds a variable in AndroidManifest.xml and it prevents Capacitor apps to build because it's not recognized.
This PR replaces the variable with the default value.

fix(cli/cordova): replace AndroidManifest.xml variables with default value

---

core/src/runtime.ts

React apps using react-refresh encounter this issue with our proxy.

fix(core): fix $$typeof() not implemented error

---

cli/src/config.ts
cli/src/definitions.ts
cli/src/ios/common.ts
cli/src/ios/open.ts
cli/src/ios/run.ts
cli/src/ios/update.ts

Additional config unification for xcodeproj and xcworkspace directories.
precursor to: https://github.com/ionic-team/capacitor/pull/4002

refactor(cli): move xcodeproj/xcworkspace to config

---

cli/bin/capacitor
cli/package.json

fixes https://github.com/ionic-team/capacitor/issues/4034

fix(cli): bump minimum node version to 12.4.0

---

android-template/build.gradle
android/capacitor/build.gradle
capacitor-cordova-android-plugins/build.gradle

chore(android): update gradle plugin

---

android-template/variables.gradle
android/capacitor/build.gradle
capacitor-cordova-android-plugins/build.gradle

While updating the plugins I noticed some dependencies had a double whitespace, so I searched here and also happened, so removing those extra whitespaces.

chore: Remove double whitespace on some gradle files

---

android-template/variables.gradle
android/capacitor/build.gradle

…sion gradle variables
as those were not configurable

feat(android): androidxActivityVersion & androidxFragmentVersion gradle variables

---

android/capacitor/build.gradle

looks like I missed some or forgot

chore(android): Update default version of gradle dependencies

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

Use the new Activity Result API in BridgeWebChromeClient instead of using Cordova plugins.
closes https://github.com/ionic-team/capacitor/issues/4159

refactor: Use the new Activity Result API in BridgeWebChromeClient

---

.github/workflows/ci.yml

Capacitor 3 is supposed to only support Xcode 12, so I've removed Xcode 11.7 and added 12.4

ci: Update Xcode versions

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Append user agent properly on iOS when "appendUserAgent" is used

---

.github/workflows/ci.yml

we are testing main instead of the actual PR

chore(ci): run tests on the actual PR

---

cli/src/tasks/create.ts

create command in capacitor 2 should install capacitor 2 dependencies instead of latest

fix(cli): Make create install capacitor 2

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

fix(ios): isNewBinary is true if defaults have no stored versions

---

capacitor-cordova-android-plugins/build.gradle

on cordova plugins project, it was not properly formed

fix(android): proper targetSdkVersion configuration on cordova plugins

---

cli/src/declarations.ts
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPInstanceConfiguration.h
ios/Capacitor/Capacitor/CAPInstanceConfiguration.m
ios/Capacitor/Capacitor/CAPInstanceDescriptor.h
ios/Capacitor/Capacitor/CAPInstanceDescriptor.m
ios/Capacitor/Capacitor/CAPInstanceDescriptor.swift

closes https://github.com/ionic-team/capacitor/issues/4721

feat(ios): Add limitsNavigationsToAppBoundDomains configuration option

---

android/capacitor/src/main/assets/native-bridge.js
ios/Capacitor/Capacitor/assets/native-bridge.js

fix(iOS/Android): rebuild native bridge on iOS and Android

Rebuild native-bridge.ts on for iOS and Android projects

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ExifWrapper.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ImageUtils.java

https://github.com/ionic-team/capacitor-plugins/pull/545 for Capacitor 2

fix(android): Properly reset orientation exif if corrected

---

cli/src/ios/update.ts

fix(cli): Separate Swift plugins from ObjC plugins

---

example/android/app/src/main/java/com/getcapacitor/myapp/SimpleFragmentActivity.java

closes https://github.com/ionic-team/capacitor/issues/4037

chore(example): Remove unused OnFragmentInteractionListener

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

Adds a method similar to `setServerAssetPath` and `setServerBasePath` that just reloads the app in the webview

feat(android): ability to reload the webview

---

cli/src/cordova.ts

closes https://github.com/ionic-team/capacitor/issues/5219

fix(cli): add cordova-plugin-google-analytics to static list

---

android-template/app/build.gradle

Warning mens that "something needs attention". Using `Google Services` are optional and absence `google-services.json` is a part of project configuration.

fix(android): Change logging level

---

cli/src/cordova.ts

If `Info.plist` is not found on the root, try to read `Base.lproj/Info.plist`, if not there neither, then log as possibly missing item.
closes https://github.com/ionic-team/capacitor/issues/5331

fix(cli): sync failing if Info.plist is localized

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java

closes https://github.com/ionic-team/capacitor/issues/5234

feat(android): Add getLong helper on PluginCall

---

ios/Capacitor/Capacitor/WebViewDelegationHandler.swift

closes https://github.com/ionic-team/capacitor/issues/5366

fix(ios): Reload webView on webViewWebContentProcessDidTerminate

---

android-template/variables.gradle

Addresses: WN-343 for android template

chore(android-template): bump min sdk android template

---

CHANGELOG.md
android/CHANGELOG.md
cli/CHANGELOG.md
core/CHANGELOG.md
ios/CHANGELOG.md
lerna.json
package.json

Changes I made for being able to publish the alpha 1 release and generated changelog

chore: Alpha.1 release changes

---

.github/workflows/ci.yml

removing in capacitor-4 branch too to fix the CI and unblock pending PRs

chore(ci): Remove unused action

---

core/cordova.js

To match current Cordova code
https://github.com/apache/cordova-ios/blob/a3a3936a549981054dabff8098dfa393094eb834/cordova-js-src/exec.js#L121-L123

fix(core): Make cordova bridge use Promise instead of setTimeout

---

android-template/app/src/main/res/values/styles.xml

For automatic theme change based on the user configured theme.

feat(android-template): use DayNight theme as default

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

remove titles for js alert, prompt and confirm dialogs
closes https://github.com/ionic-team/capacitor/issues/4738

chore(android): Remove js dialog titles

---

ios/Capacitor/Capacitor/WebViewAssetHandler.swift

Serve media files with ranges if the Range header is pressent

feat(ios): Support of range requests on WebViewAssetHandler

---

ios/Capacitor/Capacitor/CAPWebView.swift

feat(ios): Add overrideable router var for CAPWebView

---

ios/package.json

closes https://github.com/ionic-team/capacitor/issues/5798

fix(ios): publish Podfile script

---

android/package.json
ios/package.json
scripts/sync-peer-dependencies.mjs

next is the beta, use ^4.0.0
also uncomment the script that updates peer dependencies

chore(ios/android): update core peerDependency to ^4.0.0

---

cli/src/android/update.ts

Don't quote dependencies that start with "platform(" since those are BoM dependencies
closes https://github.com/ionic-team/capacitor/issues/5820

fix(cli): Support of BoM dependencies on cordova plugins

---

cli/package.json
package.json

to fix cli and core not building because of minipass types

chore: Update @types/tar dev dependency

---

cli/src/ios/update.ts

closes https://github.com/ionic-team/capacitor/issues/5494

fix(cli): Make update from windows use proper paths on Podfile

---

cli/src/cordova.ts

closes https://github.com/ionic-team/capacitor/issues/5755

fix(cli): Find the Info.plist when using scheme

---

cli/src/declarations.ts

closes https://github.com/ionic-team/capacitor/issues/5898

docs(cli): Improve information about minWebViewVersion and errorPath

---

cli/src/declarations.ts
cli/src/tasks/copy.ts

Backports https://github.com/ionic-team/capacitor/pull/5896 and https://github.com/ionic-team/capacitor/pull/5955 to 3.x

feat(cli): backports secure live updates support with portals for capacitor to 3.x

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Addresses: https://github.com/ionic-team/capacitor/issues/5947
This PR fixes an issue with local requests not being handled properly on native platforms (iOS/Android). As a result, fetching `IonIcons` or local assets could crash the app.

fix(http): fix local http requests on native platforms

---

android/capacitor/src/main/assets/native-bridge.js
android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java
core/native-bridge.ts
ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift
ios/Capacitor/Capacitor/WebViewDelegationHandler.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

Addresses: https://github.com/ionic-team/capacitor/issues/5950
This PR modifies `document.cookie` setter to be synchronous.

fix(cookies): make document.cookie setter synchronous

---

.github/ionic-issue-bot.yml

add issue bot for triaging and locking old issues

chore(ci): Add ionic-issue-bot

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorCookies.java
core/src/core-plugins.ts
ios/Capacitor/Capacitor/Plugins/CapacitorCookieManager.swift
ios/Capacitor/Capacitor/Plugins/CapacitorCookies.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m

Addresses: https://github.com/ionic-team/capacitor/issues/5944
This PR adds the `getCookies()` plugin method & returns cookies as a `key-value` map

feat(cookies): add get cookies plugin method

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/PluginHandle.java

feat(android): Adds support for registering already initialized instances of plugins to the bridge.

feat(android): Plugin Instance Support

---

android/capacitor/src/main/java/com/getcapacitor/MessageHandler.java

closes https://github.com/ionic-team/capacitor/issues/6002

fix(android): Don't run Cordova plugins on ui thread

---

.github/workflows/ci.yml
.github/workflows/publish-android.yml
.github/workflows/publish-ios.yml
.github/workflows/publish-npm-latest.yml

These updates will rid of warnings occurring in action runs.

chore: update actions in workflows

---

cli/src/android/run.ts
cli/src/definitions.ts

closes https://github.com/ionic-team/capacitor/issues/6083

fix(cli): flavor flag not using correct apk

---

cli/src/index.ts
cli/src/tasks/build.ts

fix(cli): config file android release type not overridden

---

README.md

Ref: https://github.com/badges/shields/issues/8671

chore(readme): fix CI status badge

---

cli/src/tasks/init.ts

Update default in Capacitor 5 to prepare for change from #6332 in Capacitor 6 or later.

feat(cli): update init to set androidScheme to https

---

cli/src/ios/build.ts

4.x port of PR #6371
Fixes: #6369 
(cherry picked from commit 128bb779695b16caf76971d6c96e641c86d1088d)

fix(cli): point build to proper workspace name

---

android/capacitor/build.gradle
android/capacitor/src/test/java/com/getcapacitor/ConfigReadingTest.java

org.json and org.mockito:mockito-inline are updated, along with some minor changes to test classes.

chore(android): Updating more test dependencies

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

closes https://github.com/ionic-team/capacitor/issues/6361

fix(android): Allow WebView to load data urls

---

CONTRIBUTING.md

Maybe this is pre-emptive... but helpful to know there is a Capacitor 4 specific branch!

docs: Add 4.x branch to Contributing.md

---

ios/Capacitor/Capacitor/CAPPlugin+LoadInstance.swift

- added initalization of event listeners in load()

fix(ios): Event listeners were unexpectedly nil

---

cli/src/cordova.ts

closes https://github.com/ionic-team/capacitor/issues/6321

fix(cli): Fix cordova plugin config checker over checking 5.x

---

README.md

It looks like there are new contributors in the `main` branch!
I've added the following wonderful people to `README.md`:
* zakuru
Have a great day!
Ionitron 💙

chore(readme): add new contributor

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

fix(http): copy native response url to fetch response

---

cli/package.json

closes https://github.com/ionic-team/capacitor/issues/6485

chore(deps): Update xml2js dependency

---

cli/src/tasks/migrate.ts

Also add androidxCoreKTXVersion to be updated
Also fix a bug where the gradle and google-services plugins were not being updated because the line to write in `android/build.gradle` was deleted by mistake.

feat(cli): Migrate update to gradle 8

---

android/build.gradle
android/capacitor/build.gradle
android/scripts/publish-module.gradle

Fixes maven publishing after update to Gradle 8.0

chore(android): fix maven publishing

---

cli/src/index.ts

match the note about dimensions not supported
https://github.com/ionic-team/capacitor-docs/pull/198

chore(cli): Add note about dimensions not supported on flavors

---

.github/ionic-issue-bot.yml

Make it more clear that the issue reporter needs to provide a sample app.

chore: Improve bot message for requesting reproductions

---

android/capacitor/src/main/assets/native-bridge.js
core/native-bridge.ts
ios/Capacitor/Capacitor/assets/native-bridge.js

Addressed bug brought up in PR #6725

fix: add http method to prototype.open

---

cli/src/index.ts
cli/src/tasks/run.ts
cli/src/util/livereload.ts

Examples:
```bash
npx cap run ios -l --port 3000 --host 192.168.0.X
```
```bash
npx cap run android --live-reload --port 3000 --host 192.168.0.X
```

feat: add livereload to run command

---

ios-template/App/Podfile
ios/scripts/pods_helpers.rb

closes https://github.com/ionic-team/capacitor/issues/6917

fix(ios): Add workaround for CocoaPods problem on Xcode 15

---

android/capacitor/build.gradle

`androidx.activity:activity` 1.8.0 has been updated with proper SDK 34 support

chore(android): Update default value of androidxActivityVersion

---

cli/package.json

cherry-pick https://github.com/ionic-team/capacitor/pull/7023

fix(cli): Use latest native-run

---

CONTRIBUTING.md

Remove `lerna bootstrap` information since it's no longer needed.
Also update the supported versions

chore: Update CONTRIBUTING.md with latest information

---

android/capacitor/build.gradle

closes https://github.com/ionic-team/capacitor/issues/7095

chore(android): Update json test dependency

---

core/src/core-plugins.ts

cherry-pick https://github.com/ionic-team/capacitor/pull/7003

fix(http): set formdata boundary and body when content-type not explicitly set

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

cherry-pick https://github.com/ionic-team/capacitor/pull/6603

feat: support for Amazon Fire WebView (#6603)

---

ios/Capacitor/Capacitor/KeyValueStore.swift

Removes overloads of KeyValueStore.get and KeyValueStore subscript by providing default arguments to both for the generic value.

chore(ios): Remove duplicate code in KeyValueStore.swift

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java

chore(android): Deprecate PluginCall hasOption 

---

cli/src/android/build.ts
cli/src/index.ts

fix(cli): correctly build and sign Android apps using Flavors 

---

android/capacitor/src/main/java/com/getcapacitor/plugin/CapacitorHttp.java

This PR prevents `RejectedExecutionException` crash reports after shutting down and removes requests once completed from the `activeRequests` map to prevent memory leaks.

fix(http): better handling of active requests and shutting down gracefully

---

cli/src/tasks/migrate.ts

migrate to latest maps and geolocation plugins variable versions

fix(cli): Migrate variables to newer dependency versions

---

core/package.json

in https://github.com/ionic-team/capacitor/pull/7263 forgot to add the new files to the files object so they are published and we can use them in capacitor-docs repo

chore(core): Publish cookies and http docs to npm

---

cli/src/android/build.ts

* fix build on based linux file systems

fix(cli): correct build path for non flavor builds 

---

android/capacitor/src/main/assets/native-bridge.js
android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java
core/native-bridge.ts
ios/Capacitor/Capacitor/CapacitorBridge.swift
ios/Capacitor/Capacitor/WebViewAssetHandler.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

cherry pick https://github.com/ionic-team/capacitor/pull/6818
it had several merge conflicts in the swift files, I think I fixed them correctly, but extra 👀 are appreciated

fix(http): route get requests through custom handler

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

cherry pick https://github.com/ionic-team/capacitor/pull/7280

fix(android): handle http errors on the proxy

---

android/capacitor/src/main/assets/native-bridge.js
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
core/native-bridge.ts
ios/Capacitor/Capacitor/WebViewAssetHandler.swift
ios/Capacitor/Capacitor/assets/native-bridge.js

cherry pick https://github.com/ionic-team/capacitor/pull/7273

fix(http): handle proxy urls with port

---

android/capacitor/src/main/java/com/getcapacitor/plugin/util/HttpRequestHandler.java
android/capacitor/src/test/java/com/getcapacitor/plugin/util/HttpRequestHandlerTest.java

fix(android): incorrect http url params encoding

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

fix(android): let WebView handle errors (#7286)

---

android/capacitor/src/main/java/com/getcapacitor/JSInjector.java

cherry-pick https://github.com/ionic-team/capacitor/pull/7308

fix(android): prevent crash on script injection if the script is too long

---

ios/Capacitor.podspec
ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/PrivacyInfo.xcprivacy
ios/CapacitorCordova.podspec
ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/PrivacyInfo.xcprivacy

supersedes #7314 because branch rules
closes https://github.com/ionic-team/capacitor/issues/7176

chore(ios): Add xcprivacy manifest for Capacitor and Cordova

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

closes https://github.com/ionic-team/capacitor/issues/6377

fix(android): Allow WebView to load blob urls

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

closes https://github.com/ionic-team/capacitor/issues/7517

fix(android): javascript injection not working on urls with query

---

ios/Capacitor/Capacitor/JSExport.swift

closes https://github.com/ionic-team/capacitor/issues/7435

fix(ios): make removeAllListeners accessible from javascript

---

ios/Capacitor/Capacitor.xcodeproj/project.pbxproj
ios/Capacitor/Capacitor/Codable/JSValueDecoder.swift
ios/Capacitor/Capacitor/Codable/JSValueEncoder.swift
ios/Capacitor/CodableTests/DataCodableTests.swift
ios/Capacitor/CodableTests/DateCodableTests.swift
ios/Capacitor/CodableTests/NonconformingFloatCodableTests.swift
ios/Capacitor/CodableTests/URLCodableTests.swift

cherry pick of commit created from https://github.com/ionic-team/capacitor/pull/7647 for cap 6

feat(ios): cherry-pick - JSValueEncoder/Decoder feature parity with JSONEncoder/Decoder

---

cli/src/tasks/migrate.ts

Make migrate do this change:
https://github.com/ionic-team/capacitor/pull/7652
Also removed `removeKey` function since it was unused

chore(cli): make migrate add navigation to configChanges

---

ios-spm-template/App/CapApp-SPM/README.md

docs(CapApp-SPM/README): fix typo

---

android/capacitor/src/main/java/com/getcapacitor/CapacitorWebView.java

* Add margins for Android 15 EdgeToEdge default mode
* Closes #7838 
* Closes #7846

fix(android): add EdgeToEdge compatibility

---

cli/src/ios/common.ts
cli/src/tasks/migrate.ts
cli/src/util/spm.ts

closes https://github.com/ionic-team/capacitor/issues/7936

fix(cli): Don't downgrade deployment target on migrate

---

cli/src/ios/update.ts
cli/src/util/spm.ts

Initial Cordova plugin SPM support
It creates a `Package.swift` per Cordova plugin and links it in the `CapApp-SPM` project.

feat(cli): Initial Cordova plugin SPM support

---

.github/workflows/publish-android.yml
.github/workflows/publish-ios.yml
.github/workflows/publish-npm-nightly.yml
lerna.json

update the branch in lerna, android, ios and npm nightly workflows

chore: Update release branches
