cli/src/ios/common.ts
cli/src/ios/update.ts
cli/src/plugin.ts

Search for cordova plugins in node_modules and add them to the app as local CocoaPods in the project.
For now it assumes all the native code will be in `src/ios` folder. Might need to change that to cover other plugins where the code is in a different folder by reading the plugin.xml content and create the .podspec based on the `source-file` and `header-file` tags instead of doing a `*.{swift,h,m}`. 
The PR already read the xml, but doesn't use it for now.

Handle Cordova plugins native code

---

cli/src/ios/update.ts
cli/src/plugin.ts
cli/src/util/fs.ts

Copies the needed js files from node_modules to public folder following Cordova plugins structure modifying them as Cordova does.
Also generates a `cordova_plugins.js` file in public folder with the required content.

Copy and manage the Cordova plugins js

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

When a file is requested for `/var/mobile/Containers/Data/Application/` (ie, Cordova Camera plugin), serve the actual file.

Serve the actual files in /var/mobile/Containers/Data/Application/

---

cli/src/android/update.ts
cli/src/ios/update.ts
cli/src/tasks/copy.ts
cli/src/tasks/update.ts

Moved the cordova.js to update command as it should not be copied with the regular copy, but when are Cordova updates.
In case there are no Cordova plugins installed it will write empty cordova.js and cordova_plugins.js (initial idea was to delete them, but existing Cordova/Ionic apps will have the cordova.js in the index.html and will show errors on the inspector if not found)

Make the cordova.js copy un update and improve how it works

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

If the existing app has cordova.js linked in the index.html it will cause troubles.
Serving an empty response when cordova.js is requested we avoid this problems.

Return empty response instead of cordova.js content

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Same as #118 but for Android, when cordova.js is linked in the index.html, return an empty response to avoid problems with the injected one.

Return empty cordova.js for Android

---

android/capacitor/src/main/java/com/getcapacitor/JSExport.java

Passing the ex to the log shows it like a crash message despite it doesn't crash, saw a few users on slack putting those messages as errors. 
This happens when there is no public/plugins folder

Don't show the full exception on the log message

---

cli/src/tasks/update.ts

Avoid crash on update when the plugin has no clobbers.
Also don't show clobbers element in the plugin entry if there is no clobber for it.
Improve cordova_plugins.js formatting

Avoid crash when plugin has no clobbers

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVScreenOrientationDelegate.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVUIWebViewDelegate.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVUIWebViewDelegate.m
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVUserAgentUtil.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVUserAgentUtil.m

Classes required by InAppBrowser plugin to work as it imports them.
They are from cordova-ios without changes.

Add Cordova Classes for InAppBrowser compatibility

---

cli/src/android/update.ts
cli/src/ios/common.ts
cli/src/ios/update.ts
cli/src/plugin.ts
cli/src/tasks/update.ts

Rearranged code by moving plugin related method to plugin class.
Now when the plugin doesn't have code for the platform it won't be added to the list, so we avoid an iOS error when the src/ios folder is not found and tries to read a podspec form there

Ignore the Cordova plugin if it doesn't have platform tag

---

ios/Capacitor/Capacitor/CAPBridge.swift

geolocation plugin wasn't working and the problem was the pluginInitialize method was not called, so this will call it after the instantiation

Call pluginInitialize after plugin instantiation

---

ios/CapacitorCordova/CapacitorCordova.xcodeproj/project.pbxproj
ios/CapacitorCordova/CapacitorCordova/CapacitorCordova.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVConfigParser.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVViewController.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVViewController.m

file plugin checks for CDVViewController class in code.
I can't import the Cordova original file as it imports a ton of other classes and we don't really use the CDVViewController, so adding a minimal one to make file plugin work.

Add almost empty CDVViewController to make file plugin work

---

core/cordova.js

The cordova.js is based on the cordova-ios cordova.js.
Remove traces of ios by renaming iOSExec to capacitorExec
Use Capacitor.platform as platform.id instead of hardcode it to ios so cordova.platformId returns the right value.
Set version to 1.0.0, not sure if we can automate this with lerna to match the actual capacitor version

Improve cordova.js file

---

android/capacitor/src/main/java/com/getcapacitor/cordova/CapacitorCordovaCookieManager.java
android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

Added a cookie manager based on Cordova's SystemCookieManager (couldn't use that one as it isn't public)
The cookie manager is needed for file-transfer to work.

Add cookie manager to the mock cordova webview

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

The MimeType was never set. Additionally the URLConnection.guessContentTypeFromName does not recognize *.js types. But this is required to enable ES6 Modules like used in stenciljs.
This fixes https://github.com/ionic-team/capacitor/issues/153

MimeType was not set correctly

---

cli/src/android/doctor.ts
cli/src/cordova.ts

When writing/reading it's `utf8` (default is `utf8`, so we don't even need it)
In xml file content it's `utf-8`

Fix encoding naming mistakes

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVCommandDelegateImpl.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVCommandDelegateImpl.m
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m

Some Cordova plugins need to instantiate other plugins, but we had all that logic in CAPBridge, not accesible from Cordova plugins.
So created a CDVPluginManager class in CapacitorCordova to handle the Cordova plugin classes and changed CAPBridge to use it

Create a Cordova Plugin manager to handle plugins

---

cli/src/ios/update.ts

Improved the custom framework handling to move them to sources folder so they get deleted on update (in case the plugin was removed), and to be grouped with other files from the same plugin.
Also handle source-file tags with framework property. Those are framework libs. Mapped them to `s.vendored_libraries` in CocoaPods

Improve frameworks

---

core/cordova.js

cordova.js had a check to not allow multiple definitions of cordova and was throwing errors because of the native-bridge definition included recently.
Removing the check to avoid such errors

Remove cordova defined check

---

site/docs-md/getting-started/with-ionic.md

- Fix Ionic version
- clarify what build requires `cap copy`
- Link Ionic Native
- fix "Cordova" link (right now links to https://capacitor.ionicframework.com/docs/getting-started/basics/cordova which is an endless load loop)

multiple tiny changes in "with Ionic" docs

---

cli/src/android/update.ts

This was to force the FCM version, but now it will use the default from the plugin.xml preferences.

Remove patch used to force the FCM Version

---

site/docs-md/ios/configuration.md

- always codify Info.plist
- some capitalization
- fix title of linked Apple document

Docs: polish "ios configuration"

---

cli/src/ios/common.ts

Check if it's a Cordova plugin first to avoid checkout for podspec.
This way we avoid reading the src/ios folder, which might not exist if the plugin doesn't include source code and was throwing an error.

Check if it's a Cordova plugin first to avoid checkout for podspec

---

site/src/components/capacitor-site/capacitor-site.scss

Right now each Docs page requests the image relative to itself:
https://capacitor.ionicframework.com/docs/plugins/ios/assets/img/ionic-os-dark-logo.png
https://capacitor.ionicframework.com/docs/ios/troubleshooting/assets/img/ionic-os-dark-logo.png
...

Site: Fix assets in CSS to also work in docs

---

cli/src/tasks/copy.ts

CLI commands were just thrown into the error message. Use ` to highlight them better.

CLI: better highlight CLI commands in CLI error message

---

core/native-bridge.js

Fallback logging to old console.log/error as no keys are exposed by Object.keys(console) until more recent versions of webview/chrome

Added fallback logging to native-bridge.js

---

cli/src/android/update.ts
cli/src/ios/update.ts
cli/src/plugin.ts

Some plugins (like sqlite), have sources/resources references to another plugin files, so search on the root of the project instead of inside the plugin when the file src starts with "node_modules"

If the file starts with node_modules, search on the root

---

core/src/web-runtime.ts

"Plugin does not have web implementation." error message now uses the plugin name instead of just "Plugin"
ex: `Keyboard does not have web implementation.`
Addresses issue #253

Use plugin name in no impl. error message

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m

Retaining and reusing plugins wasn't working because pluginObjects dictionary was not initialized

Init pluginObjects dictionary

---

android-template/app/build.gradle

Updated to `ionic-team:capacitor-android:1.0.+` .
Using `+` to account for future release.
Closes issue #271

Update build.gradle dependency for Capacitor

---

cli/src/ios/update.ts

When the plugin has a podspec framework, add it to the new podspec for static frameworks
Regular plugins without podspec will be grouped in the old dynamic framework podspec
Only add the pod entries in the podfile if there are plugins present for that kind of podspec
Also add .cpp for allowed file types

Generate new podspec for static frameworks

---

capacitor-android-plugins/build.gradle

Some aar files from Cordova plugins are still not found, point to the libs folder with flatDir

Set flatDir for libs

---

cli/src/cordova.ts

Some plugins use `/*` instead of `/manifest` as the parent on edit-config and config-file tags, but * means at the root and the root is /manifest, so replace it to make it work properly.

Replace * with manifest

---

.gitignore
lerna.json
package.json
scripts/deploy.sh
scripts/deploy/package.json.template
scripts/generate.sh

Adds a generate script for creating capacitor-ios folder with ios folder inside and a package.json so it can be published on npm.
Not sure if it will work as I added capacitor-ios to the gitignore to not commit it.

Generate capacitor-ios package to publish

---

electron-template/package.json

`@capacitor/electron` needs to be installed when an electron project is added, but the dependency was missing.

fix for electron-template

---

cli/src/cordova.ts

In edit-config and config-file, the parent is allowed to not have the parent ("manifest"), in case it's not provided we add it to the path parts.
Also log the messages with logInfo to make them more visible.

Handle case where parent doesn't include root

---

cli/src/android/update.ts
cli/src/ios/update.ts
cli/src/tasks/sync.ts
cli/src/tasks/update.ts

Remove Podfile.lock and always run pod install instead of pod update
Removed the needsUpdate flag as it was used to run install or update and now we always use install, and wasn't used on Android.
Also removed the log about running pod repo update regularly as our pods are local now.

Remove Podfile.lock and always run pod install instead of pod update

---

cli/src/config.ts
site/docs-md/basics/configuring-your-app.md
site/src/assets/docs-content/basics/configuring-your-app.html

I was looking into a windows issue and npx cap open android wasn't working despite https://github.com/ionic-team/capacitor/commit/49e94b3c8d33962ab15ca2d3464eb358ad36bba0
As windowsAndroidStudioPath is set, it's using it's value, so changing the default path it there too.
Also changed the path in some docs

Fix windows Android Studio path

---

core/src/core-plugin-definitions.ts
electron/src/electron/filesystem.ts
electron/src/electron/network.ts
electron/src/plugins.ts

Adds the core plugin `Network` to electron.
**Limitation:**
- At this time I can not find a way to detect type of connection, be it WiFi, Ethernet, ectra. So for now, the `connectionType` will either be set to `wifi` or `none` depending on the status of `connected`.

Electron Network plugin support

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

If the image is very big or it's corrupt it will increase memory until it crash the app.
With this change, we catch the OutOfMemory and return an error instead of crashing.

Handle Out of Memory error

---

site/docs-md/apis/filesystem/index.md

In https://capacitor.ionicframework.com/docs/apis/filesystem
Replace `encoding: 'utf8'` with `encoding: FilesystemEncoding.UTF8`

Fix a trivial doc typo

---

site/src/components/site-menu/site-menu.tsx

I believe when starting with a project, people tend to read and follow along with the "Getting Started" section in the order it is there. In that light, it makes sense to put the checking of required dependencies before the installation section.

doc(getting-started): move dependencies before installation

---

plugin-template/android/plugin/build.gradle

Tried to use a local dependency without success (because the plugin projects are modules and modules don't have the settings.gradle), so I think using 1+ is our best option here.
Closes #410

Update capacitor dependency version for plugins

---

cli/src/android/update.ts

This is needed if a plugin's gradle file has a postBuildExtras task declared, otherwise the task won't be executed.
The PR writes it in the capacitor.build.gradle, but we can put it in the app's build.gradle instead.

Add postBuildExtras script

---

cli/src/android/update.ts
cli/src/common.ts
cli/src/cordova.ts

Changed `await import('xml2js');` to `require('xml2js');` so buildXmlElement is sync and doesn't need all those nested promises

Make buildXmlElement sync

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h

Without this, Cordova plugins calling `self.webViewEngine evaluateJavaScript` will fail to build as WKWebView is not available to use.

Make posible for plugins to call evaluateJavaScript on the engine

---

example/src/pages/local-notifications/local-notifications.ts

As `Plugins.LocalNotifications` is undefined for the Android example, it prevents the navigation to the LocalNotifications page

Handle undefined LocalNotifications to allow navigation

---

cli/src/common.ts
cli/src/tasks/copy.ts
cli/src/tasks/sync.ts

Changed copy method to show checkWebDir's error message (right now it's different if you run npx cap copy or if copy is called by other like sync) so it's consistent.
Changed sync function (called by add command) to execute copy and update even if copy fails.
Changed logFatal to logError because logFatal stops execution.
Changed spinner.fail to show only the error.message if defined, as I throw the message directly it was showing undefined, and throwing an Error object duplicated the message as both spinner.fail and logError were displaying the same.

Make sync run update even if copy fails

---

electron/index.js

The splash screen was not customizable because the splashOptions object was hardcoded made it an optional parameter on the constructor so that others can easily customize the splash screen.

Adding electron splash screen config object as optional parameter

---

cli/src/android/update.ts
cli/src/common.ts

This is a big problem when a plugin has an uses-feature tag with required property and another plugin doesn't have a required property or it has the opposite value.
That prevents the app from building, it's a current Cordova problem that we can workaround with this.

Don't add duplicate entries to AndroidManifest.xml

---

cli/src/common.ts
cli/src/tasks/create.ts
cli/src/tasks/init.ts

Make create command not add the platforms as some users might not want them or might not have things ready (CocoaPods, Android SDK)
Instead log how to add them as in init command
Closes #480 #484

Make create don't add platforms

---

example/ios/IonicRunner/IonicRunner/Info.plist
ios-template/App/App/Info.plist

It's not used and should be an array of strings, not a string.

Remove fb entry for LSApplicationQueriesSchemes

---

cli/src/cordova.ts

When the config-file/edit-config element to write in the Info.plist is an array or a dictionary, log that the Info.plist might need some manual editing even if the key is present
Closes #476

Improve the logs about manual Info.plist changes

---

core/src/web/device.ts

manufacturer returns navigator.vendor, which for Chrome in Android is "Google Inc." and not the phone manufacturer, the phone manufacturer is not exposed to the navigator object.
Changed platform to be "pwa"

Add model, osVersion and manufacturer to Device PWA plugin

---

core/src/web/device.ts

The last commit [74091ef](https://github.com/ionic-team/capacitor/commit/74091ef3049af958a2d85af74606ab77296ae22a) have errors while get the model in user agents that has parentheses between the infos about the device like mine below
```
Mozilla/5.0 (Linux; Android 7.1.1; Moto E (4) Build/NMA26.42-97; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36
```
Also, if you have an iPhone you will get `CPU iPhone OS {version}` like as the osVersion. Is a bunch of infos then i reduce to only the real OS version.
If you are in a webwiew, your user agent will has a ` wv` and this break the operation to get the model in android phones
- Get model before `AppleWebKit`;
- Remove webview reference
- Get only the version in non-Android devices
[User agents in …

fix(device): ios version and motorola model

---

cli/src/android/common.ts
cli/src/android/update.ts
cli/src/cordova.ts
cli/src/ios/common.ts
cli/src/ios/update.ts
cli/src/plugin.ts

Added a plugin blacklist with "cordova-plugin-statusbar", "cordova-plugin-splashscreen" and "cordova-plugin-ionic-webview" to skip the install. It will also log that they were skipped.
Removed some old CocoaPods plugin type code as al iOS plugins should use CocoaPods now, but it's type is "Core", not "CocoaPods".
Anyway, I find the word "Core" a bit confusing as we use it for the 3rd party plugins, the real core plugins are the ones included in Capacitor and those are not logged/handled

Added plugin blacklist to skip install

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Use the handleProxyRequest method to workaround CORS problems by setting a Access-Control-Allow-Origin header to the request

Set Access-Control-Allow-Origin header to workaround CORS

---

cli/src/cordova.ts

Some plugins like Ionic Keyboard use `target="config.xml"` instead of `target="res/xml/config.xml"`, so changed the code to just check if target contains `config.xml`

Inprovement in config-file handling

---

scripts/prerelease.sh

use `pod spec lint` instead of `pod lib lint` in the prerelease script

Use spec instead of lib and also check CapacitorCordova.podspec

---

cli/src/cordova.ts

If a dependency plugin can't be installed, log an error message, but don't break the execution.
Closes #541

Log error if dependency plugin fails to install

---

cli/src/cordova.ts

As incompatible plugins are not listed, having a dependency to an incompatible plugin causes an infinite loop as it doesn't see it installed.
Closes #544

Skip install on incompatible dependencies

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

The CORS workaround causes problems with POST, PUT, DELETE and ORIGIN, and for GET will create a new connection that might not have the webview cookies, so removing it from the code.
People needing this because they can't configure the server to enable CORS will have to use a plugin that use native code for the connections.

Remove CORS workaround

---

app-template/www/js/capacitor-welcome.js

Testing the generated app on iOS 10 it wasn't working.
It turns out that there are a problem with async arrow functions on iOS 10 (https://bugs.webkit.org/show_bug.cgi?id=166879)
Removed the arrow function to make it work on iOS 10.

Remove arrow function

---

cli/src/tasks/new-plugin.ts

The files are being created inside `esm` folder, so update the path in the generated package.json

Fix main and types path on generated plugin's package.json

---

cli/src/tasks/create.ts

The default project generated by create command have `"bundledWebRuntime": true`, so it needs the `capacitor.js` file to work, but it's not copied until copy command is executed, so execute it as a create step.

Make create copy web files

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

This will fade the status bar from white to black (and black to white) when changing the style instead of it just changing immediately. Just wanted the transition to look a little cleaner.

Animate iOS statusbar when changing style

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

As on Cordova WebView plugin, adding Cache-Control no-cache to the server response headers.

Add Cache-Control no-cache to Android server response

---

ios/Capacitor/Capacitor/Plugins/Share.swift

I noticed this crash while testing Example app on iOS 12.
Not sure if it was happening before or if it's new on iOS 12, but what the fix do is to show the share sheet centered (as we do for all the other popovers), so shouldn't break previous versions (unless the share sheet was changed to be a popover now)

Fix share crash

---

cli/src/plugin.ts

It was showing the "Found 0 Capacitor plugins" when passing 0 incompatible plugins.
Closes #567

Make sure it's capacitor type

---

cli/src/tasks/new-plugin.ts

Description and git repository are mandatory for iOS plugins, if the user doesn't provide them, then the generated .podspec will fail to validate and the plugin won't be able to install.

Make Description and git repository mandatory on plugin generator

---

cli/src/definitions.ts
cli/src/ios/update.ts
cli/src/plugin.ts

When using a locally installed plugin, the app failed to build.
Changed the Podfile generation to use the path of the plugin instead of picking it from node_modules

Fix iOS project build when app uses a locally installed plugin

---

cli/src/plugin.ts

In my previous PR I noticed we have all the deps in the config object, so I'm replacing the getDependencies method to get them from there instead of reading the package.json file

Avoid package.json read to get dependencies, we have them in config object

---

cli/src/ios/update.ts
cli/src/util/fs.ts

Related to #612, not completely fixes it yet.
It will add `import Cordova` to .swift files to make them compile

Import Cordova in .swift files

---

cli/src/config.ts
cli/src/definitions.ts
cli/src/ios/update.ts

With this we can close #612
It adds a configurable option to set the Swift version for Cordova plugins.
Also makes the iOS min version configurable, which we already had as a config value, but wasn't really configurable.
To configure both, this will need to be added to the capacitor.config.json file:
```
"ios": {
"cordovaSwiftVersion": "3.2",
"minVersion": "11.0"
}
```

Allow to configure Swift version for Cordova Plugins

---

core/src/core-plugin-definitions.ts
example/src/pages/local-notifications/local-notifications.ts
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

Make notification id number in types, Int in Swift and updated examples.
Android push notifications need an Integer as Identifier, so changing it for iOS too

Make LocalNotification id an Integer

---

cli/src/config.ts

As extConfig is picked from capacitor.config.json file, on init command it doesn't exist yet, so it fails.

Handle no extConfig on app init

---

cli/src/android/update.ts

Add amazon schema to capacitor-android-plugins so it understand some possible amazon tags and doesn't show the `error: must not undeclare prefix.`.
Replace $PACKAGE_NAME from the generated AndroidManifest.xml with the appId from config, to avoid malformed manifest errors on install
closes #637

Amazon schema

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Browser.swift

Fixes #616. Also changes default to fullscreen. See: [https://developer.apple.com/documentation/uikit/uimodalpresentationstyle](UIViewController API) for other possible presentation styles. I just stuck with fullScreen and popover for now.

iOS - Adds presentationStyle to BrowserOpenOptions

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Removed the random UUID generation on the authority and use localhost instead.
The port will be picked from server.port configuration in capacitor.config.json.
If the configuration is not present, then it will generate a random port number and store the port in SharedPreferences for reuse.
Closes #636

Change authority

---

ios/Capacitor/Capacitor/CAPConfig.swift

`CAPConfig.getString("server.port")` or `CAPConfig.getString("server.url")` don't return a value, while `CAPConfig.getValue("server.port")` and `CAPConfig.getValue("server.url")` do.
With this fix both of them will work

Make getString understand keys with .

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

The port will be picked from server.port configuration in capacitor.config.json.
If the configuration is not present, keep the old behaviour and use a random port stored in UserDefaults

Make it possible to configure iOS port with server.port

---

ios/Capacitor/Capacitor/Plugins/Browser.swift

Swift 4.0 didn't like the string cases (works fine on 4.1). One option was to add ? to them, but as there are only 2 options I changed the switch with an if.
Also moved the self.setCenteredPopover(self.vc) to only run it in the popover case, as it's not needed in full screen.

Make presentationStyle change compile on Swift 4.0

---

site/docs-md/basics/configuring-your-app.md

With the changes made yesterday (https://github.com/ionic-team/capacitor/pull/648/commits/88de42219c14561ab975044d0d581bc51ac505f8 and https://github.com/ionic-team/capacitor/pull/650/commits/ac99702a6b19cdcabaa43bcc126c8d1b4b9f8c52), it's possible to configure the port.
This just documents how to do it.
And also, how to load an external url.
Closes #617

Document how to configure the port and how to load an external url

---

core/src/core-plugin-definitions.ts

`show` and `hide` actually return a `Promise`. Related to #590.
Also should the `callback?: Function` be there?

fix(SplashScreenPlugin): use correct return type

---

cli/src/ios/common.ts

The PRODUCT_BUNDLE_IDENTIFIER appears twice, change the regex to replace multiple occurrences.
Closes #653

Make PRODUCT_BUNDLE_IDENTIFIER search multiple occurrences

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

Call removeAllViews and destroy on webview object when the app is closed so it doesn't create a new webview on next launch
Closes #669

Destroy webview on app exit

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

On Android we load external apps in the browser, on iOS they are opening internally.
Changed it to load http and https urls outside
Closes #655

Make http and https urls load outside the app

---

android/capacitor/src/main/java/com/getcapacitor/CapacitorWebView.java

super.dispatchKeyEvent(event); doesn't dispatch special chars properly, so they are not passed to the webview.
This appends them to the active element, but won't fire Keyboard Events for them.

Append special chars to active element

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Console.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Toast.java

There are only a few places where == is actually used. Most others are fine.
Fixes #678.

fix usage of == operator in string comparison

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPlugin.m

So in Cordova webViewEngine can have UIWebView or WKWebView class, so it's declared as "id". 
For some reason that confuses InAppBrowser in Capacitor.
Changed it to always be WKWebView as in Capacitor that's the only option.
Closes #677

Make webViewEngine to be WKWebView class

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java
core/src/web/device.ts

Android: 
1) The platform value should be lower case to match the docs in [DeviceInfo](https://github.com/ionic-team/capacitor/blob/78dfcc419b1e3417086569ca9b3d5411531a4391/core/src/core-plugin-definitions.ts#L380)
2) Added a few null checks to prevent NPEs
Core: 
There are 2 platform values in this class: "web" and "pwa". I changed it to "web" because of the doc in DeviceInfo.

Small inconsistencies in the Device plugin's Core and Android implemenation

---

ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m

Renamed from 'exec' to 'beforeExit'. Would throw an error when trying to schedule a background task. Fixes #685

iOS: Fix BackgroundTask beforeExit method name

---

README.md

Since the Capacitor project is already in beta, the Readme should be updated.

Changed 'alpha' to 'beta' in Readme

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift

call success on available methods
call error("not available") on Android only methods
make getDeliveredNotifications return a PushNotificationDeliveredList Promise
add registrationError listener
make PushNotification fields optional and add notification and data for Android
rename didRegisterForRemoteNotificationsWithDeviceToken listener to registration

Improve iOS push notifications

---

cli/src/config.ts
cli/src/cordova.ts

When a plugin has dependencies it enters in an infinite loop because the app dependencies are not updated after the plugin install, so it doesn't find it and try to install it again.

Update app.package after plugin install to refresh dependencies

---

site/src/components/site-menu/site-menu.tsx

As LocalNotifications landed for Android, enable the docs on the menu.
Closes #535

Enable LocalNotifications docs

---

android/capacitor/src/main/java/com/getcapacitor/CapacitorWebView.java

Added a new `captureInput` preference for Android that allows the keyboard key capture, otherwise it will use the default keyboard as the `BaseInputConnection` has a few issues (no autocompletion, no emoji, problems with special chars, not respecting type number, etc)
Closes #676
Closes #701
Also reuse the same `BaseInputConnection` instead of creating a new one every time.

Add an Android preference 'captureInput' to use special keyboard

---

android-template/app/build.gradle

to apply google-services plugin, it requires a google-services.json file present on the project.
Only apply it if the file is present, otherwise log a warning telling Push Notifications won't work.
Closes #724

Only apply google-services plugin if json file is present

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/JSInjector.java

When configuring server.url on Android, the Capacitor js files/code are not injected, so you can't use Capacitor plugins.
Used code from #438

Inject Capacitor scripts when the app is loaded from external url

---

cli/src/plugin.ts

Some Cordova plugins are just js code with no native code, so don't have platform tags.
By returning [] instead of null we detect it as Cordova plugin despite not having platform tag.
Closes #763

Return [] instead of null when there is no platform tags

---

cli/src/cordova.ts

Add "cordova-plugin-console" and "cordova-plugin-compat" to the skip list so they don't get installed as console can cause problems with Capacitor console and compat causes multiple dex problem as the same classes are in cordova-android.

Add console and compat plugins to incompatible list

---

android/capacitor/src/main/java/com/getcapacitor/Config.java
android/capacitor/src/main/java/com/getcapacitor/Splash.java
site/docs-md/apis/splash-screen/index.md

Creating custom icons and splashscreens following Josh Morony's great post works like charm. https://www.joshmorony.com/adding-icons-splash-screens-launch-images-to-capacitor-projects/
To generate my splashscreens I used one of the tools listed https://apetools.webprofusion.com/app/#/tools/imagegorilla. This tool generates the image files needed but names it `screen` instead of `splash`.
Instead of renaming all files it would be nice to let users configure the resource name for the splashscreen image.
```
"android": {
"splashResourceName": "screen",
}
```
I searched but didn't find anything according on ios. If there is I'm happy to add a config param there as well.
BR, Michael

Android: make splash resource name configurable

---

cli/src/config.ts

If `linuxAndroidStudioPath` key is not set in `capacitor.config.json` the `npx cap open android` command fails due to the fact that the path to the binary is an empty string:
```js
this.linux.androidStudioPath = this.app.linuxAndroidStudioPath && this.app.linuxAndroidStudioPath;
// which is equates to:
const foo = '' && '';
```
By changing the way `this.linux.androidStudioPath` is set the issue is fixed, however we could also set the `linuxAndroidStudioPath` key in `app` same as the windows equivalent is:
```js
app = {
...
windowsAndroidStudioPath: 'C:\\Program Files\\Android\\Android Studio\\bin\\studio64.exe',
linuxAndroidStudioPath: '', // this can be set to the default /usr/local/android-studio/bin/studio.sh
...
}
```

Fix android paths

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaInterfaceImpl.java
android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java

While looking into #787, one of the problems was the plugin wasn't getting the onResume event.
I noticed we weren't sending activity events to Cordova plugins (onPause, onResume, stop, start, destroy, onNewIntent)
Added all of them.
It fixes #787, but sadly the plugin doesn't properly work yet, `set` is not able to encrypt the value.

Send activity events to Cordova plugins

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

feat(splash): splash can be animated on android

---

core/cordova.js

cordova.js still had problems on android emulator with old webview because of not being es5

Make cordova.js es5

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Equivalent of https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/162 for Capacitor
Returns 404 error when the file is not found
Also handles urls that append timestamp like params after `?` on file urls to avoid caching.

Handle file not found and file with ?

---

android/capacitor/src/main/java/com/getcapacitor/plugin/StatusBar.java

The statusbar was setting the style incorrectly for android, meaning that it would draw white icons when asking for a light statusbar, instead of dark ones, same goes for the dark style.
When setting the statusbar to either a dark or light style, I was forced to do this trick in order to get it working properly for both android and iOS:
```js
StatusBar.setStyle({ style: this.$isIOS ? StatusBarStyle.Light : StatusBarStyle.Dark }).catch(
this.$helpers.err
)
```
From what I was able to research, the iOS implementation is correct and only the android version of the plugin was displaying these issues, as per [this stackoverflow answer](https://stackoverflow.com/a/39596725/426540) setting a statusbar with a light style is done like so:
```java
...
flags |= View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR; …
```

[Android] Incorrect status-bar style

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java

I won't pretend to be a Java guru, but while trying to fiddle with the backButton events, I noticed that you could not remove the created event listener, after hours of debugging I was able to fix it. Here's the JS example:
```js
...
created() {
this.backEvent = App.addListener('backButton', this.handleHardwareBackButton)
},
destroyed() {
this.backEvent.remove()
},
```
Given the above code, the removeListener method was trying to remove a non-existent `call` object even though the `savedCall` condition was passing.
In fact, looks like this is how it's done for the [iOS counterpart](https://github.com/ionic-team/capacitor/blob/aaa301a5874b37bdf18d305f1e9e26cc5092dd7c/ios/Capacitor/Capacitor/CAPPlugin.m#L101)

[Android] Remove correct call

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

This method is needed to make window.open work.
The code will make window.open to open Safari (or other apps based on the url scheme)
Closes #798

Make window.open to launch safari

---

core/src/web/index.ts

```typescript
export class TestWeb extends WebPlugin implements TestPlugin {
constructor() {
super({
name: 'TestWeb',
platforms: ['web']
});
}
testMethod: void {
this.notifyListeners('testEvent', null);
this.addLisener('testEvent', () => {
console.log('testEvent!!');
});
}
}
```
This code causes the `TypeError: Cannot read property 'forEach' of undefined` JS error, because `let listeners = this.listeners[eventName];` returns undefined.
```typescript
notifyListeners(eventName: string, data: any): void {
let listeners = this.listeners[eventName];
listeners.forEach(listener => listener(data));
}
```
https://github.com/ionic-team/capacitor/blob/de8e66c/core/src/web/index.ts#L131-L134

Fix: execute `notifyListeners` before `addListener` causes JS error

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

This should fix a compile error introduced in #790.

[Android] Add missing import statement to splash

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

Send error when the photo capture is canceled with cancel button (iPhone) or when the popover is dismissed (iPad)

Send error on photo cancel

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java
android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/CameraUtils.java

By default, the Android webview does **not** open the camera for inputs like:
```html
<input type="file" accept="image/*" capture>
```
This pull-request fixes that. The motivation for this functionality is that it might replace the need for using the *native* [Camera](https://capacitor.ionicframework.com/docs/apis/camera) plugin with purely *browser* APIs. Obviously, the native camera plugin will still be needed for more advanced use-cases, but if all you need is to take a picture with the camera you will now be able to do so without any native plugin (and the same code will also work in browsers).
This functionality was previously requested in #540 and it was [supposedly](https://github.com/ionic-team/capacitor/issues/540#issuecomment-388920583) already …

Add support for media capture using input fields on Android

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java
android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java

At the moment, an input file with capture (`<input type="file" accept="image/*" capture>`) won't show the camera if the permission is not granted beforehand, which is most likely. 
This PR will make the input file request the permission if it wasn't granted and continue the flow if granted. 
@vially as you sent the previous PR that added capture support, can you give it a try?

Make input file capture ask for permission if not granted

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
site/docs-md/basics/configuring-your-app.md

I hope to get better performance, if this debugging could be disabled by a config parameter.
According to the docs `https://developer.android.com/reference/android/webkit/WebView#setWebContentsDebuggingEnabled(boolean)` it defaults to false.
BR

Config param to disable web content debugging

---

android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

Hello,
Use Case: My app needs to save document files like PDF, Excel, ... to the public "Documents" directory so a normal user can discover the file using the buildin file explorer on Android devices.
There were a few problems to solve
* `FilesystemDirectory.Documents` points to the wrong directory
* Runtime permission are missing. Starting with Android 6 (API Level 23) Android supports runtime permissions see https://developer.android.com/training/permissions/requesting. Therefore configuring all permissions upfront in the manifest is not required anymore, except you targeting Android 5 of course.
* Create intermediate directories if they not exists.
I tested on Android 5-8 (Level 22, 23, 24, 25, 27) and writing files works on every device and the changes are immediately visible in the …

Android: Enable Filesystem#writeFile to save files to "Documents" directory

---

android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java

Right now even release builds can be debugged/inspected in chrome.
This will disable them as default when debuggable is false, but the preference from https://github.com/ionic-team/capacitor/pull/820 will take precedence in case the user want to disable it in debug mode, or enable it in release mode.

Make debugging disabled as default in release builds

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java
ios/Capacitor/Capacitor/Plugins/Browser.swift

App crash is an empty string is used as url, return an error if the url is empty

Handle empty url string

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Camera.swift

Make camera full screen as recommended, but allow presentationStyle option to show as popover if desired.
This is only for Camera source, for Photos it should still use popover despite the setting.
Closes #819

Make camera full screen and allow presentationStyle

---

ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

LocalNotifications.cancel was not calling success, so it was hanging if you had an await.
Also if no notifications were present it was failing to call error.
Closes #844

Make LocalNotifications.cancel call success

---

core/native-bridge.js

Add isPluginAvailable function to Capacitor in the native bridge so it's available on iOS and Android

Add isPluginAvailable to native bridge

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Possible fix for #337. Until now I have been adding [cordova-plugin-disable-ios11-statusbar](https://github.com/jcesarmobile/cordova-plugin-disable-ios11-statusbar) to my capacitor projects to fix this issue, so this basically applies the same thing to capacitor's webview. Not sure if its the proper way to solve the issue, but it fixes the issue on the native side instead of requiring CSS changes.

Fix iOS webview bottom space (#337)

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

Cordova requestPermissions method doesn't handle the Android < 6 case, so it crash. 
Avoid to request the permission on Android < 6 as it's not needed and makes the app crash.

Only request permission on Android 6+

---

core/cordova.js

Added call to massageArgsJsToNative as was in original Cordova implementation, which fixes broken passing of ArrayBuf arguments to legacy Cordova plugins.

Fix passing ArrayBuf arguments to Cordova plugins

---

core/cordova.js

On Android the ArrayBuffer is handled in a different way than on iOS.
Modified massageArgsJsToNative function to handle Android in a different way.

Handle ArrayBuffer for Cordova Android plugins

---

android-template/app/src/main/AndroidManifest.xml

Added permissions required by `Navigator.getUserMedia` to default template.
Moved Camera permission there as it's not really required for Camera plugin, but it's required for `getUserMedia`

Add Navigator.getUserMedia permissions to default template

---

site/docs-md/plugins/android.md
site/docs-md/plugins/ios.md

Small docs update. This should prevent users from having to dig into the source code to figure out how to remove plugin event listeners.
I also changed "Swift" to "Java" in android.md
It's my first time contributing so let me know if you need anything else to merge this in.

Add documentation on removing plugin event listeners

---

cli/src/android/common.ts
cli/src/android/update.ts
cli/src/cordova.ts
cli/src/ios/common.ts
cli/src/ios/update.ts

Mark Cordova plugins with no platform tag as incompatible for that platform.
Avoids infinite loops when a plugin dependency doesn't have a platform tag for the one running update.
Closes #875

Detect installed dependencies for other platforms

---

cli/src/cordova.ts

Added `cordova-plugin-music-controls` and `cordova-plugin-add-swift-support` to the incompatible list to skip the install.
Closes #874

Add more incompatible plugins to the list

---

cli/src/cordova.ts

When reading a plugin js file to create the transformed one, if it was generated from windows it can add bad characters. Remove line terminators to avoid such problem.
Closes #823

Removes line terminator characters from plugins code

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift
site/docs-md/apis/status-bar/index.md

This will allow the app to either hide the status bar by default or use the light content style by default based on the `Info.plist`, which prevents the status bar flashing an undesired state from the bridge view controller's defaults.

feat(statusBar): set default ios status bar options based on plist

---

ios/Capacitor/Capacitor/UILabel.swift

This fixes #883. Looking at the commit history, it looks like this `UILabel` extension was added for the iOS Toast plugin. The extension was also affecting the native status bar labels. I determined that removing the intrinsicContentSize override fixed that issue and it appears that the Toast plugin still works as expected. I'm not sure the context of why it was needed in the first place so @mlynch will have to confirm, but at least the source of that bug has been found.

remove intrinsicContentSize override from UILabel. Fixes #883

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Geolocation.java

Using Capacitor on Android, no accuracy is recieved on the Geolocation plugin. This fix adds the property to the GeolocationPosition object.

Fix: added accuracy to GeolocationPosition object

---

ios/Capacitor/Capacitor/Plugins/Toast.swift

We weren't calling success on toast show, so the promise was pending.
Also removed some `;`, a commented line and adjusted the max size a little as toast was going offscreen if the text was too long.

Call success on Toast and minor fixes

---

Capacitor.podspec

This updates the podspec of the Capacitor target to use the `swift_version` syntax required by current versions of cocoapods. Without it there would be build errors as described in #920.

Add Support for Swift 4.0 in Cocoapods 1.5 and higher

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

Following https://github.com/ionic-team/capacitor/issues/226 I suggest this PR in order to set per default the splash screen image on Android to FIT_XY instead of CENTER_CROP

feat: set splash screen scale per default to FIT_XY on Android

---

ios/Capacitor/Capacitor/DevMode.swift

On iPad, when you shake the device, instead of showing the dev menu, it crash because it's a popover and needs some extra settings to show.

Fix dev menu crash on iPad

---

cli/src/android/common.ts
cli/src/android/update.ts
cli/src/cordova.ts
cli/src/ios/common.ts
cli/src/ios/update.ts

Fix bug introduced in #877 that makes update fail if a Capacitor plugin is present.
Also simplified the code and removed async/promises that weren't needed.

Fix update failure when Capacitor plugin is present

---

ios/Capacitor/Capacitor/Plugins/Filesystem.swift

If the base64 string have the `data:type/ext;base64,` it silently fails to write.
With this change it will strip that part, and also return an error if the base64 data is not valid.
Closes #891

Fix base64 write problems on Filesystem.writeFile

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Related to #951 and #955.
Turned out, there is a lifelong known [issue](https://issuetracker.google.com/issues/36918490) that `POST` requests can't be intercepted with `WebViewClient.shouldInterceptRequest(WebView, WebResourceRequest)` method. In my case this resulted in all GraphQL queries became duplicated – the first one is broken, with `Content-Length: 0` and an empty body, then the second normal one comes. I didn't came up with any better solution than to execute `handleProxyRequest` for `GET` requests only.
@jcesarmobile what do you think?

Android: Intercept proxyied requests in handleProxyRequest for GET method only

---

ios/Capacitor/Capacitor/CAPBridgedPlugin.m

The Foundation header include is incorrectly cased which means builds will fail on case sensitive systems.

Fix casing in ios/Capacitor/Capacitor/CAPBridgedPlugin.m

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Keyboard.java

Fix Keyboard.setAccessoryBarVisible() on Android

---

cli/package-lock.json
cli/package.json
cli/test/add.android.spec.ts
cli/test/tsconfig.json
cli/test/update.android.spec.ts
cli/test/util.ts

This PR does:
- Fix android tests by
- using `npm install` to install `@capacitor/core` and `@capacitor/cli`. Otherwise later use of `npm install` for `@capacitor/android` or `@capacitor/ios` will wipe the `node_modules/@capacitor/` folder,
- copying the Android Cordova assets after 'add android', otherwise `cap add android` will fail as the `android` directory already exists.
- Bump `jest` version to allow the `describe.each` construct.
- Use the `describe.each` construct to run both the `add` and `update` tests on a standard app layout and a monorepo-like layout.
**Notes:**
1. To run only the android tests, I use the following command. I believe two `package.json` commands could be setup in the future, with two jobs in a `.travis.yml` file (with one running on the `macos` image with …

Fix android tests

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/Config.java
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
site/docs-md/basics/configuring-your-app.md

This PR adds `allowNavigation` option to `capacitor.config.json` that allows to configure additional hosts that Capacitor will open in its WebView.
Ref. https://forum.getcapacitor.com/t/how-to-execute-the-code-before-main-app-is-fully-loaded/200

Add `allowNavigation` option that allows Capacitor to open certain URLs in its WebView.

---

cli/src/config.ts
cli/src/ios/add.ts
cli/src/ios/update.ts

On https://github.com/ionic-team/capacitor/pull/867 the iOS part was not implemented, so this PR does it.
@ptitjes not sure if you can test this on iOS, or provide a sample project that uses workspaces/hoisting so I can test? I only tested that regular projects still work fine after this change
Closes https://github.com/ionic-team/capacitor/issues/998

Resolve node modules for iOS

---

cli/src/ios/update.ts

Unneeded newlines and spaces are added to the generated `Podfile` due to weird formatting in `cli/src/ios/update.ts`. This minor PR fixes its behaviour.

Remove unneeded spaces when generating `Podfile`

---

cli/src/android/update.ts

Some plugins like `cordova-plugin-purchase` use source-file tags for .aidl files, they should go in aidl folder instead of java folder

Handle .aidl files in source-file tags

---

cli/src/plugin.ts

Despite on windows paths use `\`, those paths come from cordova plugins and looks like `/`, so don't use `sep` to get the OS separator, but always use `/`
Closes #1013

Fix getFilePath on Windows

---

cli/src/plugin.ts

As we now get the actual path by calling `resolveNode`, this `file:` replace causes problems and it's not needed, remove it and use the rootPath.
Closes #1011

Fix path for local Capacitor plugins

---

android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

mkdir can't create folders on Documents directory because it needs permissions but they weren't requested.
Added permission checking and improved the flow as the first write of file or folder was failing as didn't continue after the user accepted the permission, so it was silently failing.

Add permission check for mkdir

---

electron/src/electron/filesystem.ts

The documents dir in the `Filesystem` plugin for electron was using forward-slashes, even when the os was non-windows.  I've updated it to use `path.join` instead.

Fixing Filesystem documents dir for non-windows os in electron

---

cli/src/cordova.ts

If a plugin have a script tag in the .js code, even if it's a comment as on cordova-plugin-buildinfo, it breaks the js injection.
Remove any script tag and it's content from the plugin's .js files

Remove script tags from plugins code

---

ios/Capacitor/Capacitor/CAPAssetHandler.swift

When testing AppFlow on webview plugin, the files were cached sometimes so I added this there to solve the problem.
Back porting it to Capacitor

Add no-cache header

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/FileUtils.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Use `https` instead of `capacitor` as scheme on Android 
Also renamed `capacitor-asset` to `capacitor-file` for handling file:// urls

Use https as scheme on Android

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
site/docs-md/basics/configuring-your-app.md

To allow loading from capacitor-file, capacitor-content and http by default, but still allow to disable it if desired.

Enable Mixed content mode by default

---

cli/src/electron/add.ts
core/package-lock.json
electron-template/package.json
example/electron/package-lock.json
example/electron/package.json
example/package-lock.json
example/package.json

Update electron-template and example to electron 4.0.0
Closes #692 and #1059 because electron >= 3 allows fetch to `file://`

Update electron to 4.0.0

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

Add `preferredInterfaceOrientationForPresentation` and `supportedInterfaceOrientations` to make view controller rotation configurable and add `supportedOrientations` array that makes the configuration possible from `cordova-plugin-screen-orientation`.
Will also read current configuration from info.plist file
Closes #1061

Add cordova-plugin-screen-orientation support

---

site/docs-md/apis/status-bar/index.md

I have version @capacitor/core 1.0.0-beta.13, in this version the method has this structure (no second parameter):
```js
setStyle(options: StatusBarStyleOptions): Promise<void>;
```

Update docs setStyle method (StatusBar)

---

cli/src/ios/update.ts

Hi,
we have a project with [lerna](https://github.com/lerna/lerna) who uses symlinks to manage dependencies and we found that CocoaPods doesn't follow symlinks.
The problem is that CocoaPods doesn't follow symlinks when `pod install` is runned so is needed to resolve it when making the PodFile. If the dependency (custom plugin) is a symlink CocoaPods don't imports any source code when installing/adding it.
[7051](https://github.com/CocoaPods/CocoaPods/pull/7051) - CocoaPods closed pull request.

Follow pod symlinks

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/Plugins/SplashScreen.swift

List of improvements:
1. Startup Capacitor plugins before Cordova plugins
1. Call `showOnLaunch` as soon as the plugin is ready instead of waiting for `didLoad`
1. Don't set initial alpha value to 0 as we want it to be present from the beginning and even with a 0 time animation it still takes a few ms to animate. And it also fixes a bug where the splash disappear on rotation.

Add some splash screen startup improvements

---

ios-template/App/Podfile

Change Podfile to define `capacitor_pods` that will contain all Capacitor dependencies (and Cordova/Capacitor plugins), so it can be used in multiple targets.
Closes #1121

Define a common pod so it can be used in different tagerts

---

android/capacitor/src/main/java/com/getcapacitor/AndroidProtocolHandler.java
android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/FileUtils.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
core/native-bridge.js
ios/Capacitor/Capacitor/CAPAssetHandler.swift
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPFile.swift
ios/Capacitor/Capacitor/Plugins/Camera.swift

Use a single scheme for iOS and Android
On Android it also
- Removes duplicated injection of Capacitor js files
- Improves injection of Capacitor for live reload and allowNavigation urls (injecting the script in `onPageFinished` was making Capacitor use the web implementation instead of the native one)
- Fix crash when navigating to another page when allowNavigation is not configured

Use a single scheme for iOS and Android

---

site/docs-md/android/troubleshooting.md

closed pr #1135 rather than trying to figure out how to roll back the edit

docs(android/troubleshooting): typo missing period

---

cli/src/cordova.ts

It conflicts with Capacitor's Keyboard plugin as the code is similar

Add cordova-plugin-ionic-keyboard to incompatible list to avoid conflicts

---

cli/src/config.ts

I was attempting to use capacitor in a monorepo setup with the native project in a subdirectory and capacitor config at root. I want to have the platform directories in the project directory instead of at root so I set the `rootDir` in the config to my project's directory. This worked great for iOS, but Android did not work because it put some files in my project directory and some at root. To me it seems like if iOS uses the custom config, then Android and Electron should as well. This seemed like the only way to resolve this issue, but I may be wrong about that.

Use custom config for Android and Electron platforms like iOS does

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

Very simple implementation of view resizing when keyboard showing/hidding. The logic is copied from cordova-plugin-ionic-keyboard. There are two config parameters related to resizing:
- **resize**, allowed value is either `true` or `false`. Default value is `true`.
- **resizeMode**, allowed value is `native`, `ionic` or `body`.  Default value is `native`.

Implement view resizing on keyboard show/hide

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPPlugin.m

Right now self.webView is available, but it's null because we don't set it anywhere.

Make self.webView available for Plugins

---

example/ios/IonicRunner/IonicRunner/AppDelegate.swift
ios-template/App/App/AppDelegate.swift
ios/Capacitor/Capacitor/CAPAppDelegate.swift
ios/Capacitor/Capacitor/CAPBridge.swift

Not sure if related to the Swift 4.2 conversion, but looks like when it has `Any` it doesn't work and the `application continue` method is not called. Changing it to `UIUserActivityRestoring` makes it work again.

Fix Universal Links not passing data to app

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

The webview natively handles the keyboard by scrolling it, so headers and other fixed elements go out of screen and that's not desired.
This PR removes the native handlers and makes the plugin resize the webview then the keyboard appears.

Avoid the native webview keyboard handling to use our own

---

ios/Capacitor/Capacitor/Plugins/Keyboard.m

iOS keyboard always calls willHide, even when user changes the input field and there is no visible disappear/appear animations.
This PR uses a timer that is disabled if willShow is called right after willHide, so it doesn't send the event.
Closes #1161

Avoid duplicate hide event when user changes field

---

cli/src/definitions.ts
cli/src/ios/update.ts
site/docs-md/basics/configuring-your-app.md

So far I've only needed `-ObjC` linker flag, but adding it as default could increase the app size, so I made it configurable to add it only when needed and add some other linker flag we didn't think about.
Closes #1133

Allow to configure Cordova linker flags

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift

I think we should use just `LocalNotification` instead of `LocalNotificationRequest` and return all the fields the `LocalNotification` has on both iOS and Android, but for now I'm removing `options` as it's not returned by Android, and returned as `extras` on iOS. 
Closes #947

Remove extra/options from LocalNotificationRequest

---

ios/Capacitor/Capacitor/CAPPluginCall.swift
ios/Capacitor/Capacitor/Plugins/Keyboard.m

Make the Swift CAPPluginCall Extension to be accessible from Objective-C, so Objective-C plugins can use it's niceties.
Also make show return success, hide return unimplemented and setAccessoryBarVisible a regular success call

Make Keyboard plugin methods return proper promises

---

cli/src/cordova.ts

So cordova-plugin-file-transfer and other plugins checking the whitelist can connect. 
Closes #1199

Add <access origin="*" /> to generated config.xml

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

Occasionally you can send a dataURL with header. To prevent an error while creating the file on Android and save developer time by discovering this.
Issue #1130

Remove header form data

---

ios/Capacitor/Capacitor/Plugins/BackgroundTask.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m

A few plugin methods return void, but had promise return type, changed them to CAPPluginReturnNone

Make plugins that return void to be CAPPluginReturnNone

---

example/src/pages/background/background.ts
site/docs-md/apis/background-task/index.md

Remove the setTimeout from the example app and example in docs and document that it doesn't work on iOS when the app is in background.

Remove setTimeout from example and docs

---

cli/src/ios/update.ts

I suppose the `else` was missing due to a typo.
Without it all the weakly linked libraries were also added to either the `vendored_frameworks` or the `frameworks` array. If they ended up in the `frameworks` they were no longer **weakly** linked (e.g. they ended up marked as `Required` in the `Link Binaries With Libraries` list in Xcode).

Allow weak linking iOS frameworks

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

As described in #1238, the camera settings were not restored when the app was killed in the background. This caused the settings to fallback to their default values.

Restore camera settings after app was killed (#1238)

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java
site/docs-md/apis/splash-screen/index.md
site/src/assets/docs-content/apis/splash-screen/index.html

Since https://github.com/ionic-team/capacitor/commit/d68af92b8fba3aa8735bc812e91a3aa25b9a5541, the splash screen is not `CENTER_CROP`ed anymore which makes difficult to have (animated) vector drawables as splash screen.
As a middle ground, this PR allows to configure the `scaleType` in splashScreen plugin configuration.
The default is set to the new value since https://github.com/ionic-team/capacitor/commit/d68af92b8fba3aa8735bc812e91a3aa25b9a5541, i.e. `FIT_XY`.

[splash/android] Configuration for scaleType

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/plugin/WebView.java

Check that the server path is not empty and exists before setting it.
Also changed the preferences name to avoid problems with Cordova apps migrated to Capacitor
Closes #1214

Check that the server path is not empty

---

site/docs-md/plugins/web.md

Clicking on the 'Getting Started' link in the web plugin documentation took you to https://capacitor.ionicframework.com/docs/plugins/'./#getting-started
Clicking that link causes some oddities where it'll continue to reload and really isn't the right place anyway.
Probably one of the smallest PRs ever :)

Fixed broken documentation link

---

ios/Capacitor/Capacitor/Plugins/Device.swift

Fixed https://github.com/ionic-team/capacitor/issues/1233
Locale.current.languageCode **doesn't return the correct language** used by device, **becouse Capacitor didn't implement localization to project.**
After changing to Locale.preferredLanguages[0] it returns phone lang properly.

Fixed getLanguageCode()

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

Docs say correctOrientation is true, but on iOS it was set to false
Closes #1269

Make iOS correctOrientation default match docs

---

cli/src/index.ts
cli/src/tasks/init.ts
cli/test/init.spec.ts

This pull request is to add an option to the init command of Capacitor. This option will make it possible to set the `webDir` setting in the capacitor config.  By default it is set to 'www'.
The default works for Angular projects but for React and Vue will require a different directory. By opening up this option it is now possible for the Ionic CLI to set this in the creation of the project.

feat(init): add an option for setting the webdir of a project.

---

cli/src/ios/doctor.ts
cli/src/tasks/doctor.ts

doctor was outputting wrong package info for core and android
Also it was looking for capacitor android and capacitor ios on gradle/CocoaPods dependencies, but we moved to npm long ago, so on Android was appearing as not installed.
Also output installed versions as it was only outputting latest available versions.

doctor command improvements and bug fixes

---

cli/src/util/term.ts

Interactive mode check doesn't return true if all args are ok, so it fails to create a new project

Fix interactive mode check

---

cli/src/plugin.ts
cli/src/tasks/new-plugin.ts

If the user provides a scope on the plugin name it was failing to create the plugin, now it removes the scope from the folder name

Remove scope on plugin creation

---

cli/src/android/common.ts
cli/src/android/update.ts

Fix CLI to point to the plugin src instead of to the plugin id, but keep compatibility with older plugins

Make old plugins with subfolders still work

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java

This PR does not solve all of the issues regarding pushNotificationActionPerformed event as described in #1221  and #1181 but, I believe it is a step closer, and at least gets people a little unblocked.
App launchMode must be set to singleTask or handleOnNewIntent wont be called as described in #971 
The returned data does not contain the original notification (like on iOS), since I'm not sure how to get it on Android. I'm just passing everything I get from extras bundle to notificationRequest property. It seems that extras contain stuff from notification's data property.
Even it this gets merged there is still a problem that pushNotificationActionPerformed event is not fired if the app is closed (not in background) when notification is tapped. I'm not sure how to solve this.

Android pushNotificationActionPerformed 

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Geolocation.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/Geolocation.swift

This adds the `timestamp` and `altitudeAccuracy` properties to the built in Geolocation plugin to match the [current web API for geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Position), as well as the equivalent [Cordova plugin](https://github.com/apache/cordova-plugin-geolocation).

Add timestamp and altitudeAccuracy to native geolocation plugins

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift

Changed on `PushNotificationActionPerformed` from `notificationRequest` of type `any` to `notification` of type `PushNotification`.
Made id and data not optional and made sure they are always there on iOS and Android.
Closes #1181

Improve pushNotificationActionPerformed

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

It was only set when picking from gallery, but not from camera

Fix allowEditing not working on iOS when taking pictures

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

We are only injecting Capacitor when the url scheme matches the Capacitor one (http), make it work for https too
Closes #1381

Inject Capacitor into https urls too

---

core/package.json

Fixes #1357.
See https://rollupjs.org/guide/en#compatibility.

Change main field to CommonJS for core package

---

android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

The Filesystem plugin currently handles user permissions only for write actions. This PR extends the permissions for all the Filesystem plugin public methods.

Added read permissions for Filesystem plugin

---

ios-template/App/Podfile

Xcode 10 caches or don't rebuild existing Pods, so when adding new Cordova plugins users need to do a `Product -> Clean Build Folder` before running or plugins won't be detected.
Also if developing a Capacitor plugin or editing Capacitor source code, same thing happens.
This workaround prevents the caching but requires CocoaPods 1.6.

Add workaround for Xcode 10 CocoaPods caching

---

ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

Issue: 
1. After receiving Push/Local Notifications app crashing immediately.
2. In iOS also handled the extra parameter which is not receiving back when notification fired.

Notifications crash fix and handled extra argument value

---

core/src/web/filesystem.ts

I have found an issue writting a file using filesystem core plugin (on the web platform); The plugin tries to create the "A" directory, when trying to save the following structure:
```ts
const savingFile = <FileWriteOptions>{
directory: FilesystemDirectory.Data,
data,
path: '/' + identifier
};
```
Since  FilesystemDirectory.Data turns into "DATA", I have noticed a substr was being used with an "-1" incorrectly handled from an indexOf; so "A" folder was incorrectly being created.

[core][filesystem plugin] fixing writeFile when no subdir is used

---

cli/src/android/open.ts

wait true blocks the terminal until Android Studio is closed, setting it to false to just launch without blocking.

Set open wait to false to not block the terminal

---

cli/src/cordova.ts

Doesn't build on iOS because of problems with its .framework files.

Add cordova-plugin-braintree to incompatible plugins

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/UriMatcher.java
android/capacitor/src/main/java/com/getcapacitor/util/HostMask.java
android/capacitor/src/test/java/com/getcapacitor/util/HostMaskTest.java

Makes it possible use star masks in `server.allowNavigation` option of `capacitor.config.json`.
Examples:
- `*.example.com` would match `app.example.com`, `www.example.com` but not `example.com`
- `192.168.*.*` is valid
What the changes are:
- `HostMask` is a matcher, it parses text into masks and check strings against it `boolean matches(String host)`, i.e. `HostMask.Parser.parse("192.168.*.*).matches("192.168.1.1")` would return `true`
- `HostMaskTest` is a test suite for the above, more mask examples are inside
- `UriMatcher` was tought to use `HostMask` for the host part
- `Bridge` contained some matching of its own, that was replaced with use of `HostMask`
Closes #1381 
Closes #1389

1381 - PR1128 broke my use case AKA star mask in `server.allowNavigation` 

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java

We don't support fireos and users can guess if it's an amazon device from `manufacturer` property, so removing fireos from the return as it's not a real platform right now.

Remove fireos from getPlatform

---

core/src/core-plugin-definitions.ts
core/src/web/device.ts

Platform can only be 'ios', 'android', 'electron' or 'web', so make Device.getInfo platform to only allow one of those values.
Closes #1177

Limit the Device platform return to 4 values

---

core/native-bridge.js
core/src/definitions.ts
core/src/web-runtime.ts
electron/src/runtime.ts

`Ionic.WebView.convertFileSrc` was implemented for the same purpose, but that feels weird for non Ionic developers, so added `convertFileSrc` to Capacitor object.

Implement convertFileSrc for getting compatible urls

---

cli/src/tasks/new-plugin.ts
plugin-template/ios/Podfile

Add @capacitor/ios as devDependency and make the Podfile point to it to use latest version instead of the old one that CocoaPods return
Closes #1237

Make generated plugin use npm version of @capacitor/ios

---

cli/src/tasks/new-plugin.ts
plugin-template/android/plugin/build.gradle
plugin-template/android/settings.gradle

Use a local @capacitor/android from npm instead of `implementation 'ionic-team:capacitor-android:1+'`, which was causing problems because of fetching an old version and causes version conflicts when imported.
Closes #978

Make generated plugin use npm version of @capacitor/android

---

site/docs-md/apis/camera/index.md
site/src/assets/docs-content/apis/camera/index.html

Camera permission is not needed for using Camera plugin, so removing it from the docs.

Remove Camera permission from Camera docs

---

android/capacitor/src/main/java/com/getcapacitor/cordova/MockCordovaWebViewImpl.java
core/native-bridge.js
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVCommandDelegate.h
ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVPluginManager.m

When Cordova is present it prevents Capacitor document events from firing, so use `cordova.fireDocumentEvent` when available.
Also makes possible to fire pause and resume events even if no cordova plugins are present.
Closes #1443

Fix conflict between Capacitor and Cordova document events

---

core/src/web/camera.ts

Add error message when user clicks the close button instead of taking a picture

Return error message on Camera web plugin

---

cli/src/common.ts

Prevents webDir values like empty string, ., ./, .. or ../
Closes #1324
Closes #1452

Detect invalid values on webDir and show an error

---

cli/src/common.ts
cli/src/tasks/init.ts

Add checkInteractive for init command and set npm as default package installer in non interactive cases if no option is selected

Add more non-interactive checks for when using as subprocess

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

At the moment, only links with `target="_blank"` are opening outside the app or if it's one of the allowed schemes.
Let any link with any scheme to open outside even if target is not _blank
Closes #839

Open links with any scheme outside the app

---

core/src/web/clipboard.ts

Use readText instead of read when string or url
Also return a proper object with value key
Closes #991

Fix clipboard read for web

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

Sometimes it would be helpful if plugins had access to the local server. A possible use case can be seen in https://stackoverflow.com/a/55916297/1004651, where a plugin uses `ServiceWorkerController` to intercept the requests that a service worker makes and treats them the same way as "normal" requests.

Give access to the local server.

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

If trying to write to a file and the content contains `,`, everything before it is being stripped.
This fix only strips it when the file doesn't have encoding.

Fix writing files with , on the content

---

site/docs-md/getting-started/index.md
site/docs-md/getting-started/with-ionic.md
site/src/assets/docs-content/getting-started/index.html
site/src/assets/docs-content/getting-started/with-ionic.html
site/src/components/site-menu/site-menu.tsx

Revamp of the Getting Started and With Ionic pages:
- Moving "PWA Elements" link down below With Ionic (makes more sense in terms of reading and flowing through docs)
- Changed out of date Capacitor install instructions to match current CLI features
- Added more details as to what happens when commands are run

[Docs] "Getting Started" and "With Ionic" updates

---

scripts/prerelease.sh

For local verification we should use `pod lib lint` instead of `pod spec lint`

Fix prerelease script to proper local verification of podspecs

---

ios/Capacitor/Capacitor/Plugins/SplashScreen.swift

Found a simpler fix for the splash screen blink than #1120 
@stewwan @corysmc, can you give it a try?
Looks like the problem was using the `addSubview` in the `DispatchQueue.main.async`
Closes #620 
Closes #1120

Prevent splash blink

---

core/src/core-plugin-definitions.ts

If no value for a key has been set yet, the returned value is `null`, not a string:

fix(types): return value of `StoragePlugin.get`

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift
site/docs-md/embed/index.md

This is basic support along with the start of docs for embedding Capacitor in any existing native iOS app.
Added a new field called `startDir` that is a directory to serve content from relative to the `public` directory, so setting `startDir = 'tab1'` will load `public/tab1/index.html`. This can be configured directly on the view controller or through User Defined Runtime Attributes in the storyboard tool.

Support for iOS Embed use cases

---

cli/src/index.ts
cli/src/tasks/list.ts

Added a ls command that list plugins of the available (installed) platforms, or per platform if the command contains the platform name.
Closes #1522

Add ls command for listing iOS and Android plugins

---

site/docs-md/basics/workflow.md
site/src/assets/docs-content/basics/workflow.html
site/src/assets/docs-content/web/index.html

I'm reverting ionic-team/capacitor#1536 because it adds some html changes not included in md files, likely from other changes not included.
Also we have capacitor doctor command that prints installed packages and latest versions of the packages, so I think that's better than using `npm outdated` and search in the results.

Revert "Adding instructions on how to update Capacitor"

---

site/docs-md/apis/push-notifications/index.md

Fix Typo in sound option for Push notifications appearance in foreground
[old] `sound`: the devide will ring/vibrate when the push notification is received
[new] `sound`: the device will ring/vibrate when the push notification is received

Fix Typo in sound option

---

android/capacitor/src/main/java/com/getcapacitor/JSInjector.java

Some frameworks like nuxt put things in the `<head>` tag (i.e. `<head data-n-head="">`, so injector wasn't working as we were relying on that tag to inject the javascript. 
This fix will check if the html has a regular head tag, if not it will put the javascript before the closing `</head>` tag if present, and if not it will log an error. 
Closes #1550

Android javascript injection improvements

---

site/docs-md/getting-started/index.md

This minor PR will add a missing parenthesis to the Capacitor [getting started](https://capacitor.ionicframework.com/docs/getting-started) page.

[fix] Added missing parenthesis to /docs/getting-started

---

site/docs-md/cordova/migrating-from-cordova-to-capacitor.md

There is a link to https://capacitor.ionicframework.com/docs/with-ionic which is broken. Correct link is https://capacitor.ionicframework.com/docs/getting-started/with-ionic/

fix broken link

---

site/docs-md/guides/ionic-framework-app.md

The import is working fine now, so removed the note and added the usage instructions.

Fix(docs): Remove note about pwa-elements import not working

---

site/scripts/markdown-renderer.ts

except for xml and html files
Not sure if it's the proper fix for #1585, but seems to work.
Closes #1585

Fix(docs): Avoid the special char replacement on code samples

---

core/src/web/camera.ts

If using pwa-elements 1.3.0 or newer, it will return an error.
Capacitor Camera will detect the error and reject the camera promise with the error message.
Closes #1577

Fix(camera web): Reject promise if pwa-elements return error

---

site/docs-md/apis/camera/index.md
site/docs-md/apis/network/index.md
site/docs-md/apis/push-notifications/index.md
site/docs-md/apis/splash-screen/index.md
site/docs-md/guides/community.md

- Community Guides page: adding *APIs* as a new subsection and link Paul’s Network post. Others in the future.
- Individual API pages: If content is explicitly about an API (like Paul’s on Network - https://developer.school/posts/ionic-4-network-detection-with-capacitor/), then link to it here too. Add header *Example Guides* to existing ones that could use it.
We get the best of both worlds and account for multiple ways that devs could be viewing the docs, for the lowest effort.

Docs: Add more community guides to APIs and comm guides pages

---

cli/src/cordova.ts

- Changed the behavior of the CLI to print missing `.plist` entries for iOS dependencies as `[warn]` statements instead of `[info]` to increase visibility

fix(cli): Updating log entries for missing .plist entries to warnings

---

cli/src/ios/common.ts
cli/src/tasks/add.ts

Fix(cli): Allow to add ios platform from windows

---

electron/src/electron/filesystem.ts

This change adds returns after all rejects, so that promises don't resolve after a rejection.

fix(electron): Prevent promises both resolving and rejecting

---

cli/src/cordova.ts

Some plugins become undefined due to ordering of cordova/plugin_list section of code in capacitor-runtime.js generated by `cordova.js` in `cli` when performing `npx cap copy`/`sync`/`add` etc.
Make sure clobbers occur before merges for the cordova plugin_list. Order by clobbers alphabetically *then* merges alphabetically (under the same theory that a merged "foo.bar" should not be blown away by a merged "foo" that may contain "bar", like the AppCenter/AppCenter.Analytics issue of #1523)
**Capacitor Version**: 1.0.0
**Fixes**: #1615

fix(cli): cordova plugins merges before clobbers

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/NativePlugin.java
android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java

Change default permissionRequestCode from 0 to 9000, so Cordova plugins that use incremental codes starting from 0 work.
Closes #1617

fix(cordova): forward requestCode 0 to Cordova plugins

---

site/docs-md/basics/configuring-your-app.md

@jcesarmobile - feel free to add more details too...

[Docs] Added appId, appName and npmClient to Configuration

---

electron/src/electron/filesystem.ts
site/docs-md/community/plugins.md

This fixes an issue where Filesystem.stat used the passed in path, instead of the directory + path combination

fix(electron): incorrect path being used for Filesystem.stat

---

ios-template/gitignore

It seems appropriate to ignore `ios/App/Podfile.lock`. Podfile.lock is generated when `npx cap update ios` is executed, and the file is updated based on the host system (cocoapods version).

fix(ios): ignore Podfile.lock

---

cli/src/cordova.ts

It was creating an empty feature tag in config.xml when the plugin had a config-file tag without feature tags.

fix(cli): Avoid empty feature in config.xml

---

cli/src/android/common.ts
cli/src/cordova.ts
cli/src/ios/common.ts

and add `cordova-plugin-googlemaps` as iOS incompatible only.

fix(cli): Allow to filter incompatible plugins per platform

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java

Using this test:
```
(async() => {
let test = async (content, encoding) => {
await Capacitor.Plugins.Filesystem.writeFile({ path: "fa", data: content, directory: "DOCUMENTS", encoding })
return content === ((await Capacitor.Plugins.Filesystem.readFile({ path: "fa", directory: "DOCUMENTS", encoding })).data);
}
console.log(await test("\ra b\r\nc d\n\r\n", "utf8") ? 'ok' : 'ko');
})();
```
iOS and PWA implementations returned 'ok', Android returned 'ko'. This PR causes Android to return 'ok'.

Fix(android): remove incorrect trailing newline in readFile when using encoding

---

cli/src/config.ts

Auto Detect Android Studio path on Windows by reading a Windows registry entry.
First checks if path in `windowsAndroidStudioPath` exist. 
If not it tries to read the Windows registry entry `HKEY_LOCAL_MACHINE\\SOFTWARE\\Android Studio`
Issues #560 and #230
Based on getASPath.bat 
https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/getASPath.bat

chore(cli): Autodetect Android Studio path on Windows

---

ios/Capacitor/Capacitor/Plugins/Toast.swift

Closes https://github.com/ionic-team/capacitor/issues/1660

fix(ios): support multiline text in Toast

---

electron-template/gitignore

The `app/` directory is generated with `npx cap copy electron` and consequently can be ignored. Also, `node_modules/` can be ignored for obvious reasons.
This also resolves #1560.

fix(electron): add .gitignore

---

cli/src/electron/add.ts
cli/src/electron/copy.ts
electron-template/package.json

More clean install/add logs
Removed comments
Install @capacitor/electron on add instead of as dependency of package.json so the template doesn't need to be updated.
Updated dependency

chore(electron): improve template and dependency installation

---

electron/index.js

Deprecate for now, but make it work in current apps so it's not a breaking change.
To benefit from it, users will have to update their template like in https://github.com/ionic-team/capacitor/pull/1672

feat(electron): deprecate injectCapacitor method

---

site/docs-md/electron/updating.md

As a developer using Capacitor, I would like to have a guide to updating my Electron application, similar to what is available for iOS and Android, so that I can have a reference to keeping my application up-to-date.

docs(electron): add updating markdown file

---

android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java
core/src/core-plugin-definitions.ts
core/src/web/filesystem.ts
electron/src/electron/filesystem.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/Filesystem.swift
site/docs-md/apis/filesystem/index.md
site/docs-md/community/plugins.md

Implementation for all platforms, and uses the same move semantics across all.
It also preserves mtime across all platforms for both files and directories, (ctime is not available in some platforms, or is inconsistently handled by the underlying filesystem).
Moving a file to a directory does not imply moving it into that directory (ie "mv <file> <directory>" does not imply "mv <file> <directory>/<file>" and will fail
```
Missing arguments -> fails
Move into a subdirectory of itself -> fails
Move a file to an nonexistent location -> fails
Move a file to "overwrite" a directory -> fails
Move a file into a nonexistent directory -> fails
Move a nonexistent file -> fails
Move a file into a subdirectory that is a file -> fails
Move a file onto itself -> succeeds (with no on-disk change)
Move a …
```

feat(Filesystem): Add move implementation

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
site/docs-md/basics/configuring-your-app.md

Adds backgroundColor configuration option for the webview for both Android and iOS. It can use the same value for both platforms if on the root, or per platform if inside the platform object.
Also fixes a problem with `android.webContentsDebuggingEnabled` configuration option not working. 
Closes #1003

feat(webview): Add backgroundColor configuration option

---

ios/Capacitor/Capacitor/CAPAssetHandler.swift
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeDelegate.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/CAPConfig.swift
ios/Capacitor/Capacitor/CAPLog.swift
ios/Capacitor/Capacitor/JS.swift
ios/Capacitor/Capacitor/JSExport.swift
ios/Capacitor/Capacitor/Plugins/BackgroundTask.swift
ios/Capacitor/Capacitor/Plugins/Clipboard.swift
ios/Capacitor/Capacitor/Plugins/Console.swift
ios/Capacitor/Capacitor/Plugins/Geolocation.swift
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift
ios/Capacitor/Capacitor/Plugins/Network/Network.swift
ios/Capacitor/Capacitor/Plugins/SplashScreen.swift

feat(ios): add configuration option to disable logs

---

cli/src/ios/update.ts

cordova-ios 5 included a new podspec tag for handling CocoaPods, some plugins already updated to use it but we were still not handling it.
This PR reads it and add it to the podspec dependencies.

fix(cordova): handle new plugins podspec tag

---

cli/src/ios/update.ts

As Capacitor has a different project structure than cordova, the `@import Firebase;` doesn't work.
But `#import <Firebase/Firebase.h>` works and does the same, so if present in Objective-C files, replace it.
Closes #1695

fix(cordova): replace Firebase import objective-c files

---

cli/src/common.ts

If you init capacitor in a project, it would prompt for an npm client, even if the project already has a `yarn.lock`. If a project has a `yarn.lock`, capacitor should automatically use yarn as the npm client, instead of prompting. This PR fixes that.

fix(cli/init): check if project already uses yarn before prompting

---

core/src/web/app.ts

Today I've started to use Capacitor and I like the fact that I can use the web plug-ins to simplify our codebase. The 'appStateChange' event was not working in the web environment, so I've added it by listening to 'visibilitychange' on the document. 
Since it's my first hours with the project, I don't know if I put it in the right spot...

fix(web): support for App 'appStateChange' event

---

site/docs-md/web/index.md

It current brings to https://capacitor.ionicframework.com/getting-started/

docs: Fix install link on web section

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java

registrationError was not implemented for Android

fix(push): registrationError not working on Android

---

cli/src/definitions.ts
cli/src/plugin.ts

In some cases Cordova puts the plugins in devDependencies instead of in dependencies, so Capacitor doesn't find them, this will check in both places.

fix(cli): check for plugins in devDependencies

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

This allows capacitor to handle fullscreen. This is my first attempt to write code in Java and please keep in mind it's a really strange environment for me.
Thanks
This should close #605

fix(android): enable full screen video

---

ios/Capacitor/Capacitor/Plugins/Geolocation.swift

Use the best desiredAccuracy (kCLLocationAccuracyBestForNavigation) if enableHighAccuracy is set to true

fix(ios): read enableHighAccuracy geolocation option

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Also only return the proxy response if html, otherwise not intercept. 
Closes #1772

fix(android): better proxy mimeType detection for Capacitor injection

---

example/ios/IonicRunner/IonicRunner.xcodeproj/project.pbxproj
example/ios/IonicRunner/Podfile.lock
example/ios/IonicRunner/config.xml

The generated config.xml is required by Capacitor, but the example app didn't have it.
Closes #1787

chore(example): update example app to work with latest Capacitor

---

core/src/web/filesystem.ts

This fix corrects a problem where an appendFile/writeFile could corrupt a directory entry if given a directory entry path.

fix(core/web): avoid appendFile/writeFile to overwrite existing directory entry

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

According to the typescript definitions the CameraPhoto object should contain a field "format", but it doesn't on android. This PR adds that field and sets its value to "jpeg".

fix(android): add missing format field in CameraPhoto

---

ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift

fix(ios): don't override notification delegate if already set

---

site/docs-md/apis/index.md

Multiple users (myself including) have been confused by how to leverage Capacitor APIs properly. it's really easy to forget to use the API object itself - here's an attempt to clarify things.

Clarify API usage

---

electron/src/electron/filesystem.ts

Will only work in electron 5 or newer because it was added in node 10.12, but it's better than ignoring it.

fix(electron): createIntermediateDirectories option not being used in mkdir

---

core/src/web/filesystem.ts

fix(core/Filesystem): allow readdir on root directories

---

ios/Capacitor/Capacitor/Plugins/Filesystem.swift

readdir returns the full file/folder path instead of just the name (as all other platforms do).
This change makes it return only the name of the file/folder.

fix(ios/Filesystem): make readdir return only content names

---

ios/Capacitor/Capacitor/CAPLog.swift

The changes in 1a6239bea1793d8237878a97f3eb97be76555cfd made the log
output super annoying multi-line debug messages when more than one
argument was passed to print().

fix(ios): improve CAPLog variadic logging

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVURLProtocol.m

It's unused and deprecated, so removing for possible macOS compatibility in the future.
Closes #1814

chore(cordova): remove deprecated AssetsLibrary

---

ios/CapacitorCordova/CapacitorCordova/Classes/Public/CDVCommandDelegateImpl.m

It was hardcoded to www, but that doesn't work as Capacitor uses public folder, and was ignoring possible subfolders.

fix(ios/cordova): return proper pathForResource in CDVCommandDelegate

---

android/capacitor/src/main/java/com/getcapacitor/PluginRequestCodes.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java
core/src/core-plugin-definitions.ts
core/src/web/filesystem.ts
electron/src/electron/filesystem.ts
example/src/pages/filesystem/filesystem.html
example/src/pages/filesystem/filesystem.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/Filesystem.swift
site/docs-md/apis/filesystem/index.md

Implementation for all platforms, and uses the same copy semantics across all.
This method is called 'copy' (rather than node-style copyFile), since it can copy both directory structures and individual files.
It turns out that a copy operation has almost everything in common with a rename operation, so in each case there is a _copy method that does the bulk of the param checking/error handling etc. so as not to end up with a lot of duplication.
Copy, and now rename support a 'toDirectory' as well as the pre-existing 'directory'. Developers can omit 'directory' to use DEFAULT_DIRECTORY, include only 'directory' to rename/copy within a directory, or include both to rename/copy between directories.
Finally, added a set of tests to the example app to show the move/copy operations working.

feat(): Add copy implementation

---

site/docs-md/community/plugins.md

This is forked from `capacitor-admob` , because `capacitor-admob` worked only capacitor/android@beta only.

update(plugins): add @rdlabo/capacitor-admob

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

The local web server is not able to guess the proper mimeType for wasm files, so do it ourselves based on the extension.
Closes #1864

fix(android): return proper mimeType for wasm files

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

I don't understand why you hard-code the spinner size to 120x120 pixels. It does not depend on the screen DPI and if there is a difference between `androidSpinnerStyle` `large` and `small`, I can't see it.
Why not let the spinner decide how large is should be?

fix(android/splash): don't hardcode spinner size

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

On slow devices, there is a visual glitch when the splash screen is hidden, which can be avoided by changing the visibility before removing the view.
Additionally, the `FLAG_FULLSCREEN` should be copied from the window so that the status bar does not appear during the splash, in case `<item name="android:windowFullscreen">true</item>` was specified in `styles.xml`.

fix(android/splash): Avoid glitches on slow devices and respect keep fullscreen flag

---

cli/src/tasks/new-plugin.ts
plugin-template/ios/Podfile

The plugin generator should run pod install so the xcworkspace is generated as the docs say.
Also the Podfile should include CapacitorCordova.
closes #1836

fix(cli): make plugin generator run pod install on plugin creation

---

electron/src/electron/filesystem.ts

I was working with the Filesystem plugin and some data URL files encoded in base64 and I stumbled upon the fact that Electron bridge is not implemented like the Android and iOS one. I simply cannot store a PDF file because it always encrypt as UTF8 and break the file.
On iOS and Android, the default encoding when writing files is `base64`. If a data URL is detected it deletes its header before converting it to `binary`. When reading, if no encoding is given, the same thing happens the other way, it converts `binary` to `base64`.
This is a breaking change for Electron users but ATM, Electron filesystem plugin does not behave at all like iOS and Android.

fix(electron): correctly read/write file with no encoding

---

cli/src/cordova.ts

Otherwise `<js-module>`'s with no name are installed as
`pluginId`.`undefined`, which can mess with `deviceready`.
Copies the logic directly from https://github.com/apache/cordova-common/blob/d73d7fab70d2a5110bae174e48065065373732c9/src/PlatformJson.js#L247
and https://github.com/apache/cordova-ios/blob/4562ef5608d57d471dc11212c9f432762886a32d/bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js#L194
Closes https://github.com/ionic-team/capacitor/issues/1958.

fix(cli): mimic cordova's js-module logic when no name attribute

---

cli/src/cordova.ts
cli/src/definitions.ts
cli/src/tasks/init.ts

On init command, the existing config.xml preferences will be migrated to capacitor.config.json.
Those preferences will be copied to the platform generated config.xml on copy/update commands. 
Closes #1944

feat(cordova): move Cordova prefs from config.xml to capacitor.config.json

---

core/src/core-plugin-definitions.ts
site/src/assets/docs-content/apis/splash-screen/api.html

Just a minor typo fix, changing `authHide` -> `autoHide`

docs(splash screen): fix typo for options

---

android/capacitor/src/main/java/com/getcapacitor/BridgeWebChromeClient.java

Currently when you add a file input with multiple mime-types in the accept attribute Capacitor will only use the first mimetype, this change make the file picker correctly use all specified mime-types.
Example of input thats currently broken:
`<input type="file" accept="image/jpeg,image/png,application/pdf">`
the example file input will only accept jpeg images instead of also accepting png and pdf's

fix(android): handle input file with multiple accept mimetypes

---

core/src/web/filesystem.ts

As stated [here](https://github.com/ionic-team/capacitor/pull/1905#discussion_r318572467), the web bridge slightly behaves differently than iOS and Android one: It does not remove the data url header when using base64 encoding (no encoding given). This PR aims to fix this.

fix(core): remove data url header on writeFile if no encoding is passed

---

core/native-bridge.js

fix(android): don't patch console object

---

site/docs-md/apis/camera/index.md
site/docs-md/apis/toast/index.md
site/docs-md/web/pwa-elements.md

Add note on Toast and Camera about requiring PWA Elements to work.
Also removed the Ionic part of PWA Elements since it no longer uses Ionic components but regular web components.
Closes #1934

docs: add note on plugins that require PWA Elements

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java
core/src/core-plugin-definitions.ts
core/src/web/device.ts
electron/src/electron/device.ts
ios/Capacitor/Capacitor/Plugins/Device.swift
site/docs-md/apis/device/index.md
site/src/assets/docs-content/apis/device/api.html

Adds the app bundle build number to the `Device.getInfo()` payload. Currently you can only get the bundle version number, but developers may wish to display the build number in their app as well.
iOS:
```
Bundle.main.infoDictionary?["CFBundleVersion"]
```
Android:
```
getContext().getPackageManager().getPackageInfo(getContext().getPackageName(), 0).versionCode
```

feat(core): add appBuild to device getInfo

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java

appVersion and appBuild are not optional fields, but in case they are null they won't be added to the resulting object. Changing the null to empty string so they are properly returned.

fix(android): return empty string if appVersion or appBuild fail

---

core/src/core-plugin-definitions.ts

As can be seen in for example https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/Plugins/Filesystem.swift#L107-L116, the current implementation treats file as binary if encoding is left out.

fix(core): update FileWriteOptions and FileAppendOptions encoding description

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java
core/src/core-plugin-definitions.ts
core/src/web/filesystem.ts
electron/src/electron/filesystem.ts
example/src/pages/filesystem/filesystem.ts
ios/Capacitor/Capacitor/Plugins/Filesystem.swift
site/docs-md/apis/filesystem/index.md

Deprecate `createIntermediateDirectories` in mkdir in favour of `recursive`.
Show warning when `createIntermediateDirectories` is used.
Add `recursive` option that replaces `createIntermediateDirectories`
Closes #1936

feat(Filesystem): Deprecate createIntermediateDirectories in mkdir

---

core/native-bridge.js

If I receive news of a Capacitor plugin error via sentry, there are no stack traces because `fromNative` (in `native-bridge.js`) throws a deserialized JSON object, not an `Error`. It's not even clear that the error is from a Capacitor plugin, as it's usually something like `{ message: "File not found" }`.
This pull request transforms the error objects into actual `Errors` before they are thrown (well, passed to the callback/rejected). Now, at least one can see that the error originated from the native bridge:
Note that this PR uses `Object.assign` - I'm not sure whether Capacitor supports platforms without it. This is the MDN compatibility table:

fix(core): return proper Error objects from native

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

- Added a `feature-request` Github template
- Updated the `bug-report` template for cleanliness
- Both templates now add a basic title to help identify type of issue quickly

chore(github): Update issue submission templates

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Some node modules provides ES module script with .mjs extension.

fix(android): return proper mimeType for .mjs files

---

android/capacitor/src/main/java/com/getcapacitor/plugin/camera/CameraUtils.java

The camera throws "Unable to create photo on disk" error when `saveToGallery` is set to `true` on Android 5.1. This PR fixes the issue by calling the `mkdirs()` to create the directory. Fixes the issue #2013
As adopted from cordova-camera-plugin
https://github.com/apache/cordova-plugin-camera/blob/master/src/android/CameraLauncher.java#L610

fix(android): when saving picture to gallery make sure the folder exist

---

core/src/core-plugin-definitions.ts

It's a bit confusing that _adding_ a new listener "overrides" the default listener, so it should be documented.

docs(android/types): Add note about backbutton listener behaviour

---

electron/index.js

Resolves #2010 on MacOS. 
The issue stems from the splash screen being destroyed already, so I'm simply adding a check to ensure that the splash screen reference has a value and that it isn't already destroyed. This seems to solve the problem in a straightforward manner.

fix(electron): Check whether the splash screen is already destroyed on close

---

site/docs-md/plugins/android.md

- improves docs about android plugins with intents -> fixes https://github.com/ionic-team/capacitor/issues/2019
- makes registering/adding plugin to capacitor clearer -> fixes https://github.com/ionic-team/capacitor/issues/2024

docs(android): improve plugin development guide

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

Use the server.url as localUrl if defined so requests have the same origin and fetch works
closes #2042 
closes #1776 
closes #2043

fix(android): allow fetch to local files on livereload

---

site/docs-md/apis/storage/index.md

Mention that UserDefaults and SharedPreferences is used under the hood.

docs(Storage): explain what the plugin uses under the hood

---

electron/index.js

The splash screen's HTML had a bad quote. The opening `"` on `"Helvetica Neue"` actually closed the style attribute. Changing `"Helvetica Neue"` to `'Helvetica Neue'` and properly closing the style attribute solves this, and the splash HTML renders correctly.

fix(electron): use proper quotes on splashHtml style font

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

The iOS implementation of the Camera plugin did not implement saving to the photo gallery. 
closes #2076

fix(ios/Camera): implement saveToGallery

---

site/docs-md/apis/filesystem/index.md

Updated the example-code for the `Filesystem.writeFile({ ... })`-method to include the `await` keyword.

docs(Filesystem): use await in writeFile example

---

cli/src/ios/update.ts

fix(cordova/ios): patch usage of NSBundle bundleForClass in plugins

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
electron-template/index.js
electron/index.js
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
site/docs-md/basics/configuring-your-app.md

Makes possible to configure the userAgent for iOS, Android and Electron from values stored in `capacitor.config.json` file. Can be appended to the original userAgent or totally replaced.
For existing electron apps will require manual changes on the user template.
Closes #2088

feat: make possible to configure userAgent

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

When there are urls in allowNavigation object, requests to those domains are being treated as local request instead of being proxied. This PR solves that.
Closes #2132

fix(android): properly proxy requests to domains in allowNavigation

---

site/docs-md/community/plugins.md

Recently created a small capacitor plugins that allows changing the android navigationbar color during runtime. Adding this to the community plugins section in case it helps someone.

docs(ce-plugins): add capacitor-navigationbar to community plugins

---

android/capacitor/src/main/java/com/getcapacitor/WebViewLocalServer.java

This sends cookies along with requests to proxied urls, brings the behaviour in line with what happens on iOS.
This is important for us as we change the html being served to the app based on the cookies.

fix(android): Send cookies on proxied requests

---

android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ImageUtils.java
ios/Capacitor/Capacitor/Plugins/Camera.swift

This fixes a bug where giving a prescribed `height` when scaling results in an image with inverted aspect ratio (i.e. trying to scale a portrait image would yield a landscape result and vice versa).

fix(plugin/camera): Fix scaling when setting only height

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

On iOS 13 the camera is taking a few seconds to appear because of some configurations being done in a background thread, which shows 3 background thread warnings on Xcode and delay the code execution.
This PR moves all the camera configuration code to be executed in main thread.

fix(ios): set camera configuration in main thread

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

When dark status bar style was defined in plist it wasn't remembered  in statusBarStyle and as a result preferredStatusBarStyle always returned .default, which caused flicker of the status bar . Partially closes #1761 (in terms of ios issues).

fix(ios): set dark statusbar style if defined in plist

---

site/docs-md/ios/custom-code.md

It's already well-documented, but adding a JS example means that you can just copy-paste instructions and start playing around right away.

docs: Added JS example to iOS custom-code section

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

In some cases `wm.addView(splashImage, params);` causes `IllegalStateException` (like calling show twice at once) anda makes the app to crash.
This PR prevents those crashes.

fix(android): avoid crash on SplashScreen.show()

---

cli/src/index.ts
cli/src/ios/update.ts
cli/src/tasks/add.ts
cli/src/tasks/sync.ts
cli/src/tasks/update.ts
cli/test/update.android.spec.ts
cli/test/update.ios.spec.ts

Add --deployment option for update and sync commands that doesn't remove the Podfile.lock file and also pass --deployment option to the pod install command
Closes #2200

feat(cli): Add --deployment option for update and sync commands

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java

When passing in a value via JavaScript to Capacitor like this:
`({volume:0.0})`
then Capacitor in Android is parsing this to an *Integer* instead and *getFloat()* will fail since it is expecting a *Float* type.
The same happens when doing this:
`({volume:0.1})`
then Capacitor in Android is parsing this to a *Double* instead.
So I added explicit casting for these 2 use cases.

fix(android): proper parsing of plugin integers and doubles

---

ios/Capacitor/Capacitor/CAPPluginCall.swift

some javascript float values are received as double

fix(ios): make getFloat work on plugins

---

site/docs-md/plugins/ios.md

The source code for `CAPPluginCall` show that the proper method name is `getBool` rather than `getBoolean`.

docs(ios-plugin-guide): Change getBoolean to getBool

---

electron-template/package.json
electron/index.js

Given that Electron is now at v7, this PR is to support that in Capacitor, and also provides a minor fix in the SplashScreen that is a response to a recently-reported Electron bug.

fix(electron): make apps work on electron 7

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationSchedule.java
core/src/core-plugin-definitions.ts
example/src/pages/local-notifications/local-notifications.html
example/src/pages/local-notifications/local-notifications.ts
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

The notification schedule already has support for repeating on a period of time, via the `every` option. However, it only allows the user to specify one of the options in the enum, with no support for repeating at multiples of the unit of time. This adds a `count` option to LocalNotificationSchedule (inspired by the structure of the notification trigger in https://github.com/katzer/cordova-plugin-local-notifications), which works in concert with the `every` option to set repeating notifications on multiples of the units of time. If no `count` is provided, it defaults to one, so this change should be backwards compatible. Implemented support for iOS and Android, but the web plugin didn't have support for `every`, so I didn't add any support for `count` there.
I'm open to suggestions on the …

feat(LocalNotifications): Add support for count to work with every on LocalNotificationSchedule

---

ios/Capacitor/Capacitor/CAPNotifications.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift
site/docs-md/guides/push-notifications-firebase.md

This PR enables passing strings to the `PushNotifications` `registration` event callback. This will enable user projects to pass any 3rd party token to the same event so they don't need to check which platform it is in JS to get the right kind of token.
This also includes a change to the push notifications firebase guide that adds the necessary lines to the user `AppDelegate.swift` to receive their FCM token in JS instead of the APNS one if they choose.
I have successfully built and tested this code locally to verify that it solves this problem (FCM token is passed through the same event on iOS and android). @jcesarmobile  Let me know if there's anything about this implementation that might be inconsistent with the rest of the repo or some other reason why it shouldn't be merged.

feat(ios): make didRegisterForRemoteNotificationsWithDeviceToken handle Data and String push tokens

---

core/src/web/local-notifications.ts

Request Permission for Local Notification on safari for mac OSX returning this error.
"undefined is not an object (evaluating 'Notification.requestPermission().then')"
Change From: 
Notification.requestPermission().then((result) => {})
To:
Notification.requestPermission((result) => {})

fix(core/web): make LocalNotifications.requestPermissions() work on Safari

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift

So, when a project has a .framework, for some reason appendingPathComponent works in a different way when you append an empty string
if no framework is present, appending empty string to "public" results in "public"
if a framework is present, appending empty string to "public" results in "public/" and makes the app to crash as it doesn't find the public folder.
This PR only appends `startDir` if not empty
Also uses a new assetsFolder variable to be used instead of hardcoded "public" value
closes #2262

fix(ios): incorrect behavior of appendingPathComponent when framework is present

---

cli/src/tasks/new-plugin.ts
site/docs-md/plugins/index.md

The recommended case of the plugin-name is actually
[kebab-case][wikipedia] not snake-case.
[wikipedia]: https://en.wikipedia.org/wiki/Letter_case#Special_case_styles

fix(cli): use proper kebab-case name for npm package

---

ios/Capacitor/Capacitor/CAPBridge.swift

The `dispatchQueue.sync` is causing problems on subsequent plugin calls where the reference is retained (see https://github.com/ionic-team/capacitor/issues/2315 as example)
I don't think it's really needed, it fixes the issue and other plugins keep working, so I think it's safe to remove. 
Closes https://github.com/ionic-team/capacitor/issues/2315

fix(ios): avoid lock of subsequent plugin calls

---

site/docs-md/cordova/using-cordova-plugins.md

Useful in many ways, but recently found it handy when cloning someone's project then double-checking that the plugin version they thought they had actually was the latest.

docs: Add how to determine installed plugin version in project

---

cli/src/android/update.ts

if an edit-config tag has merge mode on application, write directly in the application tag as attributes 
closes #2296

fix(cli): handle edit-config with merge mode on application object

---

cli/src/ios/update.ts

In Capacitor the bundles are in the main bundle, we had patched the path for `[self class]`, but media-capture uses `[CDVCapture class]`, so patching that too.
closes #2185

fix(cordova): patch CDVCapture bundle path

---

android/capacitor/src/main/java/com/getcapacitor/plugin/camera/ExifWrapper.java

fix(android): add missing GPS tags to exif data

---

ios/Capacitor/Capacitor/CAPBridge.swift

I changed the monitoring event because with the previous one it is not possible to intercept the action of entry on the task manager or the arrival of telephone calls, with this event instead it is possible to have the various events (for the purposes I have undertaken with the above plugin is essential to make this change).

fix(ios): fire appStateChange in incoming calls

---

cli/src/android/open.ts
cli/src/config.ts

`execSync` is displaying a registry error if the Android Studio key is not found
This PR moves the Android Studio detection logic from config (which is executed every time) to open (that is only executed when open is called), and also uses `runCommand` instead of `execSync` so the registry message is not displayed, and also improves the error message is the Android Studio registry is not found so users can configure `windowsAndroidStudioPath`
Closes #2031

fix(cli): move Android Studio detection to avoid displaying registry errors

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Browser.java

fix(android): make Browser plugin fire browserFinished

---

core/src/web/clipboard.ts
example/src/pages/clipboard/clipboard.html
example/src/pages/clipboard/clipboard.ts

fix(web/clipboard): allow writing empty string

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

For android, it is useful to hide the status bar right from the start. 
The user can add following setting:
"SplashScreen": {
"splashFullScreen": true
}

feat(android): add splashFullScreen configuration option

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java

This PR implements the `PushNotifications` plugin `getDeliveredNotifications` and `removeDeliveredNotifications` methods.
The fields available on the objects returned by `getDeliveredNotifications` are a subset of those available on iOS, but otherwise the behaviour should be the same.

fix(android): implement getDeliveredNotifications and removeDeliveredNotifications

---

ios/Capacitor/Capacitor/CAPBridgeViewController.swift
site/docs-md/basics/configuring-your-app.md

We are setting the WebView's ScrollView's content inset to never, but some users might not want that.
This PR makes possible to configure the value from `capacitor.config.json` file
Closes #1947

feat(ios): Allow to configure WebView's ScrollView's content inset

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotification.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java
core/src/core-plugin-definitions.ts

This PR adds `group` and `groupSummary` options in `LocalNotifications.schedule()`, which allows you to group notifications together on Android.
I noticed a TODO comment in `LocalNotificationManager.Build` for groups, which says to implement `setGroup`, `setGroupSummary`, and `setNumber`. This PR only implements the first 2, should I also add `setNumber`?

feat(android): add group and groupSummary to LocalNotifications

---

cli/src/cordova.ts

On add command, copy tries to write the AndroidManifest.xml file, but it doesn't exist yet and shows an error.
This PR checks if the file exists before writing to avoid that error.

fix(cli): Avoid AndroidManifest.xml not found error on add

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

Returns the original image in case of cancellation of the image edition

fix(android): return original camera image if edition was canceled 

---

cli/test/util.ts

The tests create a cordova plugin right in node_modules.
In some node versions, the plugin was being removed from node_modules after adding the platform because it was not installed.
So, this PR changes the tests to create the plugin in another folder and install it with npm install.

chore(cli): fix tests for newer node versions

---

.circleci/config.yml

Since we are dropping Xcode 10 support, make circleci use Xcode 11. And as Xcode 11 image includes CocoaPods 1.8.0, we no longer need the install-cocoapods job, that should make tests much faster

chore(circleci): update Xcode and remove install-cocoapods job

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift
site/src/assets/docs-content/apis/push-notifications/api.html

Rather than simply calling `call.success()` on iOS as soon as a user requests permissions (regardless of result), this adds a completion that allows the user to `await` the result in their app and passes back the response or error.

feat(PushNotifications): Make register method to return if permission was granted

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Toast.java
core/src/core-plugin-definitions.ts
core/src/web/toast.ts
ios/Capacitor/Capacitor/Plugins/Toast.swift

* use same duration for long and short toasts on ios, android and web (closes #2175 )
* make `short` the default on all platforms
* make android and ios actually use the duration option
* I used this test app to test the toast duration: https://github.com/pwespi/toast-test/

fix(toast): unify duration across platforms

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java
core/src/core-plugin-definitions.ts
core/src/web/filesystem.ts
electron/src/electron/filesystem.ts
ios/Capacitor/Capacitor/Plugins/Filesystem.swift

createIntermediateDirectories was deprecated in Capacitor 1.3.0 and has been showing a warning if used
removing it for Capacitor 2.0
recursive was implemented in 1.3.0 and has the same effect
closes #2005

feat(Filesystem): Remove createIntermediateDirectories from MkdirOptions

---

android-template/app/src/main/res/drawable/launch_splash.xml
site/docs-md/apis/splash-screen/index.md

This file is no longer used. Instead, configure the splash screen image with the `androidSplashResourceName` configuration option.

chore(android): remove unused launch_splash.xml

---

electron-template/index.js
electron/index.js

It's been deprecated since Capacitor 1.1.0 and not working in new electron versions (5+)
closes #2139

feat(electron): Remove injectCapacitor function

---

site/docs-md/apis/network/index.md

Hi,
While reading the documentation, I found a deadlink, and this article no longer exists.

docs(network): Remove example guide because of dead link

---

ios/Capacitor/Capacitor/Plugins/Geolocation.swift

If `enableHighAccuracy` is set, use `kCLLocationAccuracyBestForNavigation` only for `watchPosition()` and `kCLLocationAccuracyBest` for `getCurrentPosition()`
If `enableHighAccuracy` is not set, use `kCLLocationAccuracyThreeKilometers` for fastest results.
closes #1893

feat(ios): change native location accuracy values

---

site/docs-md/community/plugins.md

Hi,
Simply remove deprecated plugins add the category set of plugins with the replacement of the deprecated plugins.

docs(ce-plugins): Remove or replace deprecated plugins

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeActivity.java
android/capacitor/src/main/java/com/getcapacitor/Plugin.java

feat(android): Handle onDestroy lifecycle event in plugins

---

ios/Capacitor/Capacitor/Plugins/Clipboard.swift

Clipboard plugin is not returning errors, so in some cases it doesn't resolve nor reject, causing the app to hang.
This PR return errors
closes #2426

fix(ios): Make Clipboard plugin return errors

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Device.java
core/src/core-plugin-definitions.ts
core/src/web/device.ts
electron/src/electron/device.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/Device.swift

Remove batteryLevel and isCharging from getInfo
Create new getBatteryInfo function with batteryLevel and isCharging
Closes #2311

feat(Device): Add getBatteryInfo function

---

ios-template/App/Podfile
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/Plugins/StatusBar.swift
site/docs-md/basics/opening-native-projects.md
site/docs-md/getting-started/dependencies.md
site/docs-md/guides/push-notifications-firebase.md
site/docs-md/ios/index.md

Change docs to say only Xcode 11+ is supported
Remove code that was present to support Xcode 10
Closes #2405

chore(ios): drop Xcode 10 support

---

android/capacitor/src/main/java/com/getcapacitor/Dialogs.java
android/capacitor/src/main/java/com/getcapacitor/plugin/Modals.java
core/src/core-plugin-definitions.ts
core/src/web/modals.ts
electron/src/electron/modals.ts
ios/Capacitor/Capacitor/Plugins/Modals.swift

closes https://github.com/ionic-team/capacitor/issues/2473

feat(modals): add inputText property to prompt for prefilled text

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/BridgeWebViewClient.java

closes https://github.com/ionic-team/capacitor/issues/2230

feat(android): provide WebViewClient accessor

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java
core/package-lock.json
core/src/core-plugin-definitions.ts
core/src/web/filesystem.ts
electron/src/electron/filesystem.ts
example/src/pages/filesystem/filesystem.ts
ios/Capacitor/Capacitor/Plugins/Filesystem.swift

feat(Filesystem): make writeFile return the file uri

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java
core/src/web/local-notifications.ts
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

iOS and Android weren't returning a proper LocalNotificationScheduleResult (according to the types)
On web it was returning a proper LocalNotificationScheduleResult, but didn't include the id.
closes #2152

fix(LocalNotifications): return proper LocalNotificationScheduleResult on schedule

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/PluginResult.java
android/capacitor/src/main/java/com/getcapacitor/plugin/App.java
core/src/core-plugin-definitions.ts

feat(android): make AppRestoredResult also returns error info and success boolean

---

core/src/web/modals.ts
electron/src/electron/modals.ts

uses new pwa-action-sheet from ionic/pwa-elements
closes #2462

fix(modals): make showActions work on web and electron

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Modals.java

showActions is non cancelable on iOS and web, make it non cancelable on Android too to avoid apps hanging on the await

fix(android): Make Modals.showActions non cancelable

---

cli/src/ios/update.ts

don't try to read source-file tags with framework attribute as they might be directories
closes #2506

fix(cordova): handle source-file with framework attribute

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/UIStatusBarManager+CAPHandleTapAction.m

use swizzling to implement statusTap for iOS 13
closes #2109

fix(ios): implement statusTap for iOS 13

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Filesystem.java
core/src/core-plugin-definitions.ts
example/src/pages/filesystem/filesystem.ts
ios/Capacitor/Capacitor/Plugins/Filesystem.swift
site/docs-md/apis/filesystem/index.md

It has never worked as intended, so I'm removing it.
If using it on Android, just replace it with `FilesystemDirectory.Data` as it was pointing to the same native folder
closes #2312

feat(Filesystem): remove FilesystemDirectory.Application

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java
android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts
core/src/web/local-notifications.ts
ios/Capacitor/Capacitor/CAPUNUserNotificationCenterDelegate.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift
ios/Capacitor/Capacitor/Plugins/PushNotifications.swift

Added a new `requestPermission` method to `PushNotifications` and `LocalNotifications`
On Android it just return `granted: true` since there are no permissions needed
Register and schedule no longer prompt for permissions, `requestPermission` have to be called first.
closes #1797
closes #2406

feat: add requestPermission to PushNotifications and LocalNotifications

---

scripts/deploy.sh

iOS script sometimes fails on Capacitor as it depends on CapcitorCordova, and if it fails, Android is not published.
Publish Android first to avoid forgetting to manually publish it if it failed.

chore: make deploy script publish Android before iOS

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java
android/capacitor/src/main/java/com/getcapacitor/PluginHandle.java

Since Capacitor uses reflection it was catching any exception the reflection could cause, but that was also hiding any possible crash a plugin might have and make it impossible for crash reporters such as Crashlytics to report those issues.
This PR changes the `invoke` exception handling to not catch `InvocationTargetException` nor `IllegalAccessException`, and throw them as a `RuntimeException`
closes #2150

feat(android): Allow plugin methods to crash

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Clipboard.java
core/src/core-plugin-definitions.ts
core/src/web/clipboard.ts
ios/Capacitor/Capacitor/Plugins/Clipboard.swift

removed the Clipboard.read() options (type)
Now the keyboard will always return what it has, and instead of the user passing a type, it returns a type with the mime type of the data the clipboard has.
also writes image data as plain text
closes #2365
closes https://github.com/ionic-team/capacitor/issues/375

feat(clipboard): remove Clipboard.read() options

---

android/capacitor/src/main/java/com/getcapacitor/Plugin.java
cli/src/cordova.ts

* fix(android): plugin retained events not being retained if listeners were empty (#2408)
* fix(cli): Avoid AndroidManifest.xml not found error on add (#2400)

V1.x patches

---

android/capacitor/src/main/java/com/getcapacitor/PluginCall.java
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPPluginCall.h
ios/Capacitor/Capacitor/CAPPluginCall.m
ios/Capacitor/Capacitor/CAPPluginCall.swift
ios/Capacitor/Capacitor/JS.swift

This allows plugin calls to reject with a node like code (string) 
`call.reject("Error message", "ERROR_CODE");`

feat: Allow plugins to reject with a string code

---

ios/Capacitor/Capacitor/CAPBridge.swift

In Xcode 11.4 beta, Capacitor apps crash with
> NSForwarding: warning: object 0x1d64f3b70 of class 'PFEmbeddedMulticasterImplementation' does not implement methodSignatureForSelector: -- trouble ahead
> NSForwarding: warning: object 0x1d64f3b70 of class 'PFEmbeddedMulticasterImplementation' does not implement doesNotRecognizeSelector: -- abort
Do not merge yet in case Apple fix it in a future release, but have the change around just in ase

fix(ios): avoid crash on registerPlugins on Xcode 11.4

---

android/capacitor/src/main/java/com/getcapacitor/Bridge.java

Currently, Capacitor does not yet support Android fragments.
To overcome this limitation, I implemented my own `BridgeFragment`, which is similar to `BridgeActivity`. To do so, I found it useful to make `Bridge.restoreInstanceState()` a public method.
More generally, I suggest to treat `Bridge.java` as a pseudo-public API that can be used by any developer. The reason is that the existing Bridge implementations might not cover every case that is necessary for integrations in complex native codebases.

feat(android): Make Bridge.restoreInstanceState() public

---

lerna.json
scripts/deploy.sh

remove capacitor electron from lerna so it's not released with the other capacitor packages, but uses it's own versioning.

chore: remove electron from lerna

---

example/src/pages/clipboard/clipboard.ts

Clipboard.read() removed the options, so example was failing to build.
This PR removes the options from the Clipboard.read() example code.

chore(example): Fix Clipboard.read()

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Accessibility.java

Don't throw the `UnsupportedOperationException` since it was implemented.

fix(android): Avoid Accessibility.speak() crash

---

android/capacitor/src/main/java/com/getcapacitor/plugin/camera/CameraSettings.java
core/src/core-plugin-definitions.ts

Was true on Android, false on iOS.
This PR unify the value to false and document it on the types.

feat(camera): Unify saveToGallery default value to false

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

`FEATURE_CAMERA` only checks if the rear camera, `FEATURE_CAMERA_ANY` allows any camera.

fix(android): don't return NO_CAMERA_ERROR if any camera is present

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
android/capacitor/src/main/java/com/getcapacitor/plugin/camera/CameraUtils.java

If `saveToGallery` was used, the camera plugin tried to write on `getExternalStoragePublicDirectory`, which is deprecated on Android 10.
`Intent.ACTION_MEDIA_SCANNER_SCAN_FILE` is also deprecated, so changing the save to gallery code to use `MediaStore.Images.Media.insertImage` instead. 
closes #2555

fix(android): make camera work on Android 10

---

ios/Capacitor/Capacitor/Plugins/Clipboard.swift

Web and Android return text/plain instead of text/html for text and urls, so unify the types.

fix(ios): make Clipboard.read return text/plain

---

android-template/app/src/main/AndroidManifest.xml

When the app is used in multi window mode, the app gets restarted at first and on any resize, this change avoids it.
Also avoids restarts when changing the uiMode.

feat(android): avoid app restart on activity resize or uiMode change

---

electron/src/electron/filesystem.ts

Currently `appendFile` on electron is broken because the parameters are in the wrong order.
Also if data was `binary` the append would not work correctly because the string did not get converted to a `buffer`

fix(electron): correct implementation of Filesystem.appendFile

---

site/docs-md/android/updating.md

docs(update guide): fix targetSdkVersion instructions 

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java

It's using `Notification` instead of `NotificationCompat`, which might cause problems in Android versions.

fix(android): Use NotificationCompat constant for setting visibility

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Share.java
example/src/pages/share/share.html
example/src/pages/share/share.ts

Currently, without this fix, either text only or url only sharing does not work.
I added two more buttons on example app to show that now it is working.

fix(android): allow Share plugin to provide text or url only

---

site/src/components/site-header/site-header.tsx

The GitHub link has a "targetblank" icon but the link hasn't. Same for the socials links, they have a target blank in the footer but not in the header.

docs(site): Add target blank to external links in site header

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotification.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java
core/src/core-plugin-definitions.ts
example/android/app/src/main/assets/capacitor.config.json
example/capacitor.config.json
example/ios/IonicRunner/IonicRunner/capacitor.config.json
example/src/pages/local-notifications/local-notifications.html
example/src/pages/local-notifications/local-notifications.ts
site/docs-md/apis/local-notifications/index.md

Good day,
I was finding that I needed to customize quite a few things with android local notifications so I decided to put my first PR in to see how it goes.  
This PR adds the ability to set an icon color in android.  You can do it with the plugin definition or globally in the config.
If this is something the community is interested in... i have already done something similar to make the notification expandable and can put that PR in at some point in the future as well.

feat(android): added configurable icon color for local notifications

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

fix(ios): Make Camera.getPhoto return exif from gallery photos

---

ios/Capacitor/Capacitor/Plugins/Camera.swift

First time contributor.
Noticed that nothing was being returned from `Camera.getPhoto()` on iOS  if source is `CameraSource.Prompt` and 'Cancel' is selected. 
fixes #2196

fix(ios): return error if Cancel is selected from Camera.getPhoto() prompt

---

site/docs-md/guides/push-notifications-firebase.md

Capacitor 2.0 requires to call `requestPermission` to prompt the user, change the guide code to use it before registering.
Also update some Ionic CLI changes since the guide was created.
Add a missing `}` on the full page example

docs(firebase-guide): update guide with Capacitor 2.0 changes

---

site/docs-md/getting-started/dependencies.md

Capacitor 2.0 supports iOS 11+ (same as 1.x), so remove the example text where it says  11 & 12 as 13 is also supported and might be confusing.
pod repo update is not needed if using CocoaPods 1.7.2 or newer, so removing the note.
java is not required as Android studio ships with its own JDK.

docs(dependencies): update to latest Capacitor

---

README.md
site/CONTRIBUTING.md

Original doc looks to have been copied from the Stencil docs. Updated.

docs: Update site/docs Contributing readme

---

core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/CAPBridgeViewController.swift
ios/Capacitor/Capacitor/Plugins/StatusBar.swift

This adds an option to the status bar `show` and `hide` methods to change the animation style. The style will always default to `.slide` if not specified in the options (other options are `.fade` and `.none`. This is iOS only. I considered adding this as a plugin config that could be configured in `capacitor.config.json` but there could be use cases to change this on each show and hide.

feat(ios): set status bar animation style when showing and hiding

---

android/capacitor/src/main/java/com/getcapacitor/JSObject.java

make JSObject.getString return null value (or default value) if a null javascript value was passed
closes #2590

feat(android): make JSObject.getString return null instead of 'null' string

---

android/capacitor/src/main/java/com/getcapacitor/plugin/StatusBar.java
core/src/core-plugin-definitions.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/StatusBar.swift
site/docs-md/apis/status-bar/index.md

Addition of a new method in the core Statusbar plugin, similar to the `overlaysWebView` method/preference of the cordova statusbar plugin. Updated example in the docs for the Statusbar plugin.
Works only for android (as discussed in [#1876](https://github.com/ionic-team/capacitor/issues/1876)) since on iOS it already handles it correctly on devices with notches.
I'm not confident in my android knowledge these days, so I might have overlooked something. But in my tests everything worked as expected, similar to the cordova plugin.
What I'm not sure about is the correct way to handle that the iOS version of the plugin doesn't implement this feature. I added it with a `"not implemented"` response in the `Statusbar.swift` file but I'm not sure if that is all that's needed here.

feat(android): Add Statusbar.setOverlaysWebView method

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

This fixes #1761 so the splash screen doesn't override the status bar color when it's visible. The reason this was broken was the flags were not getting applied from the window properly. It should have been: 
```
a.getWindow().getAttributes().flags | (WindowManager.LayoutParams.FLAG_FULLSCREEN);
```
instead of
```
a.getWindow().getAttributes().flags & (WindowManager.LayoutParams.FLAG_FULLSCREEN);
```
but the fullscreen flag was replicating the behavior of the `splashFullScreen` config, so I removed it.
`splashImage.setFitsSystemWindows(true);` is required so the splash screen does not appear behind the action bar.

fix(android): maintain status bar color during splash

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java

This adds additional flag to capacitor config called `splashImmersive` that allows to hide not only status bar (achieved by using already existing `splashFullScreen` flag) but also software navigation bar. More info available here https://developer.android.com/training/system-ui/immersive#immersive
This particular configuration uses "Sticky Immersive" approach https://developer.android.com/training/system-ui/immersive#sticky-immersive
closes #2423

feat(android): Add immersive configuration to Splash

---

android/capacitor/src/main/java/com/getcapacitor/plugin/App.java
core/src/core-plugin-definitions.ts
core/src/web/app.ts
electron/src/electron/app.ts
ios/Capacitor/Capacitor/Plugins/App.swift
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m

feat(App): Add getState method to check current app state

---

site/docs-md/apis/splash-screen/index.md

Adds documentation for following additions
1. https://github.com/ionic-team/capacitor/pull/2302
2. https://github.com/ionic-team/capacitor/pull/2425

docs(Splash): document splashFullScreen and splashImmersive config options

---

android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
core/src/core-plugin-definitions.ts

Add lights and lightColor properties to PushNotificationChannel, so can be used on `createChannel` and returned by `listChannels`.
This allows to enable led light for push notifications and configure it's color (if the device supports it)
Also make `description` and `sound` optional since the native code had default values for when they are not provided. 
closes #2547

feat(android): Add lights and lightColor to PushNotificationChannel

---

cli/src/common.ts
cli/src/index.ts

If `npx cap init` is called but a `capacitor.config.json` already exists, use the values there as defaults.
This is specially important for react apps as some guides tell users to run `npx cap init` after ionic integration, and that sets the webDir value to www instead of build.

feat(cli): make init use values from capacitor.config.json as defaults

---

cli/src/common.ts

If there isn't a name already set in `capacitor.config.json` and init is called without providing a name, use the package.json name field as default value.

feat(cli): use name from package.json as default name

---

site/docs-md/android/updating.md
site/docs-md/ios/updating.md

variables.gradle is not mandatory on beta 1
add new recommended changes

docs(updating): Include beta 1 updating steps

---

site/docs-md/apis/camera/index.md

Capacitor's camera plugin is require three permission: https://github.com/ionic-team/capacitor/blob/master/ios/Capacitor/Capacitor/Plugins/Camera.swift#L348-L373
But now, docs said require one permission. This pull request is fix this.
Thanks.

fix(docs/camera): add usage descriptions for using in iOS

---

cli/package-lock.json
cli/src/ios/update.ts

CocoaPods doesn't allow `vendored_libraries` whose name don't start with lib, patched the CLI to add lib to the .a files that don't start with lib
closes #2632

fix(cordova): Add lib prefix to .a library names

---

core/src/core-plugin-definitions.ts

Explain a bit about the available FilesystemDirectory options, what they are, when they should be used, behavior when the app is deleted, Android 10+ problems.

docs(types): explain FilesystemDirectory options

---

ios/Capacitor/Capacitor/Plugins/Filesystem.swift

the url returned from absoluteString makes fileExists return false on the root folder, use path instead, it works with root and child folders.
closes #2667

fix(ios): writeFile failing on root folders

---

android-template/app/src/main/res/xml/file_paths.xml
android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java
core/src/core-plugin-definitions.ts
example/android/app/src/main/res/xml/file_paths.xml
ios/Capacitor/Capacitor/Plugins/Camera.swift

Change saveToGallery behavior to:
If from camera and not edited: save original
If from camera and edited: save edited
If from gallery and not edited: don't save
If from gallery and edited: save edited
Old behavior was:
iOS:
If from camera and not edited: save original
If from camera and edited: save edited
If from gallery and not edited: save again (changes behavior)
If from gallery and edited: save edited
Android:
If from camera and not edited: save original
If from camera and edited: save original (changes behavior)
If from gallery and not edited: don't save 
If from gallery and edited: don't save (changes behavior)
Also fixes a problem where gallery images couldn't be edited

feat(camera): unify saveToGallery behavior

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java

If the notification was scheduled with every or on options, it will crash when trying to set the `when` time.
So set it only if at is not null to prevent the crash.
closes #2639

fix(android): make LocalNotification not crash on showing when

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/Plugins/Browser.swift
ios/Capacitor/Capacitor/TmpViewController.swift

Add utility `presentVC` and `dismissVC` methods in the bridge for plugins to use.
They use a temporary window and temporary view controller, so the webview javascript execution is not frozen when the view controller is presented.
Changed the Browser implementation to use this two new methods so it fixes https://github.com/ionic-team/capacitor/issues/2660

feat(ios): add presentVC and dismissVC methods to bridge

---

android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotification.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java
core/src/core-plugin-definitions.ts
site/docs-md/apis/local-notifications/index.md

Allow to configure a default notification sound from capacitor.config.json file.
Also fixes and documents the regular LocalNotification sound
closes https://github.com/ionic-team/capacitor/issues/2657

feat(android): Allow to configure a default LocalNotification sound

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java
android/capacitor/src/main/java/com/getcapacitor/plugin/PushNotifications.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotification.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/NotificationChannelManager.java
core/src/core-plugin-definitions.ts
core/src/web/local-notifications.ts
ios/Capacitor/Capacitor/Plugins/DefaultPlugins.m
ios/Capacitor/Capacitor/Plugins/LocalNotifications.swift

Starting in Android 8.0 (API level 26), all notifications must be assigned to a channel. For each channel, you can set the visual and auditory behaviour that is applied to all notifications in that channel. Then, users can change these settings and decide which notification channels from your app should be intrusive or visible at all.
This PR is for allowing channel feature to LocalNotification. The first user needs to create a Notification channel with `createChannel` method and then assign `channelId` at the time of scheduling notification. If no `channelId` is provided will use the default channel and if provided `channelId` does not exist, the notification will not be generated.
Fixes #2675

feat(LocalNotifications): add createChannel, deleteChannel and listChannels methods

---

android/capacitor/src/main/java/com/getcapacitor/plugin/LocalNotifications.java
android/capacitor/src/main/java/com/getcapacitor/plugin/notification/LocalNotificationManager.java

feat(LocalNotifications): Allow to create notifications without activity

---

site/docs-md/community/plugins.md

I have written a capacitor plugin that enables the webview to listen for dark mode change events on Android, Web/PWA and electron. I'll be adding iOS support soon. Using this plugin apps can toggle its dark theme as soon as the platform's dark theme changes.

docs(ce-plugins): Add capacitor-dark-mode plugin

---

site/docs-md/README.md

it was documented, but never added to the side menu

docs(permissions): Display permissions page on side menu

---

android/capacitor/src/main/java/com/getcapacitor/Splash.java
site/docs-md/apis/splash-screen/index.md

Prioritise `splashImmersive` over `splashFullScreen` if both flags are set.
closes #2700

chore(android): Improve handling of splashImmersive and splashFullScreen preferences

---

site/docs-md/android/updating.md

closes https://github.com/ionic-team/capacitor/issues/2695

docs(updating): Add some 2.0.0 missing information

---

ios/Capacitor/Capacitor/CAPBridge.swift
ios/Capacitor/Capacitor/Plugins/Browser.swift

the tmpWindow doesn't work fine when using popover presentation, and since popover presentation doesn't freeze the javascript, changed the code to not use the tmpWindow when the presentation is popover
closes https://github.com/ionic-team/capacitor/issues/2711

fix(ios): don't use the tmpWindow on popover presentation

---

cli/src/common.ts

The CLI tries to default to the package.json name, but on create there is no package.json yet. 
closes #2721

fix(cli): avoid error on create command

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Modals.java
android/capacitor/src/main/java/com/getcapacitor/ui/ModalsBottomSheetDialogFragment.java
core/src/core-plugin-definitions.ts

Display the title on Modals.showActions
Document that message is iOS only
closes #2723

fix(android): display title on Modals.showActions

---

cli/src/android/add.ts
cli/src/common.ts
cli/src/ios/add.ts

Running `cap add android` should add the same version of the android platform as the rest of Capacitor. With these changes, it runs `npm install @capacitor/<platform>@<version>` so a very specific version is installed.
We could also look for the version of `@capacitor/core`, which might make more sense.

fix(cli): match platform version with cli version on add command

---

cli/src/ios/update.ts

Only system libraries should be added to libraries section, but since it's hard to know if the library is a system library or not, at least don't include a library in libraries section if it's also on vendored_libraries section
closes #2642

fix(cordova): Don't add as system library if it's a vendored library

---

site/docs-md/community/plugins.md

Remove `capacitor-apple-login` as the github package has been removed (unknown why)

docs(ce-plugins): Remove capacitor-apple-login

---

cli/src/common.ts

We were showing an info message if the CLI version was newer than the platform versions, but makes more sense to warn (because it's serious and can cause issues) if the core version doesn't match the platform version.
Only do it at minor or major level, since at patch level the types shouldn't have changed.

fix(cli): Warn if core version doesn't match platform version

---

electron/src/electron/modals.ts

fix(electron): Update Modals Plugin to use new dialog async syntax

---

cli/src/electron/add.ts

fix(cli): use appName as package.json name on electron project

---

site/docs-md/apis/keyboard/index.md

docs(keyboard): Add missing import in example

---

android/capacitor/src/main/java/com/getcapacitor/plugin/Camera.java

closes https://github.com/ionic-team/capacitor/issues/2766

fix(android): avoid camera crash on photo edit cancel
